-- ============================================================
-- ENRICHISSEMENT FORMATIONS 1-3 : modules et leçons supplémentaires
-- ============================================================

-- ============================================================
-- FORMATION 1 : Finance Personnelle & Investissement en Afrique
-- Ajout modules 6-8
-- ============================================================
DO $$ DECLARE
  v_course_id uuid;
  v_mod6 uuid; v_mod7 uuid; v_mod8 uuid;
  v_max_pos int;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'finance-personnelle-investissement-afrique';
  SELECT COALESCE(MAX(position), 0) INTO v_max_pos FROM modules WHERE course_id = v_course_id;

  INSERT INTO modules (course_id, title, position) VALUES
    (v_course_id, 'Planification de la retraite en Afrique', v_max_pos + 1),
    (v_course_id, 'Finance d''entreprise familiale et PME', v_max_pos + 2),
    (v_course_id, 'Outils numériques de gestion financière personnelle', v_max_pos + 3);

  SELECT id INTO v_mod6 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos LIMIT 1;
  SELECT id INTO v_mod7 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 1 LIMIT 1;
  SELECT id INTO v_mod8 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 2 LIMIT 1;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES

  -- Module 6 : Planification retraite
  (v_mod6, v_course_id, 'Pourquoi planifier sa retraite dès aujourd''hui en Afrique', 'document', 1, false,
   E'# Pourquoi planifier sa retraite dès aujourd''hui\n\n## La réalité des retraites en Afrique subsaharienne\nDans la plupart des pays d''Afrique de l''Ouest, le système de retraite public (CNPS, CNRPS, RCAR...) couvre moins de **15% de la population active**. La grande majorité des travailleurs, notamment les indépendants, commerçants et entrepreneurs, n''ont aucune protection formelle.\n\n## Les 3 piliers d''une retraite africaine solide\n\n### Pilier 1 : L''immobilier\nAvoir sa maison payée avant la retraite est la priorité numéro 1. Une maison sans loyer équivaut à un revenu mensuel économisé.\n\n**Calcul simple :**\n- Loyer moyen Abidjan (appartement modeste) : 150 000 XOF/mois\n- Sur 20 ans de retraite : 150 000 × 240 = **36 000 000 XOF économisés**\n\n### Pilier 2 : Les revenus passifs\n- Loyers d''un bien immobilier locatif\n- Dividendes BRVM\n- Activité commerciale légère transmise aux enfants\n\n### Pilier 3 : L''épargne investie\n- Assurance vie épargne (SUNU, NSIA, Allianz)\n- Fonds communs de placement\n- Or physique (valeur refuge traditionnel)\n\n## La règle des 25 fois\nPour générer 300 000 XOF/mois de revenus passifs, vous avez besoin d''un capital de :\n```\nCapital nécessaire = Revenu mensuel × 12 × 25\n= 300 000 × 12 × 25 = 90 000 000 XOF\n```\nCela semble énorme — mais avec 30 ans de capitalisation à 8%/an, il suffit d''épargner **70 000 XOF/mois** dès aujourd''hui.\n\n## Action immédiate\nCalculez votre âge de retraite cible et le nombre d''années dont vous disposez. Chaque année perdue double presque l''effort d''épargne requis.'),

  (v_mod6, v_course_id, 'Les produits d''épargne retraite disponibles en zone UEMOA', 'document', 2, false,
   E'# Produits d''épargne retraite en zone UEMOA\n\n## 1. L''assurance vie épargne (produit le plus accessible)\n\n### Fonctionnement\n- Versements réguliers (mensuel, trimestriel)\n- Capital garanti + participation aux bénéfices\n- Exonération fiscale sur les primes dans certains pays\n\n### Compagnies agréées CIMA\n| Compagnie | Pays | Rendement moyen |\n|-----------|------|----------------|\n| SUNU Assurances | CI, Sénégal, Togo... | 4-5% |\n| NSIA Vie | CI, Gabon, Congo | 4-6% |\n| Allianz Afrique | Plusieurs pays | 3-5% |\n| AXA Afrique | CI, Cameroun | 4-5% |\n\n### Conseil : Le plan épargne retraite (PER)\nCertaines compagnies proposent des PER spécifiques avec :\n- Versements libres ou programmés\n- Capital ou rente à la retraite\n- Option décès incluse\n\n## 2. Les OPCVM (Organismes de Placement Collectif)\nDisponibles via les SGI de la BRVM :\n- **Sicav obligataires** : rendement 5-7%, risque faible\n- **Sicav actions** : rendement potentiel 10-15%, risque modéré\n- **Fonds diversifiés** : mélange des deux\n\n## 3. L''or physique\nTradition africaine séculaire. L''or conserve son pouvoir d''achat sur le long terme.\n- **Forme recommandée** : lingots ou pièces certifiées\n- **Conservation** : coffre bancaire\n- **Rendement** : corrélé au dollar, protection contre l''inflation CFA\n\n## 4. La tontine structurée\nAméliorez la tontine traditionnelle :\n- Contrat écrit entre membres\n- Compte bancaire dédié\n- Investissement des fonds non distribués en BRVM ou immobilier\n\n## Plan d''action selon l''âge\n| Âge | Priorité |\n|-----|----------|\n| 20-30 ans | Commencer petit (10 000 XOF/mois), habitude |\n| 30-40 ans | Accélérer, viser 15-20% du revenu |\n| 40-50 ans | Maximiser, réduire les dettes |\n| 50+ ans | Consolider, sécuriser les actifs |'),

  (v_mod6, v_course_id, 'Simuler et optimiser votre épargne retraite', 'document', 3, false,
   E'# Simuler votre épargne retraite\n\n## L''outil de simulation en 5 étapes\n\n### Étape 1 : Définir votre cible\n- Âge de retraite souhaité : ___\n- Revenu mensuel souhaité à la retraite : ___ XOF\n- Durée de retraite estimée : ___ ans\n\n### Étape 2 : Calculer le capital nécessaire\n```\nCapital = Revenu mensuel × 12 × (1 / Taux de retrait)\n```\nAvec un taux de retrait de 4% (règle des 25x) :\n```\nEx : 400 000 XOF/mois × 12 / 0,04 = 120 000 000 XOF\n```\n\n### Étape 3 : Calculer l''épargne mensuelle nécessaire\nFormule de capitalisation :\n```\nÉpargne mensuelle = Capital × i / ((1+i)^n - 1)\n```\nOù :\n- i = taux mensuel (taux annuel / 12)\n- n = nombre de mois restants\n\n**Exemple concret :**\n- Capital cible : 120 000 000 XOF\n- Années restantes : 25 ans (300 mois)\n- Rendement : 7%/an → 0,583%/mois\n\n```\nÉpargne = 120 000 000 × 0,00583 / ((1,00583)^300 - 1)\n        = 699 600 / (5,72 - 1)\n        = 699 600 / 4,72\n        ≈ 148 220 XOF/mois\n```\n\n### Étape 4 : Répartir vos investissements\n| Allocation | Produit | Rendement cible |\n|------------|---------|----------------|\n| 40% | Immobilier | 7-9% |\n| 30% | Assurance vie épargne | 5-6% |\n| 20% | BRVM (actions) | 10-15% |\n| 10% | Or physique | 5-8% |\n\n### Étape 5 : Réviser annuellement\nChaque année, ajustez en fonction de :\n- Augmentation de vos revenus\n- Performance des investissements\n- Changements de situation familiale\n\n## Les erreurs à ne pas commettre\n1. **Toucher à l''épargne retraite** pour des dépenses courantes\n2. **Mettre tous ses œufs dans l''immobilier** sans liquidités\n3. **Négliger l''assurance vie** : si vous décédez avant la retraite, votre famille doit pouvoir continuer\n4. **Attendre d''avoir plus d''argent** : commencez maintenant, même avec 20 000 XOF/mois'),

  -- Module 7 : Finance entreprise familiale
  (v_mod7, v_course_id, 'Séparer finances personnelles et finances d''entreprise', 'document', 1, false,
   E'# Séparer finances personnelles et finances d''entreprise\n\n## Le piège le plus courant des entrepreneurs africains\nLa majorité des PME africaines qui échouent ne manquent pas de clients — elles meurent de confusion entre l''argent personnel et l''argent de l''entreprise.\n\n## Les conséquences de la confusion\n1. **Impossibilité de mesurer la rentabilité réelle**\n2. **Prise de décision sans données fiables**\n3. **Crise de trésorerie imprévue**\n4. **Difficultés à obtenir un crédit bancaire**\n5. **Conflits familiaux** (quand les membres de la famille puisent dans la caisse)\n\n## La solution : La structure financière minimale\n\n### Pour une entreprise individuelle\n1. **Compte bancaire professionnel séparé** : toutes les recettes y entrent, toutes les dépenses pro en sortent\n2. **Salaire du dirigeant fixé** : vous vous payez comme un employé (ex : 20% du CA net)\n3. **Dividendes trimestriels** : si bénéfices, vous vous distribuez un complément\n\n### Pour une SARL/SARLU\n- Le capital social doit rester intouché\n- Le compte courant d''associé est un prêt de vous à l''entreprise\n- La rémunération du gérant est fixée par statuts\n\n## Le tableau de bord financier minimum\n```\nCA mensuel                      : X XOF\n- Achats/coûts variables        : X XOF\n= Marge brute                   : X XOF\n- Charges fixes (loyer, salaires): X XOF\n= Résultat d''exploitation       : X XOF\n- Salaire dirigeant             : X XOF\n= Bénéfice net                  : X XOF\n```\n\n## Exercice pratique\nOuvrez un compte bancaire professionnel cette semaine. Si vous êtes déjà en activité, retracez les 3 derniers mois et calculez votre vrai bénéfice net.'),

  (v_mod7, v_course_id, 'Accéder au financement bancaire et aux microcrédits en Afrique', 'document', 2, false,
   E'# Accéder au financement en Afrique\n\n## Les obstacles spécifiques aux PME africaines\n- Manque de garanties réelles (titre foncier, véhicule...)\n- Historique de crédit insuffisant\n- États financiers non certifiés\n- Méconnaissance des produits disponibles\n\n## Les sources de financement selon le stade\n\n### Démarrage (0 - 12 mois)\n| Source | Montant typique | Taux |\n|--------|----------------|------|\n| Tontine familiale | 500k - 5M XOF | 0% |\n| Microfinance (Advans, Baobab, CMS) | 200k - 3M XOF | 2-4%/mois |\n| Fonds d''amorçage (Hub Africa, etc.) | Variable | Equity |\n\n### Croissance (1-3 ans)\n| Source | Montant typique | Condition |\n|--------|----------------|----------|\n| Crédit PME bancaire | 3-50M XOF | 2 ans d''existence, bilans |\n| Fonds de garantie (FAGACE, FSA) | Jusqu''à 80% du crédit | Dossier |\n| Leasing équipement | Variable | Bien en garantie |\n\n### Expansion (3+ ans)\n- **Capital-investissement** : fonds comme I&P, Cauris, Africinvest\n- **Obligations** : financement sur la BRVM pour les grandes PME\n- **Financement export** : AFREXIMBANK pour les exportateurs\n\n## Constituer un dossier bancaire solide\n\n### Les 5 documents indispensables\n1. **Statuts de la société** (ou registre de commerce)\n2. **3 derniers bilans comptables** (ou déclarations fiscales)\n3. **Plan de trésorerie 12 mois** (entrants et sortants mois par mois)\n4. **Business plan** (présentation du projet financer)\n5. **Justificatifs des garanties** (titre foncier, assurance nantissement)\n\n## Conseil clé : La relation bancaire\nOuvrez un compte professionnel 6 mois AVANT d''avoir besoin de crédit. Faites transiter votre CA par ce compte. Les banques prêtent en priorité à leurs clients qu''elles connaissent.'),

  (v_mod7, v_course_id, 'Planifier la succession et transmission de votre patrimoine entrepreneurial', 'document', 3, false,
   E'# Transmission du patrimoine entrepreneurial\n\n## Pourquoi c''est urgent en Afrique\nDans la culture africaine, parler de sa mort est tabou. Pourtant, des milliers d''entreprises familiales disparaissent à chaque génération faute de préparation. L''entreprise qui a mis 20 ans à se construire peut s''effondrer en quelques mois si rien n''est préparé.\n\n## Les scénarios de transmission\n\n### 1. Transmission aux enfants\n**Avantages :** continuité familiale, confiance\n**Risques :** compétences insuffisantes, conflits entre héritiers\n\n**Comment préparer :**\n- Former les successeurs dès aujourd''hui (intégrez-les dans l''entreprise)\n- Définir qui prend quelle responsabilité\n- Fixer des critères objectifs (diplôme, expérience minimale)\n\n### 2. Vente à un tiers\n**Avantages :** liquidité immédiate, valorisation objective\n**Processus :**\n1. Valorisation de l''entreprise (2-5x le résultat net annuel)\n2. Audit de l''acheteur\n3. Protocole d''accord\n4. Acte de cession chez le notaire\n\n### 3. Management buy-out (MBO)\nVendre à vos propres managers/employés.\n**Avantages :** continuité culturelle, personnel motivé\n**Financement :** crédit bancaire + épargne des repreneurs\n\n## La valorisation de votre entreprise\n\n### Méthodes simples\n```\nValeur = Résultat net × Coefficient sectoriel\n\nCoefficients indicatifs :\n- Commerce         : 1-2x\n- Services         : 2-4x\n- Industrie légère : 3-5x\n- Technologie      : 4-8x\n```\n\n### Ce qui augmente la valeur\n- Clients fidèles (contrats pluriannuels)\n- Marque reconnue\n- Processus documentés (pas de dépendance au fondateur)\n- Équipe stable\n\n## Le pacte familial\nDocument non légalement contraignant mais moralement fort qui définit :\n- La gouvernance de l''entreprise familiale\n- Les règles d''entrée des membres de la famille\n- La politique de dividendes\n- Le processus de décision en cas de désaccord'),

  -- Module 8 : Outils numériques
  (v_mod8, v_course_id, 'Applications et outils gratuits pour gérer ses finances personnelles', 'document', 1, false,
   E'# Applications de gestion financière personnelle\n\n## Les meilleures apps disponibles en Afrique\n\n### 1. Applications de budget\n\n**Money Manager** (Android/iOS)\n- Saisie rapide des dépenses\n- Catégorisation automatique\n- Graphiques de répartition\n- **Gratuit**, disponible en français\n\n**YNAB (You Need A Budget)**\n- Méthode budgétaire structurée\n- Synchronisation multi-devices\n- **Payant** (15$/mois) mais très puissant\n\n**Wallet by BudgetBakers**\n- Connexion aux comptes bancaires africains (partiellement)\n- Budgets par catégorie\n- **Gratuit** avec options premium\n\n### 2. Mobile Money : votre outil de traçabilité\nLes applications Wave, Orange Money, MTN MoMo gardent un historique de toutes vos transactions. Exploitez-le !\n\n**Comment utiliser Wave pour budgéter :**\n1. Téléchargez l''historique mensuel\n2. Catégorisez chaque transaction\n3. Comparez mois par mois\n\n### 3. Google Sheets (gratuit) : la solution universelle\n\n**Modèle de budget mensuel simple :**\n```\nFeuille 1 : Revenus\n- Salaire/CA mensuel\n- Revenus locatifs\n- Autres revenus\n= Total revenus\n\nFeuille 2 : Dépenses\n- Logement\n- Alimentation\n- Transport\n- Éducation enfants\n- Santé\n- Obligations sociales\n- Épargne/Investissement\n= Total dépenses\n\nFeuille 3 : Bilan\n= Revenus - Dépenses (solde du mois)\n```\n\n## Automatiser votre épargne\n**La méthode Pay Yourself First :**\nDès réception de votre salaire/revenus, transférez automatiquement votre épargne AVANT toute autre dépense. Configurez un virement automatique vers votre compte épargne le jour de la paie.\n\n## Outils de suivi des investissements BRVM\n- **Site BRVM** (brvm.org) : cours en temps réel\n- **Application BRVM** : alertes de cours\n- **Rapport SGI** : votre portefeuille mensuel par email'),

  (v_mod8, v_course_id, 'Cryptomonnaies et fintech africaines : opportunités et précautions', 'document', 2, false,
   E'# Cryptomonnaies et fintech africaines\n\n## L''Afrique est-elle prête pour les crypto ?\nL''Afrique subsaharienne est la région du monde avec la plus forte croissance d''adoption des cryptomonnaies. En 2023, le Kenya, l''Afrique du Sud et le Nigeria figurent dans le top 20 mondial d''adoption.\n\n**Pourquoi cette adoption :**\n- Inflation des monnaies locales dans certains pays\n- Envois de fonds moins chers que Western Union\n- Accès aux services financiers sans banque\n- Population jeune et technophile\n\n## Les cryptomonnaies les plus utilisées en Afrique\n\n### Bitcoin (BTC)\n- Réserve de valeur\n- Envois internationaux\n- **Risque : volatilité extrême** (-70% possible)\n\n### USDT / USDC (stablecoins)\n- Liés au dollar américain\n- Protection contre l''inflation des monnaies locales\n- **Usage pratique** : épargne en dollar sans compte bancaire\n\n### CELO / autres blockchains Africa-focused\n- Conçues pour les marchés émergents\n- Transaction peu chères et rapides\n\n## Les plateformes disponibles en Afrique\n| Plateforme | Pays | Dépôt local |\n|------------|------|-------------|\n| Binance P2P | Partout | Mobile Money |\n| Yellow Card | CI, Sénégal... | Mobile Money, Virement |\n| Mara | Afrique de l''Est | Mobile Money |\n| Quidax | Nigeria | Virement |\n\n## Précautions ESSENTIELLES\n\n### ⚠️ Les risques réels\n1. **Volatilité** : le Bitcoin peut perdre 80% en 6 mois\n2. **Arnaques** : 90% des "projets crypto africains" sont des fraudes\n3. **Perte de clés** : sans votre clé privée, vos crypto sont perdues\n4. **Régulation** : certains pays interdisent ou encadrent les crypto\n\n### Règles de prudence\n- Ne jamais investir plus de 5-10% de votre épargne en crypto\n- Utiliser uniquement des plateformes réglementées\n- Stocker vos crypto dans un wallet matériel (hardware wallet) si montants importants\n- Ne jamais partager votre phrase de récupération\n\n## Les fintech africaines prometteuses\n- **Wave** (CI, Sénégal) : services financiers mobiles\n- **Djamo** (CI) : néobanque adaptée aux besoins locaux\n- **Julaya** (CI) : paiements B2B\n- **Paydunya** : passerelle de paiement e-commerce');

END $$;


-- ============================================================
-- FORMATION 2 : Marketing Digital pour PME Africaines
-- Ajout modules 5-8
-- ============================================================
DO $$ DECLARE
  v_course_id uuid;
  v_mod5 uuid; v_mod6 uuid; v_mod7 uuid; v_mod8 uuid;
  v_max_pos int;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'marketing-digital-pme-africaines';
  SELECT COALESCE(MAX(position), 0) INTO v_max_pos FROM modules WHERE course_id = v_course_id;

  INSERT INTO modules (course_id, title, position) VALUES
    (v_course_id, 'Email Marketing et Automatisation pour PME', v_max_pos + 1),
    (v_course_id, 'SEO et Référencement pour Marchés Africains', v_max_pos + 2),
    (v_course_id, 'Publicité Payante : Meta Ads et Google Ads en Afrique', v_max_pos + 3),
    (v_course_id, 'Analytics et Mesure de Performance Marketing', v_max_pos + 4);

  SELECT id INTO v_mod5 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos LIMIT 1;
  SELECT id INTO v_mod6 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 1 LIMIT 1;
  SELECT id INTO v_mod7 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 2 LIMIT 1;
  SELECT id INTO v_mod8 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 3 LIMIT 1;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES

  -- Module 5 : Email Marketing
  (v_mod5, v_course_id, 'Construire sa liste email depuis zéro en Afrique', 'document', 1, false,
   E'# Construire sa liste email en Afrique\n\n## Pourquoi l''email reste le canal le plus rentable\nEn marketing digital, l''email génère en moyenne **42$ de retour pour chaque dollar investi** (ROI de 4200%). C''est largement supérieur aux réseaux sociaux.\n\n**En Afrique, l''email est particulièrement pertinent car :**\n- WhatsApp Business peut être coupé ou suspendu\n- Les algorithmes Facebook limitent votre portée organique\n- Vous ne possédez pas vos abonnés sur les réseaux sociaux\n- Une liste email vous appartient vraiment\n\n## Les stratégies de collecte adaptées à l''Afrique\n\n### 1. Le lead magnet (aimant à prospects)\nOffrez quelque chose de valeur en échange d''un email :\n- **Guide PDF gratuit** : "Les 10 erreurs à éviter quand on vend en ligne en Côte d''Ivoire"\n- **Mini-formation gratuite** : 3 vidéos sur votre expertise\n- **Checklist** : "Checklist pour ouvrir votre boutique sur Jumia"\n- **Réduction** : -10% sur la première commande\n\n### 2. La page de capture (landing page)\nOutils gratuits/abordables :\n- **Mailchimp** (gratuit jusqu''à 500 contacts)\n- **MailerLite** (gratuit jusqu''à 1000 contacts)\n- **Brevo (ex-Sendinblue)** : interface en français\n\n### 3. Les points de collecte physiques\nDans les pays africains, beaucoup de clients sont d''abord en contact physique :\n- Carnet de visite avec QR code vers votre formulaire\n- Tablet en boutique pour s''inscrire\n- Lors d''événements/salons professionnels\n\n## Structurer votre séquence de bienvenue\n\n**Email 1 (immédiat)** : Livraison du lead magnet + présentation chaleureuse\n**Email 3 (J+2)** : Votre histoire, pourquoi vous faites ce métier\n**Email 5 (J+5)** : Votre meilleur conseil gratuit\n**Email 7 (J+7)** : Présentation de votre offre principale\n\n## Bonnes pratiques pour l''Afrique\n- Écrivez dans la langue de votre audience (français, wolof, dioula...)\n- Évitez les images lourdes (connexion internet variable)\n- Envoyez le mardi ou jeudi matin (meilleurs taux d''ouverture)\n- Objet d''email : max 50 caractères, commencez par un bénéfice'),

  (v_mod5, v_course_id, 'Créer des campagnes email qui convertissent', 'document', 2, false,
   E'# Campagnes email qui convertissent\n\n## Anatomie d''un email de vente efficace\n\n### 1. L''objet (ligne la plus importante)\nL''objet détermine si l''email est ouvert. Formules qui fonctionnent :\n\n- **Question** : "Savez-vous combien vous perdez chaque mois ?"\n- **Urgence** : "Offre valable jusqu''au [date]"\n- **Curiosité** : "J''ai découvert quelque chose d''intéressant pour vous"\n- **Bénéfice direct** : "Comment doubler vos ventes en 60 jours"\n- **Chiffre** : "7 techniques de vente que j''aurais voulu connaître plus tôt"\n\n### 2. L''accroche (première phrase)\nDoit donner envie de lire la suite. Exemples :\n- "Il y a quelques semaines, un de mes clients a multiplié ses ventes par 3..."\n- "Je vais vous révéler la stratégie que 95% des PME africaines ignorent..."\n\n### 3. Le corps du message\nStructure AIDA :\n- **A**ttention : accroche forte\n- **I**ntérêt : problème que vous résolvez\n- **D**ésir : bénéfices concrets, preuves sociales\n- **A**ction : appel à l''action clair (un seul bouton)\n\n### 4. Le CTA (Call To Action)\n- Un seul bouton par email\n- Texte actif : "Réserver ma place" (pas "Cliquez ici")\n- Couleur contrastée\n- Taille visible sur mobile\n\n## Métriques à suivre\n| Métrique | Benchmark Afrique | Action si insuffisant |\n|----------|------------------|-----------------------|\n| Taux d''ouverture | > 20% | Améliorer l''objet |\n| Taux de clic | > 2% | Améliorer le CTA |\n| Taux de désabonnement | < 1% | Revoir la fréquence/contenu |\n| Taux de délivrabilité | > 95% | Nettoyer la liste |\n\n## Automatisation intelligente\n\n### Séquences à automatiser en priorité\n1. **Bienvenue** : 5 emails sur 2 semaines\n2. **Panier abandonné** : 3 emails sur 3 jours (si e-commerce)\n3. **Relance inactifs** : email de ré-engagement à 60 jours sans ouverture\n4. **Anniversaire client** : email personnalisé avec offre spéciale\n\n## Outils recommandés\n- **Brevo** : meilleure interface en français, SMS africain intégré\n- **Mailchimp** : simple et gratuit pour débuter\n- **ActiveCampaign** : automatisation avancée (payant)'),

  (v_mod5, v_course_id, 'WhatsApp Marketing professionnel pour PME africaines', 'document', 3, false,
   E'# WhatsApp Marketing Professionnel\n\n## Pourquoi WhatsApp est incontournable en Afrique\nAvec plus de **500 millions d''utilisateurs actifs en Afrique**, WhatsApp est de loin le canal de communication le plus utilisé. En Côte d''Ivoire, au Sénégal, au Cameroun ou au Bénin, presque tout le monde communique par WhatsApp.\n\n**Statistiques clés :**\n- Taux de lecture des messages WhatsApp : **98%** (contre 20% pour l''email)\n- Réponse en moins d''une heure dans la plupart des cas\n- Utilisé aussi bien en zone urbaine que rurale\n\n## WhatsApp Business vs WhatsApp API\n\n### WhatsApp Business (pour les TPE/PME)\n**Gratuit**, téléchargeable sur le Play Store/App Store\n**Fonctionnalités :**\n- Profil professionnel (horaires, adresse, site web)\n- Messages automatiques (bienvenue, absence)\n- Étiquettes pour classer les clients\n- Catalogue de produits\n- Statistiques de messages\n\n### WhatsApp Business API (pour les entreprises avec volume)\n**Payant**, accès via des partenaires (Twilio, Vonage, Brevo...)\n**Pour les entreprises avec >1000 messages/jour**\n\n## Stratégies WhatsApp qui fonctionnent\n\n### 1. Les groupes de communauté\nCréez un groupe WhatsApp pour vos meilleurs clients :\n- Partagez des conseils exclusifs\n- Annoncez les promotions en avant-première\n- Recueillez des feedbacks\n\n**Règle d''or :** Maximum 3 messages par semaine pour ne pas saturer.\n\n### 2. Les statuts WhatsApp (stories)\nVos contacts voient vos statuts. Utilisez-les pour :\n- Montrer les coulisses de votre business\n- Partager des témoignages clients\n- Annoncer des promotions flash (valables 24h)\n\n### 3. Les messages diffusion (broadcast)\nEnvoyez un message à plusieurs contacts sans créer un groupe.\n**Limite :** les destinataires doivent avoir votre numéro enregistré.\n\n## Construction de votre base WhatsApp\n1. Collectez les numéros avec consentement explicite\n2. Dites exactement quelle valeur vous allez apporter\n3. Permettez de se désinscrire facilement\n4. Organisez vos contacts avec les étiquettes WhatsApp Business\n\n## Ce qu''il ne faut pas faire\n- Spammer des numéros inconnus (risque de bannissement)\n- Envoyer trop de messages promotionnels\n- Négliger les questions sans réponse\n- Utiliser WhatsApp personnel pour le business'),

  -- Module 6 : SEO
  (v_mod6, v_course_id, 'SEO local : être trouvé sur Google par vos clients africains', 'document', 1, false,
   E'# SEO Local pour PME Africaines\n\n## Pourquoi le SEO local est votre meilleure opportunité\nQuand un client à Abidjan tape "meilleur restaurant poulet braisé Cocody" sur Google, il y a une intention d''achat immédiate. Si votre établissement apparaît en premier, vous avez de très bonnes chances d''avoir un nouveau client.\n\nLe SEO local est une opportunité massive en Afrique car **la concurrence est encore faible** dans la plupart des niches et villes.\n\n## Google My Business : votre vitrine gratuite\n\n### Configuration complète (étapes)\n1. Créer/revendiquer votre fiche sur **google.com/business**\n2. Compléter **100% des informations**\n   - Nom exact de l''entreprise\n   - Catégorie principale (et secondaires)\n   - Adresse précise\n   - Horaires d''ouverture\n   - Numéro de téléphone WhatsApp\n   - Site web\n   - Description (250 mots minimum)\n3. Ajouter des **photos professionnelles** (minimum 10)\n   - Façade de votre local\n   - Produits/services\n   - Équipe\n   - Clients (avec accord)\n4. Collecter des **avis Google**\n   - Envoyez le lien d''avis à vos clients satisfaits\n   - Répondez à tous les avis (positifs et négatifs)\n\n## Les mots-clés locaux à cibler\n\n### Formule : Service + Ville/Quartier\n- "Comptable Abidjan Plateau"\n- "Formation Excel Dakar"\n- "Boutique vêtements enfants Cotonou"\n- "Plombier Douala urgence"\n\n### Comment trouver vos mots-clés\n1. **Google Suggest** : tapez le début de votre service sur Google\n2. **Google Keyword Planner** (gratuit avec compte Google Ads)\n3. **Ubersuggest** (gratuit limité)\n4. **Questions fréquentes de vos clients** : les mots qu''ils utilisent vraiment\n\n## Votre site web optimisé pour le SEO local\n\n### Éléments indispensables\n- **Balise Title** de chaque page : incluez votre ville\n- **Meta description** : 150 caractères avec ville et service\n- **Page "À propos"** : mentionnez votre zone de service\n- **Page "Contact"** : adresse complète, plan Google Maps intégré\n- **Vitesse de chargement** : critique pour les connexions africaines\n\n## Mesurer vos résultats\n- **Google Search Console** : mots-clés qui vous amènent du trafic\n- **Google Analytics** : comportement des visiteurs\n- **Google My Business Insights** : vues, clics, appels depuis votre fiche'),

  (v_mod6, v_course_id, 'Créer du contenu qui positionne votre PME en experte', 'document', 2, false,
   E'# Content Marketing pour PME Africaines\n\n## Le content marketing : se faire trouver plutôt que chercher les clients\nAu lieu de courir après les clients, publiez du contenu utile qui les attire naturellement vers vous. Un artisan plombier qui publie des articles "Comment éviter les fuites d''eau en saison des pluies à Abidjan" sera trouvé par des centaines de propriétaires chaque mois.\n\n## Les formats de contenu selon votre audience\n\n### Blog / Articles de fond\n**Quand l''utiliser :** audience professionnelle, B2B, services à haute valeur\n**Longueur idéale :** 800-1500 mots\n**Fréquence :** 2 articles/mois minimum\n\n**Idées de sujets pour PME africaines :**\n- "Comment choisir un [votre produit] de qualité au Sénégal"\n- "Les 5 erreurs à éviter quand vous [problème de votre client]"\n- "Comparatif : [Option A] vs [Option B] — laquelle choisir ?"\n- "Guide complet : [processus que vos clients ne comprennent pas]"\n\n### Vidéos YouTube / TikTok\n**Quand l''utiliser :** produits visuels, démonstrations, enseignement\n**Durée idéale :** \n- TikTok/Reels : 30-90 secondes\n- YouTube tutoriel : 5-15 minutes\n\n### Podcasts\nEn forte croissance en Afrique francophone. Idéal pour :\n- Partager votre expertise en déplacement\n- Interviewer des clients ou partenaires\n- Construire une communauté de fidèles\n\n## Calendrier éditorial : planifier sur 3 mois\n\n```\nSemaine 1 : Article de blog (pilier)\nSemaine 2 : 3 posts Instagram/LinkedIn issus de l''article\nSemaine 3 : Vidéo courte sur un point clé de l''article\nSemaine 4 : Newsletter email avec le meilleur contenu du mois\n```\n\n## Recycler votre contenu\nUn seul article de fond peut devenir :\n- 5 posts Instagram\n- 1 vidéo YouTube\n- 3 stories\n- 1 email newsletter\n- 1 thread LinkedIn\n- 1 infographie\n\n**C''est la stratégie du "Content Hub" : créez une fois, diffusez partout.**\n\n## Mesurer l''efficacité de votre contenu\n| Objectif | Métrique | Outil |\n|----------|---------|-------|\n| Trafic | Visites/mois | Google Analytics |\n| SEO | Position mots-clés | Search Console |\n| Engagement | Likes, commentaires, partages | Analytics natifs |\n| Conversions | Leads, ventes issues du contenu | CRM ou Google Analytics |'),

  -- Module 7 : Publicité payante
  (v_mod7, v_course_id, 'Meta Ads (Facebook/Instagram) : cibler les clients africains', 'document', 1, false,
   E'# Meta Ads pour le Marché Africain\n\n## Pourquoi Meta Ads est puissant en Afrique\nFacebook et Instagram comptent plus de **400 millions d''utilisateurs en Afrique**. La publicité y est encore **10 à 20 fois moins chère** qu''en Europe ou aux États-Unis pour des résultats comparables.\n\n**Coût moyen par clic en Afrique de l''Ouest :**\n- Facebook : 0,05 - 0,30 USD\n- Instagram : 0,08 - 0,50 USD\n- Contre 0,50 - 3,00 USD en France\n\n## Créer votre première campagne Meta Ads\n\n### Étape 1 : Créer un compte Business Manager\n1. Rendez-vous sur **business.facebook.com**\n2. Ajoutez votre Page Facebook professionnelle\n3. Créez un compte publicitaire\n4. Ajoutez un moyen de paiement (carte Visa prépayée, PayPal)\n\n> **Astuce :** Certaines banques africaines (Ecobank, UBA, Coris) émettent des cartes Visa prépayées rechargeables via mobile money.\n\n### Étape 2 : Choisir l''objectif de votre campagne\n| Objectif | Usage |\n|----------|-------|\n| Notoriété | Faire connaître votre marque |\n| Trafic | Envoyer des visiteurs sur votre site |\n| Engagement | Obtenir likes, commentaires, partages |\n| Leads | Collecter des contacts (formulaire intégré) |\n| Ventes | Achats sur votre boutique en ligne |\n| Messages | Démarrer des conversations WhatsApp/Messenger |\n\n**Pour les PME africaines débutantes : commencez par "Messages" vers WhatsApp.**\n\n### Étape 3 : Cibler votre audience\n\n**Ciblage géographique**\n- Pays + ville spécifique (ex : Abidjan — Cocody, Plateau)\n- Rayon autour d''une adresse (ex : 5 km de votre boutique)\n\n**Ciblage démographique**\n- Âge : 25-45 ans (pouvoir d''achat)\n- Langue : Français\n- Appareil : Mobile (90% des utilisateurs africains)\n\n**Ciblage par centres d''intérêt**\n- Comportements d''achat en ligne\n- Intérêts liés à votre secteur\n- Audiences similaires (lookalike) de vos meilleurs clients\n\n### Étape 4 : Budget et durée\n**Budget recommandé pour débuter :** 5 000 - 15 000 XOF/jour\n**Durée test :** 7-14 jours minimum pour obtenir des données fiables\n\n## Créer des visuels qui captent l''attention en Afrique\n- Utilisez des personnages africains (votre cible doit se reconnaître)\n- Texte court (20% max de la surface de l''image)\n- Couleurs vives et contrastées\n- Montrez le résultat/bénéfice, pas le produit seul\n- Sous-titrez vos vidéos (beaucoup regardent sans son)\n\n## Analyser et optimiser vos campagnes\n**KPIs essentiels :**\n- CPM (coût pour 1000 impressions) : < 500 XOF = bon\n- CTR (taux de clic) : > 1% = bon\n- CPC (coût par clic) : < 100 XOF = excellent\n- CPL (coût par lead) : dépend de votre marge'),

  (v_mod7, v_course_id, 'Google Ads pour PME africaines : apparaître en premier sur Google', 'document', 2, false,
   E'# Google Ads pour PME Africaines\n\n## Google Ads vs Facebook Ads : quelle différence ?\n\n| | Google Ads | Facebook Ads |\n|--|------------|-------------|\n| **Intention** | Forte (client cherche activement) | Faible (client découvre) |\n| **Coût** | Plus élevé par clic | Moins cher par clic |\n| **Délai** | Résultats immédiats | Résultats à moyen terme |\n| **Idéal pour** | Services, urgences, B2B | Notoriété, e-commerce, B2C |\n\n**Règle simple :** Si vos clients cherchent votre service sur Google → Google Ads. Si vos clients ne savent pas encore qu''ils ont besoin de vous → Facebook Ads.\n\n## Configuration Google Ads pas à pas\n\n### 1. Créer votre compte\n1. ads.google.com → Nouveau compte\n2. Objectif : "Obtenir plus d''appels ou de visites en magasin"\n3. Facturation : carte Visa ou virement bancaire\n\n### 2. Choisir vos mots-clés\nCatégories de mots-clés :\n- **Requête large** : "plombier abidjan" → large audience, coût faible\n- **Expression exacte** : "plombier urgence abidjan cocody" → plus précis\n- **Mots-clés négatifs** : excluez "gratuit", "formation", "comment faire"\n\n### 3. Rédiger vos annonces\nStructure d''une annonce Search :\n```\nTitre 1 (30 car.) : Plombier Abidjan 24h/24\nTitre 2 (30 car.) : Intervention en 1h — Devis Gratuit\nTitre 3 (30 car.) : Plus de 500 clients satisfaits\nDescription 1 (90 car.) : Fuite d''eau, robinetterie, chauffe-eau... Nos plombiers certifiés interviennent partout à Abidjan.\nDescription 2 (90 car.) : Appelez maintenant ou réservez en ligne. Disponibles 7j/7 y compris weekends et jours fériés.\n```\n\n## Extensions d''annonce à activer\n- **Extension d''appel** : bouton d''appel direct depuis l''annonce\n- **Extension de lieu** : affiche votre adresse\n- **Extension de liens annexes** : liens vers vos pages clés\n- **Extension de prix** : affichez vos tarifs\n\n## Budget et enchères pour débutants\n**Budget journalier recommandé :** 3 000 - 10 000 XOF/jour\n**Stratégie d''enchères :** Commencez avec "CPC manuel" pour contrôler vos coûts\n\n## Mesurer le retour sur investissement\n```\nROI = (Chiffre d''affaires généré - Dépenses publicitaires) / Dépenses × 100\n\nExemple :\nDépenses pub : 50 000 XOF\nCA généré : 350 000 XOF\nROI = (350 000 - 50 000) / 50 000 × 100 = 600%\n```\nSi votre ROI est > 300%, continuez et augmentez le budget.'),

  -- Module 8 : Analytics
  (v_mod8, v_course_id, 'Google Analytics 4 : comprendre vos visiteurs africains', 'document', 1, false,
   E'# Google Analytics 4 pour PME Africaines\n\n## Pourquoi mesurer est indispensable\n"Ce qui ne se mesure pas ne s''améliore pas." Sans Analytics, vous gérez votre marketing à l''aveugle — vous dépensez de l''argent sans savoir ce qui fonctionne.\n\n## Installer Google Analytics 4 (GA4)\n\n### Sur votre site WordPress\n1. Créer un compte sur **analytics.google.com**\n2. Créer une propriété (nom de votre entreprise)\n3. Obtenir votre ID de mesure (G-XXXXXXXXXX)\n4. Installer le plugin "Site Kit by Google" sur WordPress\n5. Connecter votre propriété GA4\n\n### Sur votre site Shopify/WooCommerce\nSuivez le guide officiel dans Paramètres → Intégrations → Google\n\n## Les rapports essentiels pour votre PME\n\n### 1. Rapport Acquisition\n**Question : D''où viennent mes visiteurs ?**\n- Organique (Google naturel) : votre SEO fonctionne\n- Direct : personnes qui connaissent déjà votre marque\n- Réseaux sociaux : Facebook, Instagram\n- Email : vos campagnes email\n- Payant : vos publicités\n\n### 2. Rapport Engagement\n**Question : Que font les visiteurs sur mon site ?**\n- Pages les plus vues\n- Durée de session\n- Taux de rebond (% qui partent sans interagir)\n\n### 3. Rapport Démographie\n**Question : Qui sont mes visiteurs ?**\n- Âge et genre\n- Pays et ville (crucial pour confirmer votre cible géographique)\n- Appareils (mobile vs desktop)\n\n**En Afrique, attendez-vous à 80-90% de trafic mobile.**\n\n## Tableau de bord simple à créer\n\nCréez un rapport personnalisé avec ces métriques hebdomadaires :\n| Métrique | Cette semaine | Semaine dernière | Évolution |\n|----------|--------------|------------------|-----------|\n| Visites totales | | | |\n| Nouvelles vs retours | | | |\n| Source principale | | | |\n| Page la plus vue | | | |\n| Taux de conversion | | | |\n\n## Objectifs de conversion à configurer\nDites à GA4 ce qui compte pour vous :\n- Clics sur votre numéro de téléphone\n- Remplissage du formulaire de contact\n- Temps passé > 2 minutes sur votre site\n- Visite de la page "Tarifs" ou "Contact"\n\nCes données vous montrent quelles sources marketing vous apportent vraiment des clients, pas seulement des visiteurs.');

END $$;


-- ============================================================
-- FORMATION 3 : Excel & Google Sheets Avancé
-- Ajout modules 5-8
-- ============================================================
DO $$ DECLARE
  v_course_id uuid;
  v_mod5 uuid; v_mod6 uuid; v_mod7 uuid; v_mod8 uuid;
  v_max_pos int;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'excel-google-sheets-avance-professionnels';
  SELECT COALESCE(MAX(position), 0) INTO v_max_pos FROM modules WHERE course_id = v_course_id;

  INSERT INTO modules (course_id, title, position) VALUES
    (v_course_id, 'Tableaux Croisés Dynamiques Avancés', v_max_pos + 1),
    (v_course_id, 'Power Query et Connexion à des Données Externes', v_max_pos + 2),
    (v_course_id, 'Macros VBA et Automatisation Excel', v_max_pos + 3),
    (v_course_id, 'Tableaux de Bord et Visualisation Professionnelle', v_max_pos + 4);

  SELECT id INTO v_mod5 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos LIMIT 1;
  SELECT id INTO v_mod6 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 1 LIMIT 1;
  SELECT id INTO v_mod7 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 2 LIMIT 1;
  SELECT id INTO v_mod8 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 3 LIMIT 1;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES

  -- Module 5 : TCD Avancés
  (v_mod5, v_course_id, 'Maîtriser les Tableaux Croisés Dynamiques de A à Z', 'document', 1, false,
   E'# Tableaux Croisés Dynamiques Avancés\n\n## Rappel : Qu''est-ce qu''un TCD ?\nUn TCD (Tableau Croisé Dynamique) transforme une liste de données brutes en rapport synthétique interactif en quelques clics. C''est l''outil le plus puissant d''Excel pour l''analyse de données.\n\n## Préparer vos données pour un TCD\n\n### Règles d''or\n1. **Une ligne = un enregistrement** (pas de lignes vides, pas de sous-totaux)\n2. **Une colonne = un champ** (entêtes claires en ligne 1)\n3. **Données homogènes** dans chaque colonne (pas de mélange texte/nombre)\n4. **Pas de cellules fusionnées**\n\n### Mise sous forme de Tableau (recommandé)\n```\nSélectionner les données → Ctrl+T\n→ Cocher "Mon tableau comporte des en-têtes"\n→ OK\n```\nLe tableau s''adapte automatiquement quand vous ajoutez des données.\n\n## Créer un TCD\n```\nInsertion → Tableau croisé dynamique\n→ Sélectionner votre tableau\n→ Nouvelle feuille de calcul\n→ OK\n```\n\n## Les 4 zones du TCD\n\n| Zone | Rôle | Exemple |\n|------|------|---------|\n| **Filtres** | Filtrer tout le rapport | Année, Région |\n| **Colonnes** | Répartir en colonnes | Mois, Trimestre |\n| **Lignes** | Répartir en lignes | Produit, Client |\n| **Valeurs** | Ce qu''on calcule | CA, Quantité |\n\n## Calculs dans les valeurs\nPar défaut : somme. Clic droit → Paramètres des champs de valeurs :\n- Nombre (COUNT)\n- Moyenne\n- Max / Min\n- % du total général\n- % du total de la ligne/colonne\n- Différence par rapport à...\n\n## Champs calculés\nCréez des calculs personnalisés dans le TCD :\n```\nAnalyse → Champs, éléments et jeux → Champ calculé\nNom : "Marge brute"\nFormule : =CA - Coûts\n→ Ajouter → OK\n```\n\n## TCD Avancé : Groupement des données\n\n### Grouper des dates\nCliquez sur une date dans le TCD → clic droit → Grouper\nChoix : Jours, Mois, Trimestres, Années\n\n### Grouper des nombres\nEx : Grouper les CA par tranches (0-1M, 1M-5M, >5M)'),

  (v_mod5, v_course_id, 'Graphiques Croisés Dynamiques et Segments Interactifs', 'document', 2, false,
   E'# Graphiques Croisés Dynamiques et Interactivité\n\n## Graphique Croisé Dynamique (GCD)\nUn GCD est lié à votre TCD — il se met à jour automatiquement quand vous modifiez le TCD.\n\n### Créer un GCD\n```\nCliquer dans le TCD\n→ Analyse → Graphique croisé dynamique\n→ Choisir le type de graphique\n→ OK\n```\n\n### Types de graphiques recommandés\n| Objectif | Type de graphique |\n|----------|------------------|\n| Évolution dans le temps | Courbes |\n| Comparaison entre catégories | Barres horizontales |\n| Contribution au total | Secteurs (camembert) |\n| Corrélation | Nuage de points |\n| Composition + évolution | Barres empilées |\n\n## Segments (Slicers) — filtres visuels interactifs\n\n### Ajouter des segments\n```\nCliquer dans le TCD\n→ Analyse → Insérer un segment\n→ Cocher les champs voulus (ex : Région, Produit, Période)\n→ OK\n```\n\n### Connecter un segment à plusieurs TCD\nSi votre dashboard a plusieurs TCD :\n```\nClic droit sur le segment\n→ Connexions de rapport\n→ Cocher tous les TCD à connecter\n```\nMaintenant, un clic filtre tous les TCD simultanément.\n\n## Chronologie — filtre de dates\n```\nCliquer dans le TCD avec des dates\n→ Analyse → Insérer une chronologie\n→ OK\n```\nFaisez glisser pour sélectionner une période.\n\n## Construire un tableau de bord TCD complet\n\n### Architecture recommandée\n1. **Feuille "Données"** : vos données brutes (masquée)\n2. **Feuille "TCD"** : vos tableaux croisés (masquée)\n3. **Feuille "Dashboard"** : votre tableau de bord avec graphiques et segments\n\n### Mise en page du dashboard\n- Fond sombre ou clair uniforme\n- Titre et logo en haut\n- KPIs clés en grands chiffres\n- Graphiques principaux au centre\n- Filtres/segments à gauche ou en haut\n- Masquer les quadrillage (Vue → décocher Quadrillage)\n\n## Automatiser la mise à jour\nSi vos données changent régulièrement :\n```\nCliquer dans le TCD\n→ Analyse → Modifier la source de données\n```\nOu, si votre source est un tableau Excel, le TCD se met à jour via Actualiser (Alt+F5).'),

  (v_mod5, v_course_id, 'Fonctions de recherche avancées : INDEX/EQUIV et XLOOKUP', 'document', 3, false,
   E'# Fonctions de Recherche Avancées\n\n## Pourquoi INDEX/EQUIV est supérieur à VLOOKUP\n\nVLOOKUP (RECHERCHEV) a trois limitations majeures :\n1. Ne peut chercher qu''à gauche → droite\n2. Sensible au déplacement de colonnes\n3. Lent sur grandes bases de données\n\nINDEX/EQUIV résout les trois problèmes.\n\n## Comprendre INDEX et EQUIV séparément\n\n### EQUIV (MATCH)\nRetourne la **position** d''une valeur dans une plage\n```\n=EQUIV("Abidjan"; A2:A100; 0)\n→ Retourne 5 si "Abidjan" est en 5ème position\n```\nLe 3ème argument : 0 = correspondance exacte\n\n### INDEX\nRetourne la **valeur** d''une cellule selon sa position\n```\n=INDEX(B2:B100; 5)\n→ Retourne la valeur de la 5ème cellule de B2:B100\n```\n\n## La combinaison INDEX/EQUIV\n\n```\n=INDEX(plage_résultat; EQUIV(valeur_cherchée; plage_recherche; 0))\n```\n\n**Exemple concret :**\nVous cherchez le CA d''un client dans votre base :\n```\n=INDEX(C:C; EQUIV("Client ABC"; A:A; 0))\n```\n→ Trouve "Client ABC" dans la colonne A, retourne la valeur correspondante de la colonne C\n\n## INDEX/EQUIV double (recherche sur 2 critères)\n\n```\n=INDEX(plage_résultat;\n  EQUIV(1; (plage1=critère1) * (plage2=critère2); 0))\n```\n⚠️ Cette formule est une **formule matricielle** : validez avec **Ctrl+Shift+Entrée**\n\n**Exemple :** Trouver le CA de "Produit X" dans "Région Nord"\n```\n=INDEX(D:D; EQUIV(1; (A:A="Produit X")*(B:B="Région Nord"); 0))\n```\n\n## XLOOKUP (Excel 365 / Excel 2021)\n\nSi vous avez Excel 365, utilisez XLOOKUP — plus simple que INDEX/EQUIV :\n```\n=XLOOKUP(valeur_cherchée; plage_recherche; plage_résultat; [si_non_trouvé])\n```\n\n**Exemple :**\n```\n=XLOOKUP("Client ABC"; A:A; C:C; "Non trouvé")\n```\n\n**Avantages de XLOOKUP :**\n- Cherche dans les deux sens\n- Gère les erreurs nativement\n- Peut retourner plusieurs colonnes\n- Plus lisible\n\n## Application pratique : Base clients PME\n\n**Scénario :** Vous avez une feuille "Commandes" et une feuille "Clients". Ramenez automatiquement le nom, la ville et le solde du client dans chaque commande :\n```\n=XLOOKUP([@ID_Client]; Clients[ID]; Clients[Nom]; "Client inconnu")\n=XLOOKUP([@ID_Client]; Clients[ID]; Clients[Ville]; "")\n=XLOOKUP([@ID_Client]; Clients[ID]; Clients[Solde]; 0)\n```'),

  -- Module 6 : Power Query
  (v_mod6, v_course_id, 'Power Query : Importer et transformer des données automatiquement', 'document', 1, false,
   E'# Power Query : La Révolution de l''Import de Données\n\n## Qu''est-ce que Power Query ?\nPower Query est l''outil intégré d''Excel (et Google Sheets via des extensions) qui permet d''importer des données depuis n''importe quelle source, les nettoyer et les transformer automatiquement — sans une seule formule.\n\n**Cas d''usage typiques en Afrique :**\n- Consolider les rapports de vente de 12 agences en un seul tableau\n- Importer automatiquement les données d''une API (données BRVM, taux de change...)\n- Nettoyer des exports CSV de votre logiciel de gestion\n- Fusionner deux bases de données (clients + commandes)\n\n## Accéder à Power Query\n```\nDonnées → Obtenir des données\n```\n\n## Sources de données disponibles\n- **Fichier** : Excel, CSV, TXT, JSON, XML\n- **Base de données** : SQL Server, MySQL, PostgreSQL, Access\n- **En ligne** : SharePoint, OData, API web\n- **Dossier** : importer tous les fichiers d''un dossier d''un coup\n\n## Nettoyer des données avec Power Query\n\n### Opérations courantes\n```\nAccueil → Supprimer les lignes vides\nAccueil → Supprimer les doublons\nTransformer → Supprimer les espaces\nTransformer → Modifier le type (texte, nombre, date...)\nTransformer → Fractionner la colonne (par délimiteur)\nAjouter une colonne → Colonne personnalisée\n```\n\n### Exemple : Nettoyer un export CSV de caisse\n1. Importer le CSV (Données → À partir du texte/CSV)\n2. Power Query s''ouvre automatiquement\n3. Supprimer les colonnes inutiles\n4. Corriger les types de données (date, montant)\n5. Filtrer les lignes nulles ou erreurs\n6. Fermer et charger dans Excel\n\n**La magie :** La prochaine fois, un clic sur "Actualiser" refait tout automatiquement.\n\n## Consolider plusieurs fichiers identiques\n\n**Scénario :** Vous recevez un rapport Excel par mois (Jan.xlsx, Fev.xlsx...)\n\n```\nDonnées → Obtenir des données → À partir d''un fichier → À partir d''un dossier\n→ Sélectionner le dossier qui contient tous vos fichiers mensuels\n→ Power Query les combine automatiquement\n```\n\nAjoutez un nouveau fichier mensuel dans le dossier → Actualisez → Il apparaît automatiquement.\n\n## Fusionner deux tables (équivalent JOIN SQL)\n\n```\nAccueil → Fusionner des requêtes\n→ Sélectionner la table 2\n→ Sélectionner la colonne clé commune (ex : ID_Client)\n→ Type de fusion : Externe gauche (conserve tous les enregistrements de la table 1)\n→ OK\n```\n\nExpandez la colonne fusionnée pour afficher les champs voulus de la table 2.'),

  (v_mod6, v_course_id, 'Google Sheets : fonctions avancées et collaboration en temps réel', 'document', 2, false,
   E'# Google Sheets Avancé\n\n## Pourquoi Google Sheets en Afrique ?\nEn Afrique, Google Sheets présente des avantages uniques :\n- **Gratuit** (contrairement à Excel qui coûte cher)\n- **Fonctionne dans le navigateur** (pas besoin d''installer quoi que ce soit)\n- **Collaboration temps réel** (plusieurs personnes modifient simultanément)\n- **Accessible sur mobile** avec une connexion 3G/4G\n- **Sauvegarde automatique dans le cloud**\n\n## Fonctions exclusives à Google Sheets\n\n### QUERY — SQL dans vos feuilles\nLa fonction la plus puissante de Google Sheets :\n```\n=QUERY(données; "SELECT A, B, SUM(C) WHERE D = ''Abidjan'' GROUP BY A, B ORDER BY SUM(C) DESC")\n```\n\nExemple concret :\n```\n=QUERY(Ventes!A:E; "SELECT A, B, SUM(C) WHERE E = ''2024'' GROUP BY A, B LABEL SUM(C) ''Total CA''")\n```\n→ Calcule le CA par produit et par vendeur pour 2024.\n\n### IMPORTRANGE — Importer des données d''une autre feuille\n```\n=IMPORTRANGE("URL_du_fichier_source"; "Feuille1!A1:D100")\n```\nPratique pour :\n- Consolider des données de plusieurs équipes\n- Créer un dashboard qui se met à jour depuis plusieurs sources\n- Partager des données sans donner accès au fichier source\n\n### ARRAYFORMULA — Formule sur toute une colonne\n```\n=ARRAYFORMULA(A2:A100 * B2:B100)\n```\nEquivalent de copier une formule sur 100 lignes, mais en une seule cellule.\n\n### GOOGLEFINANCE — Données financières en temps réel\n```\n=GOOGLEFINANCE("EURUSD"; "price")\n→ Taux EUR/USD en temps réel\n\n=GOOGLEFINANCE("EPA:BNP"; "price")\n→ Cours BNP Paribas (Paris)\n```\n\n## Collaboration en équipe : bonnes pratiques\n\n### Protéger certaines plages\n```\nClic droit → Protéger la plage\n→ Définir qui peut modifier\n→ Ajouter un message d''avertissement\n```\n\n### Validation des données\nEmpêchez les saisies incorrectes :\n```\nDonnées → Validation des données\n→ Liste déroulante (valeurs fixes ou plage)\n→ Message d''aide à la saisie\n→ Alerte en cas de saisie incorrecte\n```\n\n### Historique des versions\n```\nFichier → Historique des versions → Voir l''historique\n```\nVoyez qui a modifié quoi et quand — indispensable en équipe.\n\n## Automatiser avec Google Apps Script\n```javascript\nfunction envoyerRapportMensuel() {\n  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("Résumé");\n  const rapport = sheet.getRange("A1:D20").getValues();\n  // Envoyer par email...\n  MailApp.sendEmail("direction@monentreprise.ci", "Rapport mensuel", rapport.toString());\n}\n```\nConfigurez un déclencheur pour l''exécuter automatiquement le 1er de chaque mois.'),

  -- Module 7 : Macros VBA
  (v_mod7, v_course_id, 'Introduction aux Macros VBA : automatiser vos tâches répétitives', 'document', 1, false,
   E'# Macros VBA : Automatiser Excel\n\n## Qu''est-ce qu''une macro VBA ?\nUne macro est un programme informatique qui automatise des tâches répétitives dans Excel. VBA (Visual Basic for Applications) est le langage de programmation utilisé.\n\n**Tâches idéales à automatiser :**\n- Mise en forme automatique de rapports\n- Import et nettoyage de données chaque semaine\n- Génération automatique de factures\n- Envoi d''emails depuis Excel\n- Consolidation de plusieurs feuilles\n\n## Activer l''onglet Développeur\n```\nFichier → Options → Personnaliser le ruban\n→ Cocher "Développeur"\n→ OK\n```\n\n## Enregistrer une macro (sans coder)\n```\nDéveloppeur → Enregistrer une macro\n→ Nommer la macro (ex : "MiseEnForme_Rapport")\n→ Raccourci clavier (ex : Ctrl+Shift+R)\n→ OK\n[Effectuez vos actions Excel normalement]\n→ Développeur → Arrêter l''enregistrement\n```\n\nExcel a enregistré chaque clic en VBA. Appuyez sur votre raccourci pour rejouer.\n\n## Comprendre le code VBA généré\n```vba\nSub MiseEnForme_Rapport()\n    \' Sélectionner la plage A1:E1\n    Range("A1:E1").Select\n    \n    \' Mettre en gras\n    Selection.Font.Bold = True\n    \n    \' Couleur de fond bleue\n    Selection.Interior.Color = RGB(0, 59, 145)\n    \n    \' Couleur de texte blanche\n    Selection.Font.Color = RGB(255, 255, 255)\n    \nEnd Sub\n```\n\n## Concepts VBA essentiels\n\n### Variables\n```vba\nDim MonNombre As Integer\nDim MonTexte As String\nDim MaDate As Date\nMonNombre = 42\nMonTexte = "Abidjan"\n```\n\n### Conditions\n```vba\nIf Cells(i, 3).Value > 1000000 Then\n    Cells(i, 3).Interior.Color = RGB(0, 255, 0)  \' Vert\nElseIf Cells(i, 3).Value > 500000 Then\n    Cells(i, 3).Interior.Color = RGB(255, 165, 0) \' Orange\nElse\n    Cells(i, 3).Interior.Color = RGB(255, 0, 0)   \' Rouge\nEnd If\n```\n\n### Boucles\n```vba\nDim i As Integer\nFor i = 2 To 100\n    \' Calculer la marge pour chaque ligne\n    Cells(i, 5).Value = Cells(i, 3).Value - Cells(i, 4).Value\nNext i\n```\n\n## Macro pratique : Générer une facture automatiquement\n```vba\nSub GenererFacture()\n    Dim wsModele As Worksheet\n    Dim wsFacture As Worksheet\n    Dim NumFacture As Integer\n    \n    wsModele = Sheets("Modele_Facture")\n    NumFacture = Sheets("Paramètres").Range("B1").Value + 1\n    \n    \' Copier le modèle\n    wsModele.Copy After:=Sheets(Sheets.Count)\n    \n    \' Renommer la nouvelle feuille\n    ActiveSheet.Name = "Facture_" & NumFacture\n    \n    \' Numéroter la facture\n    Range("D3").Value = "FAC-" & Format(NumFacture, "0000")\n    Range("D4").Value = Date\n    \n    \' Incrémenter le numéro\n    Sheets("Paramètres").Range("B1").Value = NumFacture\n    \n    MsgBox "Facture N°" & NumFacture & " créée avec succès !", vbInformation\nEnd Sub\n```'),

  (v_mod7, v_course_id, 'Créer des formulaires et boîtes de dialogue VBA', 'document', 2, false,
   E'# Formulaires VBA (UserForms)\n\n## Qu''est-ce qu''un UserForm ?\nUn UserForm est une boîte de dialogue personnalisée que vous créez dans Excel. Vous pouvez y ajouter des champs de saisie, des listes déroulantes, des boutons — et lier tout ça à votre code VBA.\n\n**Exemples d''utilisation :**\n- Formulaire de saisie de commande\n- Interface de recherche client\n- Formulaire de rapport d''activité\n- Assistant de configuration\n\n## Créer un UserForm\n```\nDéveloppeur → Visual Basic → Insertion → UserForm\n```\n\nLa boîte à outils apparaît avec les contrôles disponibles.\n\n## Contrôles essentiels\n\n| Contrôle | Nom | Usage |\n|----------|-----|-------|\n| Label | Label1 | Texte descriptif |\n| TextBox | TextBox1 | Saisie libre |\n| ComboBox | ComboBox1 | Liste déroulante |\n| CheckBox | CheckBox1 | Case à cocher |\n| OptionButton | OptionButton1 | Bouton radio |\n| CommandButton | CommandButton1 | Bouton d''action |\n| ListBox | ListBox1 | Liste à sélection |\n\n## Exemple complet : Formulaire de saisie client\n\n```vba\n\' Initialisation du formulaire\nPrivate Sub UserForm_Initialize()\n    \' Remplir la liste des régions\n    ComboBox_Region.AddItem "Abidjan"\n    ComboBox_Region.AddItem "Bouaké"\n    ComboBox_Region.AddItem "San Pedro"\n    ComboBox_Region.AddItem "Yamoussoukro"\n    \n    \' Date du jour par défaut\n    TextBox_Date.Value = Format(Date, "DD/MM/YYYY")\nEnd Sub\n\n\' Bouton Enregistrer\nPrivate Sub CommandButton_Enregistrer_Click()\n    \' Validation\n    If TextBox_Nom.Value = "" Then\n        MsgBox "Veuillez saisir le nom du client.", vbExclamation\n        TextBox_Nom.SetFocus\n        Exit Sub\n    End If\n    \n    \' Trouver la première ligne vide\n    Dim DerniereLigne As Long\n    DerniereLigne = Sheets("Clients").Cells(Rows.Count, 1).End(xlUp).Row + 1\n    \n    \' Sauvegarder les données\n    With Sheets("Clients")\n        .Cells(DerniereLigne, 1).Value = TextBox_Nom.Value\n        .Cells(DerniereLigne, 2).Value = TextBox_Telephone.Value\n        .Cells(DerniereLigne, 3).Value = TextBox_Email.Value\n        .Cells(DerniereLigne, 4).Value = ComboBox_Region.Value\n        .Cells(DerniereLigne, 5).Value = Now()\n    End With\n    \n    MsgBox "Client enregistré avec succès !", vbInformation\n    \n    \' Réinitialiser le formulaire\n    TextBox_Nom.Value = ""\n    TextBox_Telephone.Value = ""\n    TextBox_Email.Value = ""\n    ComboBox_Region.Value = ""\n    TextBox_Nom.SetFocus\nEnd Sub\n\n\' Bouton Fermer\nPrivate Sub CommandButton_Fermer_Click()\n    Unload Me\nEnd Sub\n```\n\n## Appeler le formulaire depuis un bouton Excel\n```vba\nSub OuvrirFormulaireClient()\n    FormulaireSaisieClient.Show\nEnd Sub\n```\n\nInsertez un bouton dans votre feuille :\n```\nDéveloppeur → Insérer → Bouton de formulaire\n→ Assigner la macro OuvrirFormulaireClient\n```'),

  -- Module 8 : Tableaux de bord
  (v_mod8, v_course_id, 'Concevoir un tableau de bord Excel professionnel', 'document', 1, false,
   E'# Tableau de Bord Excel Professionnel\n\n## Les principes du bon design de dashboard\n\n### 1. Clarté avant beauté\nUn bon dashboard répond à une question en moins de 5 secondes. Si l''utilisateur doit chercher l''information, c''est un échec de conception.\n\n### 2. La règle des 3 couleurs max\n- **Couleur principale** : votre couleur d''entreprise (ex : bleu IBIG #0B3D91)\n- **Couleur d''accentuation** : orange ou jaune pour les indicateurs clés\n- **Couleur d''alerte** : rouge pour les problèmes, vert pour les succès\n\n### 3. L''hierarchy visuelle\nDu plus important au moins important :\n1. **KPIs en gros chiffres** (en haut, grands)\n2. **Graphiques principaux** (centre)\n3. **Tableaux détaillés** (bas, secondaires)\n\n## Structure d''un dashboard de performance commerciale\n\n### Zone 1 : KPIs (indicateurs clés)\n```\n┌─────────────┬─────────────┬─────────────┬─────────────┐\n│  CA du mois │ Nb commandes│ Ticket moyen│ Croissance  │\n│ 45,3M XOF   │     127     │  356k XOF   │   +23%      │\n│ ↑ +15%/M-1  │  ↑ +8%/M-1  │ ↑ +6%/M-1   │ vs objectif │\n└─────────────┴─────────────┴─────────────┴─────────────┘\n```\n\n### Zone 2 : Graphiques d''analyse\n- Graphique courbes : évolution mensuelle du CA sur 12 mois\n- Histogramme : CA par commercial (classé décroissant)\n- Camembert : répartition CA par région\n\n### Zone 3 : Tableau détaillé\nTop 10 clients du mois avec CA et variation vs mois précédent\n\n## Techniques de mise en forme avancée\n\n### Mise en forme conditionnelle avec icônes\n```\nSélectionner la colonne "Variation"\n→ Mise en forme conditionnelle\n→ Jeux d''icônes\n→ 3 flèches (vert/jaune/rouge)\n```\n\n### Graphique à puces (bullet chart)\nCompare la valeur réelle à l''objectif et aux seuils (bon/moyen/mauvais).\nConstruit avec des barres empilées et une ligne de série.\n\n### Jauges (Gauge chart)\nReprésentent un % d''avancement vers un objectif.\nConstruit avec un demi-anneau.\n\n## Rendre le dashboard dynamique\n\n### Listes déroulantes de contrôle\n```\nDéveloppeur → Insérer → Zone de liste déroulante\n→ Lier à une cellule nommée (ex : C_Annee)\n```\n\nVos formules utilisent cette cellule :\n```\n=SUMIFS(CA; Annee; C_Annee; Region; C_Region)\n```\n\nChangez l''année ou la région → tout le dashboard se met à jour instantanément.\n\n## Exporter et partager\n- **PDF** : Fichier → Exporter → PDF (préserve la mise en forme)\n- **Image** : Copier → Coller comme image (pour PowerPoint)\n- **SharePoint** : Publier directement depuis Excel 365\n- **Google Sheets** : Importer et partager avec lien');

END $$;
