-- ============================================================
-- ENRICHISSEMENT FORMATIONS 4-6
-- ============================================================

-- ============================================================
-- FORMATION 4 : Management et Leadership en Afrique
-- ============================================================
DO $$ DECLARE
  v_course_id uuid;
  v_mod5 uuid; v_mod6 uuid; v_mod7 uuid;
  v_max_pos int;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'management-leadership-afrique';
  SELECT COALESCE(MAX(position), 0) INTO v_max_pos FROM modules WHERE course_id = v_course_id;

  INSERT INTO modules (course_id, title, position) VALUES
    (v_course_id, 'Intelligence Émotionnelle et Leadership Africain', v_max_pos + 1),
    (v_course_id, 'Gestion du Changement et Transformation Organisationnelle', v_max_pos + 2),
    (v_course_id, 'Coaching, Mentorat et Développement des Talents', v_max_pos + 3);

  SELECT id INTO v_mod5 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos LIMIT 1;
  SELECT id INTO v_mod6 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 1 LIMIT 1;
  SELECT id INTO v_mod7 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 2 LIMIT 1;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES

  (v_mod5, v_course_id, 'L''intelligence émotionnelle : le facteur clé du leadership africain', 'document', 1, false,
   E'# Intelligence Émotionnelle et Leadership\n\n## Pourquoi l''IE est cruciale en contexte africain\nDans les organisations africaines, les relations humaines précèdent souvent les processus. Un manager techniquement brillant mais émotionnellement fermé échouera là où un manager moins qualifié mais empathique réussira.\n\nDaniel Goleman, auteur du concept d''intelligence émotionnelle, a montré que **l''IE explique 67% de la différence de performance entre leaders**.\n\n## Les 5 composantes de l''IE selon Goleman\n\n### 1. La conscience de soi\n**Définition :** Capacité à reconnaître ses propres émotions et leur impact\n\n**Comment la développer :**\n- Tenir un journal quotidien de vos émotions\n- Solliciter des feedbacks réguliers de votre équipe\n- Pratiquer la pleine conscience (méditation 10min/jour)\n- S''arrêter avant de réagir : "Qu''est-ce que je ressens là ?"\n\n**Indicateurs d''une faible conscience de soi :**\n- Vous êtes souvent surpris par les réactions de votre équipe\n- Vous pensez que vos collaborateurs sont irrationnels\n- Vous avez du mal à expliquer pourquoi vous avez pris une décision\n\n### 2. La maîtrise de soi\n**Définition :** Capacité à réguler ses émotions destructives\n\n**Techniques africaines de maîtrise de soi :**\n- La "palabre" : prendre le temps de la délibération collective avant de décider\n- Le respect des anciens : cultiver la patience et l''écoute\n- La "pause café" : ne jamais répondre à chaud à un email ou message conflictuel\n\n**Protocole en situation de tension :**\n1. Inspirez profondément (4 secondes)\n2. Demandez un délai : "Donnez-moi quelques minutes pour y réfléchir"\n3. Identifiez l''émotion ressentie\n4. Cherchez la réponse, pas la réaction\n\n### 3. La motivation intrinsèque\nLeaders africains influents : Cheikh Anta Diop, Wangari Maathai, Nelson Mandela — leur point commun : une mission qui dépasse leur intérêt personnel.\n\n**Questions pour clarifier votre motivation :**\n- Pourquoi ce travail a-t-il du sens pour vous ?\n- Comment contribue-t-il à votre communauté ?\n- Quel impact voudriez-vous avoir dans 10 ans ?\n\n### 4. L''empathie\n**En contexte africain :** l''empathie (ubuntu — "Je suis parce que nous sommes") est une valeur culturelle profonde. Exploitez-la dans votre management.\n\n**Pratiques d''empathie managériale :**\n- Commencer les réunions par "Comment allez-vous vraiment ?"\n- Visiter les collaborateurs sur le terrain\n- Se souvenir des événements importants (naissances, deuils, examens des enfants)\n\n### 5. Les compétences sociales\n- Communiquer avec clarté et chaleur simultanément\n- Gérer les conflits en cherchant les intérêts communs\n- Influencer sans autoritarisme\n- Construire des coalitions et des réseaux\n\n## Auto-évaluation IE : testez-vous\nNotez-vous de 1 à 5 sur chaque composante.\nScore < 3 → axe de développement prioritaire.'),

  (v_mod5, v_course_id, 'Gérer les personnalités difficiles et les conflits d''équipe', 'document', 2, false,
   E'# Gérer les Conflits et Personnalités Difficiles\n\n## Les types de personnalités difficiles en entreprise africaine\n\n### 1. Le "résistant passif"\nNe s''oppose pas ouvertement mais sabote discrètement les initiatives.\n**Signaux :** toujours absent lors des projets importants, oublie systématiquement les tâches clés, arrive en retard aux réunions.\n\n**Comment le gérer :**\n- Entretien individuel : "J''ai l''impression que tu rencontres des obstacles. Qu''est-ce qui te bloque ?"\n- Identifier la résistance réelle (peur, sentiment d''injustice, surcharge)\n- Donner une responsabilité visible : les résistants deviennent souvent des ambassadeurs quand on les implique\n\n### 2. Le "politique"\nManipule les relations pour servir ses intérêts, crée des clans.\n**Signaux :** parle souvent des autres en mal, change d''avis selon son interlocuteur, cherche à s''attirer les faveurs de la hiérarchie.\n\n**Comment le gérer :**\n- Clarifier les règles du jeu collectivement (en réunion, pas en privé)\n- Valoriser la transparence et la coopération en public\n- Ne pas rentrer dans ses jeux : restez factuel\n\n### 3. Le "surperformant toxique"\nExcellent techniquement mais détruit la cohésion d''équipe.\n**Signaux :** critique ouvertement les collègues, refuse de partager ses connaissances, se plaint constamment.\n\n**Le dilemme africain :** souvent ce profil est protégé parce qu''il "ramène des résultats". Attention : il coûte plus en dégâts humains qu''il ne rapporte.\n\n**Comment le gérer :**\n- Nommer clairement le comportement problématique (pas la personne)\n- Objectifs incluant des critères de comportement, pas que de résultats\n- Ultimatum si pas d''amélioration\n\n## Le processus de résolution de conflits\n\n### Étape 1 : Diagnostiquer le type de conflit\n- **Conflit de tâches :** désaccord sur comment faire le travail → peut être sain\n- **Conflit de ressources :** compétition pour budget, équipement, personnel\n- **Conflit relationnel :** tensions personnelles → toujours destructeur\n\n### Étape 2 : La méthode DESC\n**D**écrire les faits : "J''ai observé que lors de la réunion de lundi..."\n**E**xprimer le ressenti : "Cela m''a mis dans une position difficile parce que..."\n**S**pécifier ce qui est attendu : "À l''avenir, je souhaite que..."\n**C**onséquences positives : "Ce qui permettra de..."\n\n### Étape 3 : La médiation si nécessaire\nEn Afrique, faire appel à un "sage" ou un médiateur respecté des deux parties est culturellement accepté et très efficace.\n\n## Le feedback constructif : l''art de dire la vérité avec bienveillance\n\n**Structure SBI (Situation-Behaviour-Impact) :**\n```\n"Dans la situation [X],\nj''ai observé que tu as [comportement Y],\net l''impact que ça a eu est [Z]."\n```\n\nExemple :\n"Lors de la présentation client de mardi, tu as répondu à une question sans vérifier les chiffres, et le client a perdu confiance dans notre expertise."'),

  (v_mod5, v_course_id, 'Leadership situationnel : adapter son style selon le contexte', 'document', 3, false,
   E'# Leadership Situationnel\n\n## Le modèle de Hersey et Blanchard\nIl n''existe pas de "meilleur style de leadership" universel. L''efficacité d''un leader dépend de sa capacité à **adapter son style au niveau de maturité de son collaborateur** sur une tâche donnée.\n\n## Les 4 niveaux de maturité des collaborateurs\n\n| Niveau | Compétence | Motivation | Profil type |\n|--------|-----------|------------|-------------|\n| M1 | Faible | Élevée | Nouvel employé enthousiaste |\n| M2 | Faible/Modérée | Variable | Employé qui perd confiance |\n| M3 | Élevée | Variable | Expert qui manque de confiance |\n| M4 | Élevée | Élevée | Top performer autonome |\n\n## Les 4 styles de leadership correspondants\n\n### Style S1 : Directif (pour M1)\n**Fort en tâches, faible en relationnel**\nDites exactement QUOI faire, COMMENT, QUAND et OÙ.\n- Donnez des instructions détaillées\n- Supervisez de près\n- Corrigez immédiatement les erreurs\n- Montrez, démontrez, faites faire\n\n**En Afrique :** Le style directif est culturellement plus accepté qu''en Occident. Utilisez-le avec bienveillance, pas avec autorité.\n\n### Style S2 : Coach/Persuasif (pour M2)\n**Fort en tâches ET en relationnel**\nExpliquez le POURQUOI, écoutez les préoccupations, encouragez.\n- Donnez toujours les raisons de vos demandes\n- Demandez leur avis avant de décider\n- Reconnaissez les progrès même partiels\n- Soyez disponible pour les questions\n\n### Style S3 : Soutien/Participatif (pour M3)\n**Faible en tâches, fort en relationnel**\nPartagez la décision, valorisez leur expertise, construisez leur confiance.\n- "Comment ferais-tu toi-même ?"\n- Laissez-les proposer des solutions\n- Validez leurs compétences publiquement\n- Soyez un facilitateur, pas un expert\n\n### Style S4 : Délégation (pour M4)\n**Faible en tâches ET en relationnel**\nDéléguez la décision et la mise en œuvre. Vérifiez les résultats, pas les méthodes.\n- Donnez l''objectif, pas la méthode\n- Faites confiance jusqu''à preuve du contraire\n- Intervenez seulement si résultats insuffisants\n- Reconnaissez publiquement leurs succès\n\n## Application pratique : l''entretien de délégation\n\n**Structure de la délégation efficace :**\n1. **Contexte :** "Voilà pourquoi cette mission est importante..."\n2. **Mission :** "Je te confie la responsabilité de..."\n3. **Résultats attendus :** "Dans 3 semaines, j''attends..."\n4. **Ressources :** "Tu disposes de... et tu peux compter sur..."\n5. **Autonomie :** "Tu prends les décisions sur X et Y. Tu me consultes sur Z."\n6. **Points de contrôle :** "On fait un point le... et le..."\n7. **Reconnaissance :** "Je te fais confiance pour ça."'),

  -- Module 6 : Gestion du changement
  (v_mod6, v_course_id, 'Conduire le changement dans les organisations africaines', 'document', 1, false,
   E'# Conduite du Changement en Afrique\n\n## Pourquoi le changement échoue souvent\nSelon McKinsey, **70% des projets de changement organisationnel échouent**. La raison principale : on gère les processus et les structures, mais on néglige les personnes.\n\nEn contexte africain, s''ajoutent des facteurs spécifiques :\n- Méfiance vis-à-vis des changements imposés "d''en haut"\n- Poids des anciens et des structures hiérarchiques informelles\n- Rôle des réseaux familiaux dans l''organisation\n- Résistance enracinée dans des valeurs culturelles\n\n## La courbe du changement (courbe de Kübler-Ross adaptée)\n\n```\nMoral\n  ↑\n  │  ①Choc\n  │    ↘\n  │      ②Déni\n  │        ↘\n  │          ③Résistance ← Zone de danger\n  │          ↗\n  │        ④Exploration\n  │      ↗\n  │    ⑤Engagement\n  │  ↗\n  └──────────────────────→ Temps\n```\n\n**Votre rôle de leader du changement :**\n- Phases 1-3 : Communiquer, expliquer, écouter les résistances\n- Phase 4 : Former, accompagner, célébrer les petites victoires\n- Phase 5 : Ancrer le changement dans la culture\n\n## Le modèle ADKAR\n\nPour qu''un individu change avec succès, il doit parcourir 5 étapes :\n\n| Étape | Question clé | Action du leader |\n|-------|-------------|------------------|\n| **A**wareness (Sensibilisation) | "Pourquoi changer ?" | Communiquer le contexte |\n| **D**esire (Désir) | "Pourquoi MOI changer ?" | Identifier les motivations personnelles |\n| **K**nowledge (Connaissance) | "Comment changer ?" | Former, donner des outils |\n| **A**bility (Capacité) | "Puis-je changer ?" | Pratiquer, accompagner |\n| **R**einforcement (Ancrage) | "Cela vaut-il la peine de continuer ?" | Reconnaître, récompenser |\n\n## Stratégies de gestion des résistances\n\n### Identifier les parties prenantes\nMatrice d''analyse :\n```\n         Forte influence\n              ↑\nFaible    │  SURVEILLER  │  GÉRER EN\nengagement│              │  PRIORITÉ\n──────────┼──────────────┼──────────\nFort      │  INFORMER    │  S''APPUYER\nengagement│              │  SUR EUX\n              ↓\n         Faible influence\n```\n\n### Les ambassadeurs du changement\nIdentifiez des personnes influentes et respectées dans chaque équipe. Convainquez-les en premier — ils convaincront les autres.\n\nEn Afrique : les "anciens" (même s''ils ne sont pas les plus gradés) sont souvent les vrais influenceurs.\n\n## Communication du changement : le plan en 4 temps\n1. **Avant** : annonce officielle par la direction\n2. **Pendant** : points réguliers d''avancement, FAQ\n3. **Après chaque étape** : célébration des succès intermédiaires\n4. **À l''arrivée** : reconnaissance collective et individuelle'),

  (v_mod6, v_course_id, 'Piloter une transformation digitale dans votre organisation', 'document', 2, false,
   E'# Transformation Digitale des Organisations Africaines\n\n## Qu''est-ce que la transformation digitale (vraiment) ?\nLa transformation digitale, ce n''est PAS acheter de nouveaux logiciels. C''est **repenser fondamentalement comment votre organisation crée de la valeur** grâce au digital.\n\n**Exemples africains concrets :**\n- Une banque qui passe du guichet au mobile banking (Wave, Orange Money)\n- Un distributeur qui crée une plateforme B2B pour ses revendeurs\n- Une école qui digitalise ses cours et atteint les zones rurales\n- Une administration qui dématérialise ses procédures\n\n## Les 4 dimensions de la transformation digitale\n\n### 1. Expérience client\n- Du présentiel vers l''omnicanal (boutique + site + WhatsApp + app)\n- Personnalisation grâce aux données\n- Self-service 24h/24\n\n### 2. Opérations internes\n- Automatisation des tâches répétitives\n- Gestion des données en temps réel\n- Collaboration à distance\n\n### 3. Modèle commercial\n- Nouveaux flux de revenus (données, abonnements, marketplaces)\n- Partenariats avec des fintech, agritech, edtech\n\n### 4. Culture et compétences\n- Agilité et droit à l''erreur\n- Formation continue\n- Recrutement de profils numériques\n\n## Feuille de route pragmatique pour PME africaine\n\n### Phase 1 : Fondations (Mois 1-3)\n- Équiper tous les collaborateurs d''un email professionnel\n- Passer à Google Workspace ou Microsoft 365\n- Mettre en place un CRM simple (HubSpot Free, Odoo)\n- Digitaliser la facturation\n\n### Phase 2 : Optimisation (Mois 4-9)\n- Site web professionnel avec paiement en ligne\n- Présence réseaux sociaux structurée\n- Gestion de stock digitalisée\n- Formation des équipes\n\n### Phase 3 : Innovation (Mois 10-18)\n- Analytics et pilotage par les données\n- Automatisation marketing (email, WhatsApp)\n- Application mobile si pertinent\n- Exploration IA (chatbot, prédictions)\n\n## Les erreurs à éviter\n1. **Digitaliser sans former** : acheter des logiciels que personne n''utilise\n2. **Ignorer la connectivité** : vérifier que votre équipe a accès à internet stable\n3. **Tout faire en même temps** : priorités claires, déploiement progressif\n4. **Négliger la cybersécurité** : mots de passe solides, sauvegarde, antivirus\n5. **Oublier l''expérience client** : votre site web doit être rapide sur 3G'),

  (v_mod6, v_course_id, 'Piloter la performance organisationnelle avec les OKR', 'document', 3, false,
   E'# OKR : Objectives & Key Results\n\n## Qu''est-ce que les OKR ?\nLes OKR (Objectifs et Résultats Clés) sont une méthode de définition et de suivi des objectifs utilisée par Google, Intel, et de nombreuses entreprises africaines en croissance.\n\n**Différence avec les KPIs :**\n- **KPI :** mesure l''état de la santé de l''entreprise (indicateur de pilotage)\n- **OKR :** définit où vous voulez aller et comment vous saurez que vous y êtes arrivé\n\n## Structure d''un OKR\n\n### L''Objectif (O)\n- Ambitieux, inspirant, qualitatif\n- "Pourquoi" et "où"\n- 3-5 objectifs maximum par trimestre\n\n**Exemple :** "Devenir la référence du conseil RH en Afrique de l''Ouest"\n\n### Les Résultats Clés (KR)\n- Mesurables, quantifiables\n- 3-5 par objectif\n- "Comment je sais que j''ai atteint l''objectif"\n\n**Exemple :**\n- KR1 : Atteindre 50 clients entreprises (vs 22 actuellement)\n- KR2 : NPS (satisfaction client) de 70 ou plus\n- KR3 : Publier 2 études de cas mensuelles\n- KR4 : Générer 30% du CA via les référencements clients\n\n## Aligner les OKR de l''organisation à l''individu\n\n```\nOKR Entreprise\n    ↓ (dérivés)\nOKR Département\n    ↓ (dérivés)\nOKR Équipe\n    ↓ (dérivés)\nOKR Individuel\n```\n\nChaque collaborateur voit comment son travail contribue aux objectifs de l''entreprise.\n\n## Cycle OKR trimestriel\n\n**Semaine 1 du trimestre :**\n- Direction fixe les OKR entreprise\n- Managers déclinent avec leurs équipes\n\n**Chaque semaine :**\n- Check-in 15 minutes par OKR (avancement 0-100%)\n- Obstacles identifiés et adressés\n\n**Fin du trimestre :**\n- Score final (0,0 à 1,0)\n- Rétrospective : qu''avons-nous appris ?\n- Planification du trimestre suivant\n\n## Le scoring OKR\n\n| Score | Signification |\n|-------|---------------|\n| 0,7 - 1,0 | Excellent (objectif ambitieux atteint) |\n| 0,4 - 0,7 | Satisfaisant (progression significative) |\n| 0,0 - 0,4 | Insuffisant (réviser l''objectif ou les ressources) |\n\n> En OKR, un score de 0,7 est considéré comme réussi. Si vous atteignez 1,0 systématiquement, vos objectifs ne sont pas assez ambitieux.'),

  -- Module 7 : Coaching et mentorat
  (v_mod7, v_course_id, 'Devenir un manager-coach : libérer le potentiel de votre équipe', 'document', 1, false,
   E'# Le Manager-Coach\n\n## Pourquoi coacher plutôt que diriger ?\n\n**Le manager traditionnel :** "Fais comme ça."\n**Le manager-coach :** "Qu''est-ce que tu ferais dans cette situation ?"\n\nLa différence est fondamentale :\n- Le dirigeant crée de la dépendance\n- Le coach crée de l''autonomie et de la croissance\n\n**En Afrique**, le modèle paternel du chef ("le patron sait tout") est profondément ancré. Le manager-coach représente une évolution culturelle profonde — plus difficile à adopter, mais infiniment plus efficace sur le long terme.\n\n## Le modèle GROW\n\n**G**oal — Quel est l''objectif ?\n- "Qu''est-ce que tu veux accomplir ?"\n- "Comment saurais-tu que tu as réussi ?"\n- "Pour quand ?"\n\n**R**eality — Quelle est la situation actuelle ?\n- "Où en es-tu maintenant ?"\n- "Qu''as-tu déjà essayé ?"\n- "Quels sont les obstacles ?"\n\n**O**ptions — Quelles sont les options ?\n- "Que pourrais-tu faire ?"\n- "Qu''est-ce qui te semble le plus prometteur ?"\n- "Y a-t-il d''autres possibilités ?"\n\n**W**ill — Quel est ton engagement ?\n- "Que vas-tu faire concrètement ?"\n- "Quand le feras-tu ?"\n- "De quoi as-tu besoin de moi ?"\n\n## Les questions puissantes du coach\n\n### Questions d''exploration\n- "Qu''est-ce qui te préoccupe vraiment dans cette situation ?"\n- "Si tu n''avais aucune contrainte, que ferais-tu ?"\n- "Qu''est-ce que tu ferais conseiller à quelqu''un dans ta situation ?"\n\n### Questions de responsabilisation\n- "Sur une échelle de 1 à 10, quel est ton niveau d''engagement sur cette action ?"\n- "Qu''est-ce qui pourrait t''empêcher de tenir cet engagement ?"\n- "Comment peux-tu réduire ce risque ?"\n\n### Questions de réflexion\n- "Qu''as-tu appris de cette expérience ?"\n- "Si c''était à refaire, que ferais-tu différemment ?"\n- "Qu''est-ce que tu es fier d''avoir accompli ?"\n\n## Établir un programme de mentorat dans votre organisation\n\n### Phase 1 : Sélection des mentors\n- Cadres seniors reconnus pour leurs valeurs, pas que leur statut\n- Volontaires (le mentorat forcé ne fonctionne pas)\n- Formation de 1 journée aux techniques de coaching\n\n### Phase 2 : Appariement mentors/mentorés\n- Intérêts professionnels compatibles\n- Pas de lien hiérarchique direct\n- Différentes fonctions pour élargir la perspective\n\n### Phase 3 : Structure des sessions\n- 1h par mois minimum pendant 6 mois\n- Agenda co-construit (le mentoré prépare les sujets)\n- Pas de compte-rendu à la hiérarchie (confidentialité)\n\n### Phase 4 : Évaluation\n- Questionnaire satisfaction à 3 mois\n- Bilan de fin de programme\n- Célébration collective des parcours'),

  (v_mod7, v_course_id, 'Construire une culture de haute performance en Afrique', 'document', 2, false,
   E'# Culture de Haute Performance\n\n## Qu''est-ce qu''une culture organisationnelle ?\nLa culture d''une organisation, c''est "la façon dont on fait les choses ici". C''est l''ensemble des valeurs, croyances, comportements et pratiques qui définissent l''identité de votre organisation.\n\nPeter Drucker l''a dit : **"La culture mange la stratégie au petit-déjeuner."**\nVos belles stratégies ne serviront à rien si la culture ne les soutient pas.\n\n## Les marqueurs d''une culture haute performance en Afrique\n\n### 1. La clarté du "Pourquoi"\nChaque collaborateur sait pourquoi l''organisation existe et comment son travail y contribue.\n\n**Exercice Ikigaï organisationnel :**\n- Ce pour quoi vous êtes bons\n- Ce dont le monde a besoin\n- Ce pour quoi vous pouvez être rémunérés\n- Ce que vous aimez faire\nL''intersection = votre raison d''être (raison d''être)\n\n### 2. La sécurité psychologique\nL''équipe doit pouvoir prendre des risques, se tromper et partager ses idées sans crainte de représailles.\n\n**Comment créer la sécurité psychologique :**\n- Le manager partage ses propres erreurs et apprentissages\n- Les bonnes questions sont célébrées autant que les bonnes réponses\n- Les post-mortems sont blameless (on cherche le problème, pas le coupable)\n\n### 3. L''excellence par la réciprocité\nEn Afrique, la réciprocité est une valeur culturelle forte. Créez une culture où :\n- Les succès des uns sont célébrés par tous\n- Les difficultés des uns sont portées par tous\n- Chacun tient ses engagements envers ses collègues\n\n### 4. La reconnaissance fréquente\n**Ce qui est reconnu est reproduit.**\n\nFormes de reconnaissance adaptées à la culture africaine :\n- Célébration publique en réunion d''équipe\n- Lettre de félicitations partagée avec la famille (rare et très impactant)\n- Intégration aux projets valorisants\n- Responsabilités élargies\n- Prime ou avantage financier\n\n## Rituels de culture haute performance\n\n| Rituel | Fréquence | Objectif |\n|--------|-----------|----------|\n| Stand-up morning (15min) | Quotidien | Alignement, obstacles |\n| Célébration des victoires | Hebdomadaire | Motivation |\n| Rétrospective d''équipe | Mensuelle | Amélioration continue |\n| Formation / apprentissage | Mensuelle | Développement |\n| Revue des valeurs | Trimestrielle | Ancrage culturel |\n| Team building | Semestrielle | Cohésion humaine |\n\n## Mesurer votre culture : l''enquête d''engagement\n\n5 questions clés (note 1-10) :\n1. Je comprends et adhère à la mission de notre organisation\n2. Je me sens valorisé et reconnu pour mon travail\n3. Mon manager m''aide à progresser\n4. Je dispose des ressources nécessaires pour faire mon travail\n5. Je recommanderais cette organisation à un ami\n\n**Score moyen > 7/10 :** culture saine\n**Score moyen 5-7 :** travail à faire\n**Score moyen < 5 :** urgence culturelle');

END $$;


-- ============================================================
-- FORMATION 5 : Comptabilité OHADA pour PME
-- ============================================================
DO $$ DECLARE
  v_course_id uuid;
  v_mod5 uuid; v_mod6 uuid; v_mod7 uuid;
  v_max_pos int;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'comptabilite-ohada-pme-sans-etre-comptable';
  SELECT COALESCE(MAX(position), 0) INTO v_max_pos FROM modules WHERE course_id = v_course_id;

  INSERT INTO modules (course_id, title, position) VALUES
    (v_course_id, 'États Financiers OHADA : Lire et Analyser le Bilan et le Compte de Résultat', v_max_pos + 1),
    (v_course_id, 'Gestion de Trésorerie et Prévisions Financières', v_max_pos + 2),
    (v_course_id, 'Fiscalité des PME en Zone OHADA', v_max_pos + 3);

  SELECT id INTO v_mod5 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos LIMIT 1;
  SELECT id INTO v_mod6 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 1 LIMIT 1;
  SELECT id INTO v_mod7 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 2 LIMIT 1;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES

  (v_mod5, v_course_id, 'Lire et comprendre le Bilan comptable OHADA', 'document', 1, false,
   E'# Le Bilan Comptable OHADA\n\n## Qu''est-ce que le bilan ?\nLe bilan est une **photographie de la situation financière de l''entreprise** à un instant T (généralement le 31 décembre). Il répond à deux questions :\n- Que possède l''entreprise ? → **ACTIF**\n- Comment l''entreprise a-t-elle financé ses biens ? → **PASSIF**\n\n**Équation fondamentale : ACTIF = PASSIF**\n\n## Structure du bilan OHADA (Plan Comptable OHADA)\n\n### ACTIF (ce que l''entreprise possède)\n\n#### Actif Immobilisé (classe 2)\nBiens durables utilisés plusieurs années :\n- **Immobilisations incorporelles** (compte 20) : fonds de commerce, brevets, logiciels\n- **Immobilisations corporelles** (compte 21-24) : terrain, bâtiment, matériel, véhicules\n- **Immobilisations financières** (compte 25-27) : participations, prêts à long terme\n\n#### Actif Circulant (classe 3-4)\nBiens et créances à court terme :\n- **Stocks** (compte 3) : marchandises, matières premières, produits finis\n- **Créances clients** (compte 411) : ce que vous doivent vos clients\n- **Autres créances** (compte 40-48) : TVA déductible, avances...\n- **Disponibilités** (compte 5) : caisse, banque, mobile money\n\n### PASSIF (comment c''est financé)\n\n#### Capitaux Propres (classe 1 partielle)\n- **Capital social** (compte 101) : apport des associés\n- **Réserves** (compte 11) : bénéfices non distribués\n- **Résultat de l''exercice** (compte 13) : bénéfice ou perte de l''année\n\n#### Dettes à Long Terme\n- **Emprunts bancaires** (compte 16) : crédit à plus d''un an\n\n#### Dettes à Court Terme (Passif Circulant)\n- **Dettes fournisseurs** (compte 401) : ce que vous devez à vos fournisseurs\n- **Dettes fiscales** (compte 44) : TVA collectée, impôts à payer\n- **Dettes sociales** (compte 42-43) : salaires, CNPS\n\n## Lire un bilan : exercice pratique\n\n**Bilan simplifié d''une PME abidjanaise (en milliers XOF)**\n\n| ACTIF | Montant | PASSIF | Montant |\n|-------|---------|--------|----------|\n| Immobilisations | 8 500 | Capital social | 5 000 |\n| Stocks | 3 200 | Réserves | 2 800 |\n| Créances clients | 4 800 | Résultat | 1 200 |\n| Disponibilités | 1 500 | Emprunts LT | 4 000 |\n| | | Dettes CT | 5 000 |\n| **Total** | **18 000** | **Total** | **18 000** |\n\n**Analyse rapide :**\n- L''entreprise est solvable (capitaux propres positifs)\n- Dettes CT (5 000) > Disponibilités (1 500) → vigilance trésorerie\n- Stocks importants → s''assurer de leur rotation rapide'),

  (v_mod5, v_course_id, 'Analyser le Compte de Résultat et les Soldes Intermédiaires de Gestion', 'document', 2, false,
   E'# Compte de Résultat et SIG OHADA\n\n## Le Compte de Résultat (CR)\nAlors que le bilan est une photo, le compte de résultat est un **film** : il retrace toutes les opérations de l''exercice (1 an) et montre si l''entreprise a été rentable.\n\n**Résultat = Produits - Charges**\n\n## Structure du Compte de Résultat OHADA\n\n### Produits d''exploitation\n- Chiffre d''affaires (ventes de marchandises + prestations)\n- Production stockée\n- Subventions d''exploitation\n\n### Charges d''exploitation\n- Achats de marchandises/matières\n- Variation de stocks\n- Transports\n- Services extérieurs (loyers, honoraires, publicité...)\n- Impôts et taxes (hors IS)\n- Charges de personnel (salaires + charges sociales)\n- Dotations aux amortissements\n\n### Résultat d''exploitation (REX)\n```\nREX = Produits exploitation - Charges exploitation\n```\nIndicateur de la performance opérationnelle pure.\n\n## Les Soldes Intermédiaires de Gestion (SIG) OHADA\n\nLes SIG décomposent le résultat pour comprendre d''où vient la performance :\n\n### 1. Marge commerciale (entreprises commerciales)\n```\nMarge commerciale = Ventes marchandises - Coût d''achat marchandises vendues\nTaux de marge = Marge / Ventes × 100\n```\n\n### 2. Valeur Ajoutée (VA)\n```\nVA = Marge brute - Services extérieurs - Autres charges\n```\nMesure la richesse créée par l''entreprise elle-même.\n\n### 3. Excédent Brut d''Exploitation (EBE)\n```\nEBE = VA - Charges de personnel - Impôts et taxes\n```\nCash-flow opérationnel avant investissements. **Indicateur le plus important pour les banques.**\n\n### 4. Résultat d''exploitation (REX)\n```\nREX = EBE - Dotations amortissements + Reprises\n```\n\n### 5. Résultat Net\n```\nRésultat net = REX ± Résultat financier ± Résultat exceptionnel - Impôt sur bénéfices\n```\n\n## Ratios d''analyse à calculer\n\n| Ratio | Formule | Interprétation |\n|-------|---------|----------------|\n| Taux de marge brute | Marge brute/CA | Rentabilité commerciale |\n| Taux d''EBE | EBE/CA | Rentabilité opérationnelle |\n| Taux de résultat net | Résultat net/CA | Rentabilité finale |\n| Charge personnel/VA | Salaires/VA | Part du personnel dans la valeur créée |\n\n**Référence OHADA secteur commerce :**\n- Taux de marge brute : 20-40%\n- Taux d''EBE : 5-15%\n- Taux résultat net : 2-8%'),

  (v_mod5, v_course_id, 'Tableau de flux de trésorerie : comprendre les mouvements de cash', 'document', 3, false,
   E'# Tableau de Flux de Trésorerie\n\n## Pourquoi le cash est roi\n**Une entreprise peut être rentable et mourir de manque de cash.** C''est l''un des paradoxes les plus douloureux de la gestion d''entreprise.\n\nExemple :\n- PME sénégalaise réalise 50M XOF de CA\n- Résultat net comptable : 5M XOF (rentable)\n- Mais elle a accordé 90 jours de crédit à ses clients\n- Pendant ce temps, elle doit payer ses fournisseurs à 30 jours\n- **Résultat : elle est en cessation de paiement malgré son bénéfice**\n\n## Le Tableau des Flux de Trésorerie (TFT) OHADA\n\nLe TFT décompose les mouvements de trésorerie en 3 catégories :\n\n### 1. Flux d''exploitation (activité courante)\n```\nRésultat net\n+ Amortissements (charge non décaissée)\n+/- Variation du BFR (stocks, créances, dettes)\n= Flux d''exploitation\n```\n\n**Si ce flux est négatif :** votre activité consomme du cash → urgent à résoudre.\n\n### 2. Flux d''investissement\n```\n- Acquisitions d''immobilisations (machines, véhicules...)\n+ Cessions d''immobilisations (ventes d''actifs)\n= Flux d''investissement\n```\n\nNégatif = vous investissez pour croître (normal)\nPositif = vous désinvestissez (attention signal d''alerte)\n\n### 3. Flux de financement\n```\n+ Nouveaux emprunts\n- Remboursements d''emprunts\n+ Apports en capital\n- Dividendes distribués\n= Flux de financement\n```\n\n## Construire un budget de trésorerie prévisionnel\n\n**Tableau mensuel sur 12 mois :**\n\n```\n                Jan    Fév    Mars   ...\nSolde début     X      X      X\n\nENCAISSEMENTS\n+ Recettes clients X\n+ Autres entrées   X\n= Total entrées    X\n\nDÉCAISSEMENTS\n- Fournisseurs     X\n- Salaires         X\n- Loyers           X\n- Remb. emprunts   X\n- Impôts           X\n= Total sorties    X\n\nFlux net du mois   X      X      X\nSolde fin          X      X      X\n```\n\n**Objectif :** Anticiper les mois déficitaires pour prendre des mesures préventives (demander un découvert bancaire, retarder un investissement, accélérer les encaissements).'),

  -- Module 6 : Trésorerie
  (v_mod6, v_course_id, 'Optimiser le Besoin en Fonds de Roulement (BFR)', 'document', 1, false,
   E'# Optimiser le BFR de votre PME\n\n## Comprendre le BFR\nLe Besoin en Fonds de Roulement est **l''argent dont vous avez besoin pour financer le décalage entre vos dépenses (fournisseurs à payer) et vos recettes (clients qui paient).**\n\n```\nBFR = Stocks + Créances clients - Dettes fournisseurs\n```\n\n**BFR positif (cas habituel) :** vous avez besoin de trésorerie pour faire tourner votre activité.\n**BFR négatif (cas des supermarchés) :** vous encaissez avant de payer → enviable !\n\n## Exemple concret\n\nPME de distribution en Côte d''Ivoire :\n- Stocks : 8 000 000 XOF (30 jours de stock)\n- Créances clients : 12 000 000 XOF (45 jours clients)\n- Dettes fournisseurs : 6 000 000 XOF (15 jours fournisseurs)\n\n```\nBFR = 8 000 000 + 12 000 000 - 6 000 000 = 14 000 000 XOF\n```\n\nCette entreprise a besoin de 14M XOF de trésorerie permanente juste pour fonctionner.\n\n## Les 3 leviers pour réduire le BFR\n\n### Levier 1 : Réduire les stocks\n**Objectif :** avoir le moins de stock possible sans ruptures\n\n- Calculez la rotation de chaque produit\n- Liquidez les stocks dormants (même à perte)\n- Négociez des livraisons plus fréquentes avec vos fournisseurs\n- Adoptez le réapprovisionnement automatique (point de commande)\n\n**Ratio :** Durée de stockage = (Stock moyen / Achats) × 360\nObjectif : < 30 jours pour le commerce général\n\n### Levier 2 : Accélérer les encaissements clients\n**Objectif :** être payé plus vite\n\n- Facturez immédiatement à la livraison\n- Proposez un escompte pour paiement rapide (ex : -2% si paiement à 10 jours)\n- Relancez dès le premier jour de retard (pas après 30 jours)\n- Exigez des acomptes sur les grosses commandes\n- Mobile Money / virement = encaissement immédiat (pas de chèque)\n\n**Ratio :** Délai clients = (Créances / CA TTC) × 360\nObjectif : < 30 jours\n\n### Levier 3 : Négocier de meilleures conditions fournisseurs\n**Objectif :** payer le plus tard possible\n\n- Négociez 60-90 jours avec vos principaux fournisseurs\n- Utilisez votre volume d''achat comme argument\n- Devenez un client prioritaire (payer toujours à temps = pouvoir de négociation)\n\n**Ratio :** Délai fournisseurs = (Dettes fournisseurs / Achats TTC) × 360\nObjectif : > 45 jours\n\n## Tableau de suivi mensuel du BFR\n\n```\n           Jan    Fév    Mars\nStocks      X      X      X\n+ Clients   X      X      X\n- Frs       X      X      X\n= BFR       X      X      X\nVariation  ↑/↓   ↑/↓   ↑/↓\n```'),

  (v_mod6, v_course_id, 'Financement court terme et gestion de la trésorerie quotidienne', 'document', 2, false,
   E'# Financement Court Terme et Trésorerie Quotidienne\n\n## Les instruments de financement court terme disponibles en Afrique\n\n### 1. Le découvert bancaire\n**Principe :** La banque vous autorise à être débiteur temporairement.\n**Coût :** Taux débiteur de 12 à 18%/an + commission de dépassement\n**Usage :** Décalages de trésorerie ponctuels (quelques jours à quelques semaines)\n\n**Attention :** Le découvert est un signal d''alerte. S''il devient permanent, vous avez un problème structurel de BFR.\n\n### 2. L''escompte commercial (avance sur créances)\n**Principe :** Vous remettez vos effets de commerce (traites clients) à la banque qui vous paie immédiatement, moins une commission.\n**Coût :** 4-8%/an\n**Usage :** Vous avez une créance à 90 jours mais besoin de cash maintenant\n\n### 3. Le crédit de campagne\n**Pour qui :** Activités saisonnières (agroalimentaire, BTP, tourisme)\n**Principe :** Crédit accordé pour financer la période de production, remboursé à la vente\n**Durée :** 3 à 12 mois\n\n### 4. Le factor (affacturage)\n**Principe :** Une société spécialisée achète vos créances clients et vous paie immédiatement (80-90% du montant), puis se charge du recouvrement.\n**Coût :** 1-3% du montant des créances\n**Avantage :** Vous transférez le risque d''impayé\n**Disponible en CI :** certaines banques et société d''affacturage\n\n### 5. Mobile Money professionnel\n**Révolution africaine :** Orange Money Business, MTN Business, Wave Business permettent :\n- Réception immédiate des paiements\n- Virements instantanés à vos fournisseurs\n- Extrait de compte pour votre comptable\n- Limite plus haute que les comptes particuliers\n\n## Gérer sa trésorerie au quotidien\n\n### L''état de rapprochement bancaire\nChaque mois, comparez votre relevé bancaire avec votre compte 512 en comptabilité.\n\n**Écarts courants :**\n- Chèques émis non encore débités\n- Virements en cours\n- Agios non comptabilisés\n- Erreurs de la banque (rare mais possible)\n\n### La règle de l''encaisse de sécurité\nConservez toujours l''équivalent de **15 jours de charges fixes** en trésorerie disponible.\n\n```\nEncaisse sécurité = (Charges fixes mensuelles × 15) / 30\nEx : Charges fixes = 6 000 000 XOF/mois\nEncaisse sécurité = 6 000 000 × 15/30 = 3 000 000 XOF\n```\n\n### Placer les excédents de trésorerie\nSi vous avez des excédents temporaires (3-6 mois) :\n- **Compte à terme (CAT)** : 3-5%/an, capital garanti\n- **SICAV monétaires** : 3-4%/an, rachetables à tout moment\n- **Bons du Trésor** : émis par l''État, 5-7%/an selon durée'),

  -- Module 7 : Fiscalité
  (v_mod7, v_course_id, 'TVA et obligations fiscales mensuelles des PME', 'document', 1, false,
   E'# TVA et Obligations Fiscales Mensuelles\n\n## La TVA en zone OHADA/UEMOA\n\n### Principe général\nLa TVA (Taxe sur la Valeur Ajoutée) est un impôt indirect collecté par les entreprises pour le compte de l''État.\n\n**Vous collectez la TVA** sur vos ventes (TVA collectée)\n**Vous déduisez la TVA** sur vos achats professionnels (TVA déductible)\n**Vous reversez** à l''État la différence\n\n```\nTVA à payer = TVA collectée - TVA déductible\n```\n\n### Taux de TVA par pays\n| Pays | Taux normal | Taux réduit |\n|------|------------|-------------|\n| Côte d''Ivoire | 18% | 9% (produits de première nécessité) |\n| Sénégal | 18% | - |\n| Cameroun | 19,25% | - |\n| Mali | 18% | - |\n| Bénin | 18% | - |\n| Togo | 18% | - |\n\n### Les opérations exonérées de TVA\n- Exportations\n- Services médicaux et hospitaliers\n- Enseignement scolaire et universitaire\n- Certains produits alimentaires de base\n\n## Les régimes d''imposition\n\n### Régime du réel normal\n**Pour :** CA > seuil (varie selon les pays, souvent > 50M XOF)\n- Déclaration de TVA mensuelle\n- Bilan comptable complet obligatoire\n- Déclaration IS ou BIC annuelle\n\n### Régime du réel simplifié\n**Pour :** CA entre 10M et 50M XOF (variable selon pays)\n- Déclaration TVA trimestrielle\n- Comptabilité allégée\n\n### Régime de l''auto-entrepreneur (certains pays)\n**Pour :** petites activités\n- Pas de TVA\n- Impôt forfaitaire sur CA\n\n## Le calendrier fiscal mensuel (régime réel normal)\n\n| Obligation | Échéance | Pénalité si retard |\n|-----------|----------|--------------------|\n| Déclaration TVA | 15-20 du mois suivant | 10-25% + intérêts |\n| Retenue à la source (IRPP salaires) | 15 du mois suivant | 10% |\n| Acomptes IS | Variable selon pays | 10% |\n\n## Exemple de déclaration TVA (Côte d''Ivoire)\n\n```\nCA du mois de janvier : 10 000 000 XOF HT\nTVA collectée (18%) : 1 800 000 XOF\n\nAchats HT : 6 000 000 XOF\nTVA déductible (18%) : 1 080 000 XOF\n\nTVA nette à payer = 1 800 000 - 1 080 000 = 720 000 XOF\n```\n\nCette somme doit être versée à la DGI avant le 20 février.\n\n## Éviter les problèmes fiscaux\n1. **Gardez tous les justificatifs** pendant 10 ans (obligation légale)\n2. **Facturez correctement** : numéro NIF, mentions obligatoires\n3. **Collaborez avec votre DGI** : en cas de difficulté, demandez un étalement\n4. **Faites-vous accompagner** par un expert-comptable ou conseil fiscal'),

  (v_mod7, v_course_id, 'Impôt sur les bénéfices et optimisation fiscale légale', 'document', 2, false,
   E'# Impôt sur les Bénéfices et Optimisation Fiscale\n\n## L''Impôt sur les Sociétés (IS) / Impôt sur les BIC\n\n### Taux d''IS en zone OHADA\n| Pays | Taux IS | Taux minimum forfaitaire |\n|------|---------|-------------------------|\n| Côte d''Ivoire | 25% | 0,5% du CA |\n| Sénégal | 30% | 0,5% du CA |\n| Cameroun | 33% | 2,2% du CA |\n| Mali | 30% | 0,75% du CA |\n| Bénin | 30% | 1% du CA |\n\n**Le minimum forfaitaire** est dû même en cas de perte ! Planifiez-le dans votre trésorerie.\n\n## Calculer l''IS\n\n```\nRésultat comptable\n+ Réintégrations fiscales (charges non déductibles)\n- Déductions fiscales (amortissements accélérés, etc.)\n= Résultat fiscal (base imposable)\n× Taux IS\n= IS brut\n- Acomptes déjà versés\n= IS restant à payer\n```\n\n### Charges non déductibles (réintégrations)\nCertaines charges comptabilisées ne sont PAS déductibles fiscalement :\n- **Pénalités et amendes** (contre la loi)\n- **Cadeaux clients** au-delà d''un seuil\n- **Charges sans justificatifs** (la DGI peut les réintégrer)\n- **Rémunérations excessives** du dirigeant\n- **Amortissements** au-delà des taux légaux\n\n## Optimisation fiscale LÉGALE\n\n### 1. Maximiser les amortissements\nCertains pays autorisent l''amortissement accéléré sur les équipements. Investissez en fin d''exercice pour réduire le résultat de l''année.\n\n### 2. Les provisions\nConstituez des provisions pour risques légitimes :\n- Provision pour créances douteuses (clients en retard >6 mois)\n- Provision pour dépréciation des stocks (produits obsolètes)\n- Provision pour litiges en cours\n\nCes provisions sont déductibles de l''IS.\n\n### 3. Les charges de personnel\nLes salaires, charges sociales, formations sont entièrement déductibles. Investissez dans votre équipe plutôt que de payer l''IS.\n\n### 4. Les charges financières\nLes intérêts d''emprunt professionnels sont déductibles. Un crédit bancaire est fiscalement plus intéressant qu''un apport en capital.\n\n### 5. Les zones franches et exonérations\nDe nombreux pays africains offrent des exonérations IS temporaires :\n- **CI :** Zone Franche Industrielle d''Abidjan (5-8 ans d''exonération)\n- **Sénégal :** Statut d''entreprise franche d''exportation\n- **Cameroun :** Zones économiques spéciales\n\n**⚠️ Important :** L''optimisation fiscale est légale et recommandée. L''évasion fiscale (dissimulation de revenus) est un délit. Faites-vous accompagner par un expert-comptable agréé ONECCA.');

END $$;


-- ============================================================
-- FORMATION 6 : Communication Professionnelle et Prise de Parole
-- ============================================================
DO $$ DECLARE
  v_course_id uuid;
  v_mod5 uuid; v_mod6 uuid; v_mod7 uuid;
  v_max_pos int;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'communication-professionnelle-prise-de-parole';
  SELECT COALESCE(MAX(position), 0) INTO v_max_pos FROM modules WHERE course_id = v_course_id;

  INSERT INTO modules (course_id, title, position) VALUES
    (v_course_id, 'Négociation et Influence Interculturelle en Afrique', v_max_pos + 1),
    (v_course_id, 'Communication de Crise et Gestion des Situations Difficiles', v_max_pos + 2),
    (v_course_id, 'Communication Digitale et Personal Branding Professionnel', v_max_pos + 3);

  SELECT id INTO v_mod5 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos LIMIT 1;
  SELECT id INTO v_mod6 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 1 LIMIT 1;
  SELECT id INTO v_mod7 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 2 LIMIT 1;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES

  (v_mod5, v_course_id, 'Les fondamentaux de la négociation en contexte africain', 'document', 1, false,
   E'# Négociation en Contexte Africain\n\n## La négociation africaine : spécificités culturelles\n\nNégocier en Afrique n''est pas négocier à l''occidentale. Ignorer les codes culturels vous fera perdre des négociations que vous auriez dû gagner.\n\n### Les caractéristiques de la négociation africaine\n\n**1. La relation précède la transaction**\nEn Occident : on négocie, puis on crée une relation si l''accord est signé.\nEn Afrique : on crée la relation, puis on négocie.\n\nImplication : Avant toute négociation importante, investissez dans :\n- Des repas, rencontres informelles\n- La connaissance de l''histoire et de la famille de l''autre partie\n- Des échanges de cadeaux symboliques\n\n**2. Le temps est circulaire, pas linéaire**\nImpatienter une contrepartie africaine en cherchant à "aller vite" est contre-productif. La décision mûrit progressivement.\n\n**3. L''harmonie du groupe prévaut sur la décision individuelle**\nSouvent, votre interlocuteur ne peut décider seul. Il doit consulter ses supérieurs, sa communauté, ses associés. Respectez ce processus.\n\n**4. Le prix affiché est une invitation à négocier**\nContrairement aux prix fixes occidentaux, le prix initial est rarement le prix final. C''est une convention culturelle respectée des deux côtés.\n\n## La méthode BATNA (Meilleure Alternative à un Accord Négocié)\n\n**Avant toute négociation, définissez :**\n1. Votre BATNA : que se passe-t-il si cette négociation échoue ?\n2. Le BATNA de l''autre partie : quelle est leur alternative ?\n\nCelui qui a la meilleure alternative a le plus de pouvoir de négociation.\n\n## Le processus de négociation en 6 étapes\n\n### Étape 1 : Préparation\n- Définir votre objectif idéal (position haute)\n- Définir votre point de rupture (minimum acceptable)\n- Préparer vos arguments, concessions possibles\n- Rechercher des informations sur l''autre partie\n\n### Étape 2 : Ouverture\n- Créer une atmosphère positive\n- Échanges personnels (famille, actualités, sport)\n- Ne pas aborder immédiatement le sujet de la négociation\n\n### Étape 3 : Exploration\n- Écouter plus que parler\n- Questions ouvertes : "Quels sont vos objectifs ?", "Quelles sont vos contraintes ?"\n- Reformuler pour montrer que vous avez compris\n\n### Étape 4 : Proposition\n- Présenter votre offre comme un bénéfice pour l''autre partie\n- Éviter les extrêmes (trop haut = irrespectueux, trop bas = perte de valeur)\n\n### Étape 5 : Négociation\n- Chaque concession doit obtenir une concession en retour\n- Concédez lentement et de moins en moins\n- Ne concédez jamais sans contrepartie\n\n### Étape 6 : Accord et consolidation\n- Résumer les points d''accord à voix haute\n- Mettre par écrit même les accords informels\n- Célébrer l''accord (repas, cadeau symbolique)'),

  (v_mod5, v_course_id, 'Techniques d''influence et de persuasion éthique', 'document', 2, false,
   E'# Influence et Persuasion Éthique\n\n## Les 6 principes d''influence de Cialdini en contexte africain\n\n### 1. La Réciprocité\n**Principe :** Nous nous sentons obligés de rendre ce qu''on nous a donné.\n**En Afrique :** La réciprocité (djembe, ubuntu, teranga) est une valeur fondamentale.\n\n**Application professionnelle :**\n- Partagez des informations utiles avant de demander quelque chose\n- Faites des introductions précieuses dans votre réseau\n- Rendez service sans attente explicite de retour\n\n### 2. L''Autorité\n**Principe :** Nous faisons confiance aux experts et aux figures d''autorité.\n\n**Construire votre autorité :**\n- Titres et certifications (diplômes, formations)\n- Références et témoignages de clients reconnus\n- Publications (articles, livres, prises de position)\n- Présence médiatique\n\n### 3. La Preuve sociale\n**Principe :** Nous regardons ce que font les autres pour décider.\n**En Afrique :** "Si Monsieur Koné fait confiance à cette entreprise, elle est sérieuse."\n\n**Application :**\n- Témoignages vidéo de clients satisfaits\n- Logos d''entreprises clientes\n- Chiffres : "500 entreprises nous font confiance"\n- Noms de références que votre prospect connaît\n\n### 4. La Rareté\n**Principe :** Ce qui est rare a plus de valeur.\n\n**Application éthique (pas de fausses urgences) :**\n- Groupe limité (ex : formation avec max 20 participants)\n- Offre valable jusqu''à une date réelle\n- Stock limité véritable\n\n### 5. La Sympathie\n**Principe :** Nous préférons dire oui à ceux qu''on aime bien.\n**En Afrique :** Les liens personnels, familiaux, régionaux et ethniques créent une sympathie naturelle. Explorez les points communs.\n\n**Construire la sympathie :**\n- Points communs : ville d''origine, école, religion, sport\n- Compliments sincères et spécifiques\n- Intérêt réel pour la vie de l''autre\n- Sourire et langage corporel ouvert\n\n### 6. L''Engagement et Cohérence\n**Principe :** Nous aimons rester cohérents avec nos positions passées.\n\n**Technique du pied dans la porte :**\nCommencez par de petites demandes auxquelles la personne dira oui facilement. Elle sera ensuite plus encline à accepter une demande plus grande.\n\n"Êtes-vous d''accord que la formation de vos équipes est un investissement important ?" → "Oui"\n"Alors laissez-moi vous présenter comment notre programme peut vous aider concrètement..."\n\n## Éthique de l''influence\n**La ligne rouge :** L''influence devient manipulation quand elle exploite les faiblesses, crée de la peur ou de la culpabilité, ou pousse à des décisions contraires aux intérêts de l''autre partie.\n\nUne réputation bâtie sur la manipulation s''effondre toujours — en Afrique plus qu''ailleurs, où la communauté partage vite les mauvaises expériences.'),

  (v_mod5, v_course_id, 'Mener des négociations commerciales gagnant-gagnant', 'document', 3, false,
   E'# Négociations Commerciales Gagnant-Gagnant\n\n## Pourquoi viser le gagnant-gagnant ?\n\nUne négociation où vous "écrasez" votre partenaire peut vous coûter cher :\n- Ressentiment et désir de revanche\n- Perte d''un client/fournisseur à long terme\n- Mauvaise réputation dans la communauté\n- Accord mal appliqué par la partie "perdante"\n\n**En Afrique :** Le business est avant tout relationnel et communautaire. Votre réputation de négociateur équitable est un actif commercial majeur.\n\n## Distinguer positions et intérêts\n\nL''erreur classique : négocier sur les **positions** (ce que chaque partie déclare vouloir) plutôt que sur les **intérêts** (pourquoi chaque partie veut ce qu''elle veut).\n\n**Exemple classique :**\nDeux sœurs se disputent la dernière orange.\nPosition sœur A : "Je veux l''orange"\nPosition sœur B : "Je veux l''orange"\n\nSi on explore les intérêts :\nIntérêt sœur A : elle veut le jus pour son cocktail\nIntérêt sœur B : elle veut l''écorce pour son gâteau\n\nSolution : sœur A prend le jus, sœur B prend l''écorce. Les deux sont 100% satisfaites.\n\n**Application commerciale :**\nVotre client veut un prix plus bas. Son intérêt réel : réduire son coût global. Vous pouvez peut-être maintenir votre prix en ajoutant de la valeur (formation, garantie étendue, livraison incluse).\n\n## La matrice de concessions\n\nPréparez à l''avance vos concessions possibles et leur valeur :\n\n| Concession | Coût pour moi | Valeur pour l''autre | Priorité |\n|------------|--------------|---------------------|----------|\n| Délai 60 jours | Faible | Élevée | À utiliser |\n| Remise 5% | Moyen | Moyen | Si nécessaire |\n| Formation incluse | Faible | Élevée | À utiliser |\n| Remise 15% | Élevé | Moyen | Dernier recours |\n\n**Règle :** Commencez par les concessions à faible coût pour vous mais haute valeur pour l''autre.\n\n## Technique de la négociation par paquets\n\nNe négociez jamais un point à la fois. Mettez tous les enjeux sur la table simultanément :\n- Prix\n- Quantité\n- Délais de livraison\n- Modalités de paiement\n- Services inclus\n- Durée du contrat\n\nCela permet de trouver des combinaisons créatives où chacun cède sur ce qui lui coûte peu mais gagne sur ce qui l''intéresse le plus.\n\n## Clore la négociation\n\n**Techniques de closing adaptées à l''Afrique :**\n\n1. **Le résumé des bénéfices :** "Donc, en récapitulant ce que vous obtenez..."\n2. **La question alternative :** "Préférez-vous qu''on commence en janvier ou en février ?"\n3. **L''appel à la relation :** "Je pense que ce partenariat va être très bénéfique pour nos deux organisations et nos équipes."\n4. **L''urgence réelle :** "Nous avons un autre client intéressé par ce créneau, mais vous êtes notre partenaire prioritaire."'),

  -- Module 6 : Communication de crise
  (v_mod6, v_course_id, 'Gérer une crise de communication en entreprise africaine', 'document', 1, false,
   E'# Communication de Crise\n\n## Qu''est-ce qu''une crise de communication ?\nUne crise est un événement inattendu qui menace la réputation, les opérations ou la pérennité de votre organisation et qui exige une réponse immédiate.\n\n**Types de crises fréquents en Afrique :**\n- Incident de sécurité (accident du travail, incendie)\n- Scandale financier (détournement, fraude)\n- Problème qualité/sécurité produit\n- Conflit social (grève, protestation d''employés)\n- Attaque sur les réseaux sociaux\n- Crise politique ou sécuritaire impactant votre secteur\n\n## La règle des premières 24 heures\n\nLes premières 24 heures déterminent souvent l''issue d''une crise. Chaque heure de silence est interprétée comme un aveu ou une incompétence.\n\n**Plan d''action immédiat :**\n\n**H+1 :** Activer la cellule de crise\n**H+2 :** Évaluer les faits disponibles\n**H+4 :** Première communication externe ("Nous sommes informés de la situation et nous agissons")\n**H+24 :** Communication complète avec explication et mesures\n\n## Les 3 C de la communication de crise\n\n### Compassion\nMontrez que vous vous souciez des personnes affectées avant de défendre votre organisation.\n\n**À dire :** "Nos premières pensées vont aux personnes touchées par cet incident. Leur bien-être est notre priorité absolue."\n**À éviter :** Commencer par les aspects juridiques ou financiers\n\n### Compétence\nDémontrez que vous maîtrisez la situation et que vous prenez les mesures appropriées.\n\n"Notre équipe de crise est mobilisée 24h/24. Voici les mesures immédiates prises..."\n\n### Cohérence\nUn message unique, une voix unique. Toute l''organisation doit tenir le même discours.\n\n**Nommez un porte-parole unique** pour toute la durée de la crise.\n\n## Gérer les réseaux sociaux en crise\n\n**En Afrique :** Facebook, WhatsApp et Twitter/X peuvent amplifier une crise en quelques heures.\n\n### Protocole réseaux sociaux\n1. **Monitorez** en continu dès le début de la crise\n2. **Ne supprimez pas** les commentaires négatifs (ça empire les choses)\n3. **Répondez** à chaque commentaire, même les plus agressifs\n4. **Reconnaissez** les faits vrais, corrigez les informations fausses\n5. **Publiez** des mises à jour régulières (toutes les 2-4 heures en phase aiguë)\n\n## Ce qu''il ne faut JAMAIS faire en crise\n1. **Mentir ou minimiser** : aggravation garantie quand la vérité émerge\n2. **Attaquer** les journalistes ou les lanceurs d''alerte\n3. **Pratiquer le "no comment"** : silence = culpabilité dans l''esprit public\n4. **Se précipiter** sur des explications incomplètes : ne communiquer que ce qu''on sait\n5. **Oublier** les parties prenantes internes (employés apprennent par les réseaux avant d''être informés)'),

  -- Module 7 : Communication digitale
  (v_mod7, v_course_id, 'Construire votre personal branding professionnel en Afrique', 'document', 1, false,
   E'# Personal Branding Professionnel en Afrique\n\n## Pourquoi le personal branding est crucial aujourd''hui\n\nDans une économie africaine de plus en plus connectée, votre réputation professionnelle n''est plus seulement ce que savent de vous les personnes que vous avez rencontrées — c''est aussi ce qu''on trouve sur vous en ligne.\n\nUn recruteur, un partenaire potentiel ou un client Google votre nom avant de vous rencontrer. Que trouvent-ils ?\n\n## Les 3 piliers du personal branding africain\n\n### Pilier 1 : La clarté de votre positionnement\n**Qui êtes-vous professionnellement ?**\n\nRépondez en une phrase : "Je suis [titre/rôle] qui aide [cible] à [résultat] grâce à [compétence distinctive]."\n\nExemple : "Je suis consultant en marketing digital qui aide les PME africaines à doubler leur clientèle en ligne grâce à une approche data-driven adaptée aux réalités locales."\n\n**Votre spécialité africaine :**\nEn Afrique, se positionner comme expert d''une problématique locale spécifique est plus puissant que d''imiter les experts occidentaux. Votre contextualisation est votre différence.\n\n### Pilier 2 : Votre présence en ligne\n\n**LinkedIn — la plateforme prioritaire pour les professionnels**\n\nOptimisation de votre profil :\n- **Photo professionnelle** : fond neutre, tenue professionnelle, sourire\n- **Titre** : pas votre intitulé de poste, mais votre proposition de valeur\n  ❌ "Responsable Marketing chez XYZ"\n  ✅ "Expert Marketing Digital | J''aide les PME africaines à croître en ligne | +15M XOF de CA généré"\n- **Section À propos** : 3 paragraphes — votre histoire, votre expertise, votre offre de valeur\n- **Expériences** : résultats chiffrés, pas de descriptions de poste\n- **Recommandations** : demandez à 5-10 personnes de laisser une recommandation\n\n**Publication régulière sur LinkedIn (2-3 fois/semaine) :**\n- Partages d''expériences professionnelles avec leçon apprise\n- Points de vue sur l''actualité de votre secteur\n- Conseils pratiques pour votre audience cible\n- Interviews ou rencontres inspirantes\n\n### Pilier 3 : Vos prises de parole publiques\n\n- **Conférences et panels** : proposez vos services comme intervenant\n- **Articles et tribunes** : journaux économiques africains, blogs sectoriels\n- **Podcasts** : en tant qu''invité ou créateur\n- **Formations et webinaires** : enseignez ce que vous savez\n\n## Construire votre réseau en Afrique\n\n**La règle du 10-5-1 :**\n- 10 personnes de votre secteur à suivre et interagir chaque semaine\n- 5 professionnels à rencontrer (café, LinkedIn call) chaque mois\n- 1 mentor ou relation stratégique à cultiver chaque trimestre\n\n**Associations et clubs professionnels (Côte d''Ivoire) :**\n- CIE (Chambre de Commerce et d''Industrie)\n- Club des Dirigeants\n- Lions Club, Rotary\n- Associations professionnelles sectorielles\n- Alumni de votre université ou grande école');

END $$;
