-- ============================================================
-- ENRICHISSEMENT FORMATIONS 3 À 9 (formations 1 et 2 déjà exécutées)
-- Exécuter ce fichier en une seule fois dans le SQL Editor Supabase
-- ============================================================


-- ============================================================
-- FORMATION 3 : Excel & Google Sheets Avancé
-- ============================================================
DO $$ DECLARE
  v_course_id uuid;
  v_mod5 uuid; v_mod6 uuid; v_mod7 uuid; v_mod8 uuid;
  v_max_pos int;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'excel-google-sheets-avance-professionnels';
  SELECT COALESCE(MAX(position), 0) INTO v_max_pos FROM modules WHERE course_id = v_course_id;

  INSERT INTO modules (course_id, title, position) VALUES
    (v_course_id, 'Tableaux Croisés Dynamiques Avancés', v_max_pos + 1),
    (v_course_id, 'Power Query et Connexion à des Données Externes', v_max_pos + 2),
    (v_course_id, 'Macros VBA et Automatisation Excel', v_max_pos + 3),
    (v_course_id, 'Tableaux de Bord et Visualisation Professionnelle', v_max_pos + 4);

  SELECT id INTO v_mod5 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos LIMIT 1;
  SELECT id INTO v_mod6 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 1 LIMIT 1;
  SELECT id INTO v_mod7 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 2 LIMIT 1;
  SELECT id INTO v_mod8 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 3 LIMIT 1;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES

  -- Module 5 : TCD Avancés
  (v_mod5, v_course_id, 'Maîtriser les Tableaux Croisés Dynamiques de A à Z', 'document', 1, false,
   E'# Tableaux Croisés Dynamiques Avancés\n\n## Rappel : Qu''est-ce qu''un TCD ?\nUn TCD (Tableau Croisé Dynamique) transforme une liste de données brutes en rapport synthétique interactif en quelques clics. C''est l''outil le plus puissant d''Excel pour l''analyse de données.\n\n## Préparer vos données pour un TCD\n\n### Règles d''or\n1. **Une ligne = un enregistrement** (pas de lignes vides, pas de sous-totaux)\n2. **Une colonne = un champ** (entêtes claires en ligne 1)\n3. **Données homogènes** dans chaque colonne (pas de mélange texte/nombre)\n4. **Pas de cellules fusionnées**\n\n## Créer un TCD\n```\nInsertion → Tableau croisé dynamique\n→ Sélectionner votre tableau\n→ Nouvelle feuille de calcul\n→ OK\n```\n\n## Les 4 zones du TCD\n\n| Zone | Rôle | Exemple |\n|------|------|---------|\n| **Filtres** | Filtrer tout le rapport | Année, Région |\n| **Colonnes** | Répartir en colonnes | Mois, Trimestre |\n| **Lignes** | Répartir en lignes | Produit, Client |\n| **Valeurs** | Ce qu''on calcule | CA, Quantité |\n\n## Champs calculés\n```\nAnalyse → Champs, éléments et jeux → Champ calculé\nNom : "Marge brute"\nFormule : =CA - Coûts\n```\n\n## Groupement des données\nCliquez sur une date dans le TCD → clic droit → Grouper\nChoix : Jours, Mois, Trimestres, Années'),

  (v_mod5, v_course_id, 'Graphiques Croisés Dynamiques et Segments Interactifs', 'document', 2, false,
   E'# Graphiques Croisés Dynamiques et Interactivité\n\n## Graphique Croisé Dynamique (GCD)\nUn GCD est lié à votre TCD — il se met à jour automatiquement quand vous modifiez le TCD.\n\n### Créer un GCD\n```\nCliquer dans le TCD\n→ Analyse → Graphique croisé dynamique\n→ Choisir le type de graphique\n→ OK\n```\n\n## Segments (Slicers) — filtres visuels interactifs\n\n### Ajouter des segments\n```\nCliquer dans le TCD\n→ Analyse → Insérer un segment\n→ Cocher les champs voulus (ex : Région, Produit, Période)\n→ OK\n```\n\n### Connecter un segment à plusieurs TCD\n```\nClic droit sur le segment\n→ Connexions de rapport\n→ Cocher tous les TCD à connecter\n```\nMaintenant, un clic filtre tous les TCD simultanément.\n\n## Chronologie — filtre de dates\n```\nCliquer dans le TCD avec des dates\n→ Analyse → Insérer une chronologie\n```\n\n## Architecture dashboard recommandée\n1. **Feuille "Données"** : données brutes (masquée)\n2. **Feuille "TCD"** : tableaux croisés (masquée)\n3. **Feuille "Dashboard"** : graphiques et segments'),

  (v_mod5, v_course_id, 'Fonctions de recherche avancées : INDEX/EQUIV et XLOOKUP', 'document', 3, false,
   E'# Fonctions de Recherche Avancées\n\n## INDEX/EQUIV vs VLOOKUP\n\nVLOOKUP (RECHERCHEV) a trois limitations :\n1. Ne peut chercher qu''à gauche\n2. Sensible au déplacement de colonnes\n3. Lent sur grandes bases\n\n## EQUIV (MATCH)\nRetourne la **position** d''une valeur dans une plage\n```\n=EQUIV("Abidjan"; A2:A100; 0)\n→ Retourne 5 si "Abidjan" est en 5ème position\n```\n\n## INDEX\nRetourne la **valeur** d''une cellule selon sa position\n```\n=INDEX(B2:B100; 5)\n→ Retourne la valeur de la 5ème cellule\n```\n\n## La combinaison INDEX/EQUIV\n```\n=INDEX(plage_résultat; EQUIV(valeur_cherchée; plage_recherche; 0))\n```\n\n**Exemple :**\n```\n=INDEX(C:C; EQUIV("Client ABC"; A:A; 0))\n```\n\n## XLOOKUP (Excel 365)\n```\n=XLOOKUP(valeur_cherchée; plage_recherche; plage_résultat; [si_non_trouvé])\n```\n\n**Avantages :** cherche dans les deux sens, gère les erreurs nativement, peut retourner plusieurs colonnes.'),

  -- Module 6 : Power Query
  (v_mod6, v_course_id, 'Power Query : Importer et transformer des données automatiquement', 'document', 1, false,
   E'# Power Query : La Révolution de l''Import de Données\n\n## Qu''est-ce que Power Query ?\nPower Query permet d''importer des données depuis n''importe quelle source, les nettoyer et les transformer automatiquement — sans une seule formule.\n\n**Cas d''usage typiques en Afrique :**\n- Consolider les rapports de vente de 12 agences en un seul tableau\n- Importer automatiquement les données d''une API\n- Nettoyer des exports CSV de votre logiciel de gestion\n- Fusionner deux bases de données (clients + commandes)\n\n## Accéder à Power Query\n```\nDonnées → Obtenir des données\n```\n\n## Opérations courantes\n```\nAccueil → Supprimer les lignes vides\nAccueil → Supprimer les doublons\nTransformer → Supprimer les espaces\nTransformer → Modifier le type\nTransformer → Fractionner la colonne\n```\n\n## Consolider plusieurs fichiers identiques\n```\nDonnées → Obtenir des données → À partir d''un fichier → À partir d''un dossier\n→ Sélectionner le dossier contenant vos fichiers mensuels\n```\nAjoutez un nouveau fichier → Actualisez → Il apparaît automatiquement.\n\n## Fusionner deux tables\n```\nAccueil → Fusionner des requêtes\n→ Sélectionner la colonne clé commune (ex : ID_Client)\n→ Type de fusion : Externe gauche\n```'),

  (v_mod6, v_course_id, 'Google Sheets : fonctions avancées et collaboration en temps réel', 'document', 2, false,
   E'# Google Sheets Avancé\n\n## Pourquoi Google Sheets en Afrique ?\n- **Gratuit** (contrairement à Excel)\n- **Fonctionne dans le navigateur**\n- **Collaboration temps réel** simultanée\n- **Accessible sur mobile** avec 3G/4G\n- **Sauvegarde automatique dans le cloud**\n\n## Fonctions exclusives à Google Sheets\n\n### QUERY — SQL dans vos feuilles\n```\n=QUERY(données; "SELECT A, B, SUM(C) WHERE D = ''Abidjan'' GROUP BY A, B")\n```\n\n### IMPORTRANGE — Importer d''une autre feuille\n```\n=IMPORTRANGE("URL_du_fichier_source"; "Feuille1!A1:D100")\n```\n\n### ARRAYFORMULA — Formule sur toute une colonne\n```\n=ARRAYFORMULA(A2:A100 * B2:B100)\n```\n\n### GOOGLEFINANCE — Données financières en temps réel\n```\n=GOOGLEFINANCE("EURUSD"; "price")\n```\n\n## Protéger certaines plages\n```\nClic droit → Protéger la plage\n→ Définir qui peut modifier\n```\n\n## Automatiser avec Google Apps Script\n```javascript\nfunction envoyerRapportMensuel() {\n  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("Résumé");\n  MailApp.sendEmail("direction@monentreprise.ci", "Rapport mensuel", "Corps du rapport");\n}\n```'),

  -- Module 7 : Macros VBA
  (v_mod7, v_course_id, 'Introduction aux Macros VBA : automatiser vos tâches répétitives', 'document', 1, false,
   E'# Macros VBA : Automatiser Excel\n\n## Activer l''onglet Développeur\n```\nFichier → Options → Personnaliser le ruban\n→ Cocher "Développeur"\n```\n\n## Enregistrer une macro (sans coder)\n```\nDéveloppeur → Enregistrer une macro\n→ Nommer la macro\n→ Raccourci clavier (ex : Ctrl+Shift+R)\n→ OK\n[Effectuez vos actions Excel normalement]\n→ Développeur → Arrêter l''enregistrement\n```\n\n## Concepts VBA essentiels\n\n### Variables\n```vba\nDim MonNombre As Integer\nDim MonTexte As String\nMonNombre = 42\n```\n\n### Conditions\n```vba\nIf Cells(i, 3).Value > 1000000 Then\n    Cells(i, 3).Interior.Color = RGB(0, 255, 0)\nElse\n    Cells(i, 3).Interior.Color = RGB(255, 0, 0)\nEnd If\n```\n\n### Boucles\n```vba\nFor i = 2 To 100\n    Cells(i, 5).Value = Cells(i, 3).Value - Cells(i, 4).Value\nNext i\n```\n\n## Macro pratique : Générer une facture\n```vba\nSub GenererFacture()\n    Dim NumFacture As Integer\n    NumFacture = Sheets("Paramètres").Range("B1").Value + 1\n    Sheets("Modele_Facture").Copy After:=Sheets(Sheets.Count)\n    ActiveSheet.Name = "Facture_" & NumFacture\n    Range("D3").Value = "FAC-" & Format(NumFacture, "0000")\n    Range("D4").Value = Date\n    Sheets("Paramètres").Range("B1").Value = NumFacture\n    MsgBox "Facture N°" & NumFacture & " créée !", vbInformation\nEnd Sub\n```'),

  (v_mod7, v_course_id, 'Créer des formulaires et boîtes de dialogue VBA', 'document', 2, false,
   E'# Formulaires VBA (UserForms)\n\n## Créer un UserForm\n```\nDéveloppeur → Visual Basic → Insertion → UserForm\n```\n\n## Contrôles essentiels\n\n| Contrôle | Usage |\n|----------|-------|\n| Label | Texte descriptif |\n| TextBox | Saisie libre |\n| ComboBox | Liste déroulante |\n| CommandButton | Bouton d''action |\n\n## Exemple : Formulaire de saisie client\n\n```vba\nPrivate Sub UserForm_Initialize()\n    ComboBox_Region.AddItem "Abidjan"\n    ComboBox_Region.AddItem "Bouaké"\n    ComboBox_Region.AddItem "San Pedro"\n    TextBox_Date.Value = Format(Date, "DD/MM/YYYY")\nEnd Sub\n\nPrivate Sub CommandButton_Enregistrer_Click()\n    If TextBox_Nom.Value = "" Then\n        MsgBox "Veuillez saisir le nom du client.", vbExclamation\n        Exit Sub\n    End If\n    Dim DerniereLigne As Long\n    DerniereLigne = Sheets("Clients").Cells(Rows.Count, 1).End(xlUp).Row + 1\n    With Sheets("Clients")\n        .Cells(DerniereLigne, 1).Value = TextBox_Nom.Value\n        .Cells(DerniereLigne, 2).Value = ComboBox_Region.Value\n        .Cells(DerniereLigne, 3).Value = Now()\n    End With\n    MsgBox "Client enregistré !", vbInformation\nEnd Sub\n```'),

  -- Module 8 : Tableaux de bord
  (v_mod8, v_course_id, 'Concevoir un tableau de bord Excel professionnel', 'document', 1, false,
   E'# Tableau de Bord Excel Professionnel\n\n## Les principes du bon design\n\n### 1. Clarté avant beauté\nUn bon dashboard répond à une question en moins de 5 secondes.\n\n### 2. La règle des 3 couleurs max\n- **Couleur principale** : couleur d''entreprise\n- **Couleur d''accentuation** : orange pour les KPIs clés\n- **Couleur d''alerte** : rouge pour les problèmes\n\n### 3. La hiérarchie visuelle\n1. **KPIs en gros chiffres** (en haut)\n2. **Graphiques principaux** (centre)\n3. **Tableaux détaillés** (bas)\n\n## Structure d''un dashboard de performance commerciale\n\n```\n┌─────────────┬─────────────┬─────────────┬─────────────┐\n│  CA du mois │ Nb commandes│ Ticket moyen│ Croissance  │\n│ 45,3M XOF   │     127     │  356k XOF   │   +23%      │\n└─────────────┴─────────────┴─────────────┴─────────────┘\n```\n\n## Rendre le dashboard dynamique\n\n### Listes déroulantes de contrôle\n```\nDéveloppeur → Insérer → Zone de liste déroulante\n→ Lier à une cellule nommée (ex : C_Annee)\n```\n\nVos formules utilisent cette cellule :\n```\n=SUMIFS(CA; Annee; C_Annee; Region; C_Region)\n```\n\n## Mise en forme conditionnelle avec icônes\n```\nSélectionner la colonne "Variation"\n→ Mise en forme conditionnelle\n→ Jeux d''icônes → 3 flèches (vert/jaune/rouge)\n```\n\n## Exporter et partager\n- **PDF** : Fichier → Exporter → PDF\n- **Image** : Copier → Coller comme image (pour PowerPoint)\n- **SharePoint** : Publier directement depuis Excel 365');

END $$;


-- ============================================================
-- FORMATION 4 : Management et Leadership en Afrique
-- ============================================================
DO $$ DECLARE
  v_course_id uuid;
  v_mod5 uuid; v_mod6 uuid; v_mod7 uuid;
  v_max_pos int;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'management-leadership-afrique';
  SELECT COALESCE(MAX(position), 0) INTO v_max_pos FROM modules WHERE course_id = v_course_id;

  INSERT INTO modules (course_id, title, position) VALUES
    (v_course_id, 'Intelligence Émotionnelle et Leadership Africain', v_max_pos + 1),
    (v_course_id, 'Gestion du Changement et Transformation Organisationnelle', v_max_pos + 2),
    (v_course_id, 'Coaching, Mentorat et Développement des Talents', v_max_pos + 3);

  SELECT id INTO v_mod5 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos LIMIT 1;
  SELECT id INTO v_mod6 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 1 LIMIT 1;
  SELECT id INTO v_mod7 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 2 LIMIT 1;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES

  (v_mod5, v_course_id, 'L''intelligence émotionnelle : le facteur clé du leadership africain', 'document', 1, false,
   E'# Intelligence Émotionnelle et Leadership\n\n## Pourquoi l''IE est cruciale en contexte africain\nDans les organisations africaines, les relations humaines précèdent souvent les processus. Daniel Goleman a montré que **l''IE explique 67% de la différence de performance entre leaders**.\n\n## Les 5 composantes de l''IE\n\n### 1. La conscience de soi\nCapacité à reconnaître ses propres émotions et leur impact.\n\n**Comment la développer :**\n- Tenir un journal quotidien de vos émotions\n- Solliciter des feedbacks réguliers\n- Pratiquer la pleine conscience (10min/jour)\n\n### 2. La maîtrise de soi\n**Protocole en situation de tension :**\n1. Inspirez profondément (4 secondes)\n2. Demandez un délai : "Donnez-moi quelques minutes"\n3. Identifiez l''émotion ressentie\n4. Cherchez la réponse, pas la réaction\n\n### 3. La motivation intrinsèque\nLeaders africains influents — Cheikh Anta Diop, Wangari Maathai, Nelson Mandela — leur point commun : une mission qui dépasse leur intérêt personnel.\n\n### 4. L''empathie\nL''ubuntu ("Je suis parce que nous sommes") est une valeur culturelle profonde. Exploitez-la dans votre management.\n\n**Pratiques :**\n- Commencer les réunions par "Comment allez-vous vraiment ?"\n- Se souvenir des événements importants (naissances, deuils)\n\n### 5. Les compétences sociales\n- Communiquer avec clarté et chaleur\n- Gérer les conflits en cherchant les intérêts communs\n- Construire des coalitions et des réseaux'),

  (v_mod5, v_course_id, 'Gérer les personnalités difficiles et les conflits d''équipe', 'document', 2, false,
   E'# Gérer les Conflits et Personnalités Difficiles\n\n## La méthode DESC\n**D**écrire les faits : "J''ai observé que lors de la réunion de lundi..."\n**E**xprimer le ressenti : "Cela m''a mis dans une position difficile parce que..."\n**S**pécifier ce qui est attendu : "À l''avenir, je souhaite que..."\n**C**onséquences positives : "Ce qui permettra de..."\n\n## Les types de conflits\n- **Conflit de tâches :** désaccord sur comment faire le travail → peut être sain\n- **Conflit de ressources :** compétition pour budget, équipement\n- **Conflit relationnel :** tensions personnelles → toujours destructeur\n\n## Les personnalités difficiles\n\n### Le "résistant passif"\nNe s''oppose pas ouvertement mais sabote discrètement.\n**Gestion :** Entretien individuel, identifier la résistance réelle, donner une responsabilité visible.\n\n### Le "politique"\nManipule les relations pour servir ses intérêts.\n**Gestion :** Clarifier les règles collectivement, valoriser la transparence en public.\n\n### Le "surperformant toxique"\nExcellent techniquement mais détruit la cohésion.\n**Gestion :** Nommer le comportement (pas la personne), inclure des critères comportementaux dans les objectifs.\n\n## Le feedback constructif SBI\n```\n"Dans la situation [X],\nj''ai observé que tu as [comportement Y],\net l''impact que ça a eu est [Z]."\n```'),

  (v_mod5, v_course_id, 'Leadership situationnel : adapter son style selon le contexte', 'document', 3, false,
   E'# Leadership Situationnel\n\n## Les 4 niveaux de maturité\n\n| Niveau | Compétence | Motivation | Profil type |\n|--------|-----------|------------|-------------|\n| M1 | Faible | Élevée | Nouvel employé enthousiaste |\n| M2 | Faible/Modérée | Variable | Employé qui perd confiance |\n| M3 | Élevée | Variable | Expert manquant de confiance |\n| M4 | Élevée | Élevée | Top performer autonome |\n\n## Les 4 styles de leadership\n\n### Style S1 : Directif (pour M1)\nDites exactement QUOI faire, COMMENT, QUAND et OÙ.\n- Donnez des instructions détaillées\n- Supervisez de près\n\n### Style S2 : Coach/Persuasif (pour M2)\n- Expliquez le POURQUOI\n- Demandez leur avis avant de décider\n- Reconnaissez les progrès même partiels\n\n### Style S3 : Soutien/Participatif (pour M3)\n- "Comment ferais-tu toi-même ?"\n- Validez leurs compétences publiquement\n\n### Style S4 : Délégation (pour M4)\n- Donnez l''objectif, pas la méthode\n- Faites confiance jusqu''à preuve du contraire\n- Reconnaissez publiquement leurs succès\n\n## L''entretien de délégation efficace\n1. **Contexte :** "Voilà pourquoi cette mission est importante..."\n2. **Mission :** "Je te confie la responsabilité de..."\n3. **Résultats attendus :** "Dans 3 semaines, j''attends..."\n4. **Ressources :** "Tu disposes de..."\n5. **Autonomie :** "Tu prends les décisions sur X. Tu me consultes sur Z."\n6. **Points de contrôle :** "On fait un point le..."'),

  -- Module 6 : Gestion du changement
  (v_mod6, v_course_id, 'Conduire le changement dans les organisations africaines', 'document', 1, false,
   E'# Conduite du Changement en Afrique\n\n## Pourquoi le changement échoue souvent\nSelon McKinsey, **70% des projets de changement organisationnel échouent** parce qu''on gère les processus mais on néglige les personnes.\n\n## Le modèle ADKAR\n\n| Étape | Question clé | Action du leader |\n|-------|-------------|------------------|\n| **A**wareness | "Pourquoi changer ?" | Communiquer le contexte |\n| **D**esire | "Pourquoi MOI changer ?" | Identifier les motivations personnelles |\n| **K**nowledge | "Comment changer ?" | Former, donner des outils |\n| **A**bility | "Puis-je changer ?" | Pratiquer, accompagner |\n| **R**einforcement | "Cela vaut-il la peine ?" | Reconnaître, récompenser |\n\n## Stratégies de gestion des résistances\n\n### Les ambassadeurs du changement\nIdentifiez des personnes influentes et respectées dans chaque équipe. Convainquez-les en premier — ils convaincront les autres.\n\nEn Afrique : les "anciens" sont souvent les vrais influenceurs.\n\n## Communication du changement : plan en 4 temps\n1. **Avant** : annonce officielle par la direction\n2. **Pendant** : points réguliers, FAQ\n3. **Après chaque étape** : célébration des succès intermédiaires\n4. **À l''arrivée** : reconnaissance collective et individuelle'),

  (v_mod6, v_course_id, 'Piloter une transformation digitale dans votre organisation', 'document', 2, false,
   E'# Transformation Digitale des Organisations Africaines\n\n## Les 4 dimensions\n\n### 1. Expérience client\n- Du présentiel vers l''omnicanal\n- Personnalisation grâce aux données\n\n### 2. Opérations internes\n- Automatisation des tâches répétitives\n- Gestion des données en temps réel\n\n### 3. Modèle commercial\n- Nouveaux flux de revenus\n- Partenariats avec des fintech, agritech, edtech\n\n### 4. Culture et compétences\n- Agilité et droit à l''erreur\n- Formation continue\n\n## Feuille de route pour PME africaine\n\n### Phase 1 : Fondations (Mois 1-3)\n- Équiper tous les collaborateurs d''un email professionnel\n- Passer à Google Workspace ou Microsoft 365\n- Mettre en place un CRM simple (HubSpot Free, Odoo)\n- Digitaliser la facturation\n\n### Phase 2 : Optimisation (Mois 4-9)\n- Site web professionnel avec paiement en ligne\n- Présence réseaux sociaux structurée\n- Formation des équipes\n\n### Phase 3 : Innovation (Mois 10-18)\n- Analytics et pilotage par les données\n- Automatisation marketing\n- Exploration IA (chatbot, prédictions)\n\n## Les erreurs à éviter\n1. Digitaliser sans former\n2. Ignorer la connectivité\n3. Tout faire en même temps\n4. Négliger la cybersécurité'),

  (v_mod6, v_course_id, 'Piloter la performance organisationnelle avec les OKR', 'document', 3, false,
   E'# OKR : Objectives & Key Results\n\n## Structure d''un OKR\n\n### L''Objectif (O)\nAmbitieux, inspirant, qualitatif — 3-5 objectifs maximum par trimestre.\n\n**Exemple :** "Devenir la référence du conseil RH en Afrique de l''Ouest"\n\n### Les Résultats Clés (KR)\nMesurables, quantifiables — 3-5 par objectif.\n\n**Exemple :**\n- KR1 : Atteindre 50 clients entreprises (vs 22 actuellement)\n- KR2 : NPS de 70 ou plus\n- KR3 : Publier 2 études de cas mensuelles\n\n## Aligner les OKR\n\n```\nOKR Entreprise → OKR Département → OKR Équipe → OKR Individuel\n```\n\n## Cycle OKR trimestriel\n\n**Semaine 1 :** Direction fixe les OKR entreprise\n**Chaque semaine :** Check-in 15 minutes par OKR (avancement 0-100%)\n**Fin du trimestre :** Score final + rétrospective\n\n## Le scoring OKR\n\n| Score | Signification |\n|-------|---------------|\n| 0,7 - 1,0 | Excellent |\n| 0,4 - 0,7 | Satisfaisant |\n| 0,0 - 0,4 | Insuffisant |\n\n> Un score de 0,7 est considéré comme réussi. Si vous atteignez 1,0 systématiquement, vos objectifs ne sont pas assez ambitieux.'),

  -- Module 7 : Coaching et mentorat
  (v_mod7, v_course_id, 'Devenir un manager-coach : libérer le potentiel de votre équipe', 'document', 1, false,
   E'# Le Manager-Coach\n\n## Le modèle GROW\n\n**G**oal — Quel est l''objectif ?\n- "Qu''est-ce que tu veux accomplir ?"\n- "Pour quand ?"\n\n**R**eality — Quelle est la situation actuelle ?\n- "Où en es-tu maintenant ?"\n- "Qu''as-tu déjà essayé ?"\n\n**O**ptions — Quelles sont les options ?\n- "Que pourrais-tu faire ?"\n- "Y a-t-il d''autres possibilités ?"\n\n**W**ill — Quel est ton engagement ?\n- "Que vas-tu faire concrètement ?"\n- "Quand le feras-tu ?"\n\n## Les questions puissantes du coach\n\n### Questions de responsabilisation\n- "Sur une échelle de 1 à 10, quel est ton niveau d''engagement ?"\n- "Qu''est-ce qui pourrait t''empêcher de tenir cet engagement ?"\n\n## Programme de mentorat en 4 phases\n\n### Phase 1 : Sélection des mentors\n- Cadres seniors reconnus pour leurs valeurs\n- Volontaires (le mentorat forcé ne fonctionne pas)\n\n### Phase 2 : Appariement\n- Intérêts professionnels compatibles\n- Pas de lien hiérarchique direct\n\n### Phase 3 : Structure des sessions\n- 1h par mois minimum pendant 6 mois\n- Agenda co-construit par le mentoré\n- Confidentialité totale\n\n### Phase 4 : Évaluation\n- Questionnaire satisfaction à 3 mois\n- Célébration collective des parcours'),

  (v_mod7, v_course_id, 'Construire une culture de haute performance en Afrique', 'document', 2, false,
   E'# Culture de Haute Performance\n\n## Peter Drucker : "La culture mange la stratégie au petit-déjeuner."\n\n## Les marqueurs d''une culture haute performance\n\n### 1. La clarté du "Pourquoi"\nChaque collaborateur sait pourquoi l''organisation existe.\n\n### 2. La sécurité psychologique\nL''équipe peut prendre des risques et partager des idées sans crainte.\n\n**Comment créer la sécurité psychologique :**\n- Le manager partage ses propres erreurs\n- Les bonnes questions sont célébrées\n- Les post-mortems sont blameless\n\n### 3. La reconnaissance fréquente\n**Ce qui est reconnu est reproduit.**\n\nFormes adaptées à la culture africaine :\n- Célébration publique en réunion\n- Lettre de félicitations partagée avec la famille\n- Responsabilités élargies\n\n## Rituels de culture haute performance\n\n| Rituel | Fréquence | Objectif |\n|--------|-----------|----------|\n| Stand-up morning (15min) | Quotidien | Alignement |\n| Célébration des victoires | Hebdomadaire | Motivation |\n| Rétrospective d''équipe | Mensuelle | Amélioration |\n| Team building | Semestrielle | Cohésion |\n\n## Mesurer votre culture (5 questions, note 1-10)\n1. Je comprends et adhère à la mission de notre organisation\n2. Je me sens valorisé et reconnu pour mon travail\n3. Mon manager m''aide à progresser\n4. Je dispose des ressources nécessaires\n5. Je recommanderais cette organisation à un ami\n\n**Score > 7/10 :** culture saine');

END $$;


-- ============================================================
-- FORMATION 5 : Comptabilité OHADA pour PME
-- ============================================================
DO $$ DECLARE
  v_course_id uuid;
  v_mod5 uuid; v_mod6 uuid; v_mod7 uuid;
  v_max_pos int;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'comptabilite-ohada-pme-sans-etre-comptable';
  SELECT COALESCE(MAX(position), 0) INTO v_max_pos FROM modules WHERE course_id = v_course_id;

  INSERT INTO modules (course_id, title, position) VALUES
    (v_course_id, 'États Financiers OHADA : Lire et Analyser le Bilan et le Compte de Résultat', v_max_pos + 1),
    (v_course_id, 'Gestion de Trésorerie et Prévisions Financières', v_max_pos + 2),
    (v_course_id, 'Fiscalité des PME en Zone OHADA', v_max_pos + 3);

  SELECT id INTO v_mod5 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos LIMIT 1;
  SELECT id INTO v_mod6 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 1 LIMIT 1;
  SELECT id INTO v_mod7 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 2 LIMIT 1;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES

  (v_mod5, v_course_id, 'Lire et comprendre le Bilan comptable OHADA', 'document', 1, false,
   E'# Le Bilan Comptable OHADA\n\n## Qu''est-ce que le bilan ?\nLe bilan est une **photographie de la situation financière** à un instant T.\n\n**Équation fondamentale : ACTIF = PASSIF**\n\n## Structure du bilan OHADA\n\n### ACTIF\n- **Actif Immobilisé** : terrain, bâtiment, matériel, véhicules, brevets\n- **Stocks** (compte 3)\n- **Créances clients** (compte 411)\n- **Disponibilités** (compte 5) : caisse, banque, mobile money\n\n### PASSIF\n- **Capitaux Propres** : capital social, réserves, résultat\n- **Dettes à Long Terme** : emprunts bancaires\n- **Dettes à Court Terme** : fournisseurs, fiscales, sociales\n\n## Exemple pratique (PME abidjanaise, en milliers XOF)\n\n| ACTIF | Montant | PASSIF | Montant |\n|-------|---------|--------|----------|\n| Immobilisations | 8 500 | Capital social | 5 000 |\n| Stocks | 3 200 | Réserves | 2 800 |\n| Créances clients | 4 800 | Résultat | 1 200 |\n| Disponibilités | 1 500 | Emprunts LT | 4 000 |\n| | | Dettes CT | 5 000 |\n| **Total** | **18 000** | **Total** | **18 000** |\n\n**Analyse rapide :**\n- L''entreprise est solvable (capitaux propres positifs)\n- Dettes CT (5 000) > Disponibilités (1 500) → vigilance trésorerie'),

  (v_mod5, v_course_id, 'Analyser le Compte de Résultat et les Soldes Intermédiaires de Gestion', 'document', 2, false,
   E'# Compte de Résultat et SIG OHADA\n\n## Le Compte de Résultat\nAlors que le bilan est une photo, le CR est un **film** de l''exercice.\n\n**Résultat = Produits - Charges**\n\n## Les Soldes Intermédiaires de Gestion (SIG)\n\n### 1. Marge commerciale\n```\nMarge = Ventes marchandises - Coût d''achat marchandises vendues\nTaux de marge = Marge / Ventes × 100\n```\n\n### 2. Valeur Ajoutée (VA)\n```\nVA = Marge brute - Services extérieurs - Autres charges\n```\nMesure la richesse créée par l''entreprise.\n\n### 3. Excédent Brut d''Exploitation (EBE)\n```\nEBE = VA - Charges de personnel - Impôts et taxes\n```\n**Indicateur le plus important pour les banques.**\n\n### 4. Résultat Net\n```\nRésultat net = REX ± Résultat financier ± Résultat exceptionnel - IS\n```\n\n## Ratios d''analyse\n\n| Ratio | Formule | Référence secteur |\n|-------|---------|-------------------|\n| Taux de marge brute | Marge brute/CA | 20-40% |\n| Taux d''EBE | EBE/CA | 5-15% |\n| Taux de résultat net | Résultat net/CA | 2-8% |'),

  (v_mod5, v_course_id, 'Tableau de flux de trésorerie : comprendre les mouvements de cash', 'document', 3, false,
   E'# Tableau de Flux de Trésorerie\n\n## Pourquoi le cash est roi\n**Une entreprise peut être rentable et mourir de manque de cash.**\n\nExemple : PME sénégalaise réalise 50M XOF de CA, résultat net 5M XOF (rentable), mais elle a accordé 90 jours de crédit à ses clients et doit payer ses fournisseurs à 30 jours → **cessation de paiement malgré son bénéfice**.\n\n## Les 3 catégories de flux\n\n### 1. Flux d''exploitation\n```\nRésultat net\n+ Amortissements (charge non décaissée)\n+/- Variation du BFR\n= Flux d''exploitation\n```\n\n### 2. Flux d''investissement\n```\n- Acquisitions d''immobilisations\n+ Cessions d''immobilisations\n= Flux d''investissement\n```\n\n### 3. Flux de financement\n```\n+ Nouveaux emprunts\n- Remboursements d''emprunts\n+ Apports en capital\n- Dividendes distribués\n= Flux de financement\n```\n\n## Budget de trésorerie prévisionnel mensuel\n\n```\n                Jan    Fév    Mars\nSolde début     X      X      X\n+ Recettes       X      X      X\n- Dépenses       X      X      X\nFlux net         X      X      X\nSolde fin        X      X      X\n```\n\n**Objectif :** Anticiper les mois déficitaires pour prendre des mesures préventives.'),

  -- Module 6 : Trésorerie
  (v_mod6, v_course_id, 'Optimiser le Besoin en Fonds de Roulement (BFR)', 'document', 1, false,
   E'# Optimiser le BFR de votre PME\n\n## Comprendre le BFR\n```\nBFR = Stocks + Créances clients - Dettes fournisseurs\n```\n\n**BFR positif :** vous avez besoin de trésorerie pour faire tourner votre activité.\n**BFR négatif (supermarchés) :** vous encaissez avant de payer → enviable !\n\n## Exemple concret\n\nPME de distribution en Côte d''Ivoire :\n- Stocks : 8 000 000 XOF\n- Créances clients : 12 000 000 XOF\n- Dettes fournisseurs : 6 000 000 XOF\n\n```\nBFR = 8 + 12 - 6 = 14 000 000 XOF\n```\n\n## Les 3 leviers pour réduire le BFR\n\n### Levier 1 : Réduire les stocks\n- Calculez la rotation de chaque produit\n- Liquidez les stocks dormants\n- Négociez des livraisons plus fréquentes\n\n**Ratio :** Durée de stockage = (Stock moyen / Achats) × 360 → Objectif : < 30 jours\n\n### Levier 2 : Accélérer les encaissements clients\n- Facturez immédiatement à la livraison\n- Proposez un escompte pour paiement rapide\n- Relancez dès le premier jour de retard\n- Mobile Money = encaissement immédiat\n\n**Ratio :** Délai clients = (Créances / CA TTC) × 360 → Objectif : < 30 jours\n\n### Levier 3 : Négocier de meilleures conditions fournisseurs\n- Négociez 60-90 jours avec vos principaux fournisseurs\n\n**Ratio :** Délai fournisseurs = (Dettes fournisseurs / Achats TTC) × 360 → Objectif : > 45 jours'),

  (v_mod6, v_course_id, 'Financement court terme et gestion de la trésorerie quotidienne', 'document', 2, false,
   E'# Financement Court Terme et Trésorerie Quotidienne\n\n## Les instruments disponibles en Afrique\n\n### 1. Le découvert bancaire\n**Coût :** 12 à 18%/an + commission de dépassement\n**Usage :** Décalages de trésorerie ponctuels\n\n### 2. L''escompte commercial\n**Principe :** Remettez vos effets de commerce à la banque qui vous paie immédiatement.\n**Coût :** 4-8%/an\n\n### 3. Le factor (affacturage)\n**Principe :** Une société achète vos créances et vous paie immédiatement (80-90%).\n**Coût :** 1-3% du montant\n**Avantage :** Transfert du risque d''impayé\n\n### 4. Mobile Money professionnel\nOrange Money Business, MTN Business, Wave Business :\n- Réception immédiate des paiements\n- Virements instantanés\n- Extrait de compte pour votre comptable\n\n## La règle de l''encaisse de sécurité\n\nConservez toujours **15 jours de charges fixes** en trésorerie disponible.\n\n```\nEx : Charges fixes = 6 000 000 XOF/mois\nEncaisse sécurité = 6 000 000 × 15/30 = 3 000 000 XOF\n```\n\n## Placer les excédents\n- **Compte à terme (CAT)** : 3-5%/an, capital garanti\n- **Bons du Trésor** : 5-7%/an selon durée'),

  -- Module 7 : Fiscalité
  (v_mod7, v_course_id, 'TVA et obligations fiscales mensuelles des PME', 'document', 1, false,
   E'# TVA et Obligations Fiscales Mensuelles\n\n## La TVA en zone OHADA/UEMOA\n\n```\nTVA à payer = TVA collectée - TVA déductible\n```\n\n### Taux de TVA par pays\n| Pays | Taux normal |\n|------|------------|\n| Côte d''Ivoire | 18% |\n| Sénégal | 18% |\n| Cameroun | 19,25% |\n| Mali | 18% |\n| Bénin | 18% |\n\n## Le calendrier fiscal mensuel\n\n| Obligation | Échéance | Pénalité si retard |\n|-----------|----------|--------------------|\n| Déclaration TVA | 15-20 du mois suivant | 10-25% + intérêts |\n| Retenue IRPP salaires | 15 du mois suivant | 10% |\n\n## Exemple de déclaration TVA (Côte d''Ivoire)\n\n```\nCA janvier : 10 000 000 XOF HT\nTVA collectée (18%) : 1 800 000 XOF\n\nAchats HT : 6 000 000 XOF\nTVA déductible (18%) : 1 080 000 XOF\n\nTVA nette à payer = 1 800 000 - 1 080 000 = 720 000 XOF\n```\n\nCette somme doit être versée à la DGI avant le 20 février.\n\n## Éviter les problèmes fiscaux\n1. Gardez tous les justificatifs pendant 10 ans\n2. Facturez correctement (numéro NIF, mentions obligatoires)\n3. Collaborez avec votre DGI en cas de difficulté\n4. Faites-vous accompagner par un expert-comptable'),

  (v_mod7, v_course_id, 'Impôt sur les bénéfices et optimisation fiscale légale', 'document', 2, false,
   E'# Impôt sur les Bénéfices et Optimisation Fiscale\n\n## Taux d''IS en zone OHADA\n| Pays | Taux IS | Taux minimum forfaitaire |\n|------|---------|-------------------------|\n| Côte d''Ivoire | 25% | 0,5% du CA |\n| Sénégal | 30% | 0,5% du CA |\n| Cameroun | 33% | 2,2% du CA |\n| Mali | 30% | 0,75% du CA |\n\n**Le minimum forfaitaire** est dû même en cas de perte !\n\n## Calcul de l''IS\n\n```\nRésultat comptable\n+ Réintégrations (charges non déductibles)\n- Déductions fiscales\n= Résultat fiscal\n× Taux IS\n- Acomptes déjà versés\n= IS restant à payer\n```\n\n## Optimisation fiscale LÉGALE\n\n### 1. Maximiser les amortissements\nCertains pays autorisent l''amortissement accéléré sur les équipements.\n\n### 2. Les provisions\n- Provision pour créances douteuses (clients en retard >6 mois)\n- Provision pour dépréciation des stocks\n\n### 3. Les charges de personnel\nSalaires, charges sociales, formations sont entièrement déductibles.\n\n### 4. Les zones franches\n- **CI :** Zone Franche Industrielle d''Abidjan (5-8 ans d''exonération)\n- **Sénégal :** Statut d''entreprise franche d''exportation\n\n**⚠️ Important :** L''optimisation fiscale est légale. L''évasion fiscale est un délit.');

END $$;


-- ============================================================
-- FORMATION 6 : Communication Professionnelle et Prise de Parole
-- ============================================================
DO $$ DECLARE
  v_course_id uuid;
  v_mod5 uuid; v_mod6 uuid; v_mod7 uuid;
  v_max_pos int;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'communication-professionnelle-prise-de-parole';
  SELECT COALESCE(MAX(position), 0) INTO v_max_pos FROM modules WHERE course_id = v_course_id;

  INSERT INTO modules (course_id, title, position) VALUES
    (v_course_id, 'Négociation et Influence Interculturelle en Afrique', v_max_pos + 1),
    (v_course_id, 'Communication de Crise et Gestion des Situations Difficiles', v_max_pos + 2),
    (v_course_id, 'Communication Digitale et Personal Branding Professionnel', v_max_pos + 3);

  SELECT id INTO v_mod5 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos LIMIT 1;
  SELECT id INTO v_mod6 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 1 LIMIT 1;
  SELECT id INTO v_mod7 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 2 LIMIT 1;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES

  (v_mod5, v_course_id, 'Les fondamentaux de la négociation en contexte africain', 'document', 1, false,
   E'# Négociation en Contexte Africain\n\n## Les caractéristiques de la négociation africaine\n\n**1. La relation précède la transaction**\nEn Afrique : on crée la relation, puis on négocie.\nInvestissez dans des repas et rencontres informelles avant toute négociation importante.\n\n**2. Le temps est circulaire, pas linéaire**\nImpatienter une contrepartie en cherchant à "aller vite" est contre-productif.\n\n**3. L''harmonie du groupe prévaut**\nVotre interlocuteur doit souvent consulter ses supérieurs, sa communauté. Respectez ce processus.\n\n## La méthode BATNA\n\n**Avant toute négociation :**\n1. Votre BATNA : que se passe-t-il si cette négociation échoue ?\n2. Le BATNA de l''autre partie : quelle est leur alternative ?\n\nCelui qui a la meilleure alternative a le plus de pouvoir.\n\n## Le processus en 6 étapes\n\n1. **Préparation** : objectif idéal, point de rupture, arguments\n2. **Ouverture** : atmosphère positive, échanges personnels\n3. **Exploration** : écouter plus que parler, questions ouvertes\n4. **Proposition** : présentez votre offre comme un bénéfice pour l''autre\n5. **Négociation** : chaque concession obtient une concession\n6. **Accord** : résumer à voix haute, mettre par écrit, célébrer'),

  (v_mod5, v_course_id, 'Techniques d''influence et de persuasion éthique', 'document', 2, false,
   E'# Influence et Persuasion Éthique\n\n## Les 6 principes d''influence de Cialdini\n\n### 1. La Réciprocité\nEn Afrique, la réciprocité (djembe, ubuntu, teranga) est une valeur fondamentale.\n**Application :** Partagez des informations utiles avant de demander quelque chose.\n\n### 2. L''Autorité\n**Construire votre autorité :**\n- Titres et certifications\n- Témoignages de clients reconnus\n- Publications et prises de position\n\n### 3. La Preuve sociale\n"Si Monsieur Koné fait confiance à cette entreprise, elle est sérieuse."\n\n### 4. La Rareté\n- Groupe limité (max 20 participants)\n- Offre valable jusqu''à une date réelle\n\n### 5. La Sympathie\nExplorez les points communs : ville d''origine, école, religion, sport.\n\n### 6. L''Engagement et Cohérence\n**Technique du pied dans la porte :**\nCommencez par des petites demandes → la personne sera plus encline à accepter une demande plus grande.\n\n## Éthique de l''influence\nL''influence devient manipulation quand elle exploite les faiblesses, crée de la peur ou de la culpabilité.\n\nUne réputation bâtie sur la manipulation s''effondre toujours.'),

  (v_mod5, v_course_id, 'Mener des négociations commerciales gagnant-gagnant', 'document', 3, false,
   E'# Négociations Commerciales Gagnant-Gagnant\n\n## Distinguer positions et intérêts\n\n**Exemple classique :**\nDeux sœurs se disputent la dernière orange.\n- Intérêt sœur A : elle veut le jus pour son cocktail\n- Intérêt sœur B : elle veut l''écorce pour son gâteau\n- Solution : les deux sont 100% satisfaites\n\n**Application commerciale :**\nVotre client veut un prix plus bas. Son intérêt réel : réduire son coût global. Vous pouvez maintenir votre prix en ajoutant de la valeur (formation, garantie étendue, livraison incluse).\n\n## La matrice de concessions\n\n| Concession | Coût pour moi | Valeur pour l''autre |\n|------------|--------------|---------------------|\n| Délai 60 jours | Faible | Élevée |\n| Formation incluse | Faible | Élevée |\n| Remise 5% | Moyen | Moyen |\n| Remise 15% | Élevé | Moyen |\n\n**Règle :** Commencez par les concessions à faible coût pour vous mais haute valeur pour l''autre.\n\n## Technique de la négociation par paquets\nNe négociez jamais un point à la fois. Mettez sur la table simultanément : prix, quantité, délais, modalités de paiement, services inclus, durée du contrat.'),

  -- Module 6 : Communication de crise
  (v_mod6, v_course_id, 'Gérer une crise de communication en entreprise africaine', 'document', 1, false,
   E'# Communication de Crise\n\n## La règle des premières 24 heures\n\n**H+1 :** Activer la cellule de crise\n**H+2 :** Évaluer les faits disponibles\n**H+4 :** Première communication externe\n**H+24 :** Communication complète avec explication et mesures\n\n## Les 3 C de la communication de crise\n\n### Compassion\n"Nos premières pensées vont aux personnes touchées par cet incident."\n\n### Compétence\n"Notre équipe de crise est mobilisée 24h/24. Voici les mesures immédiates prises..."\n\n### Cohérence\nUn message unique, une voix unique. **Nommez un porte-parole unique** pour toute la durée de la crise.\n\n## Gérer les réseaux sociaux en crise\n\n1. **Monitorez** en continu\n2. **Ne supprimez pas** les commentaires négatifs\n3. **Répondez** à chaque commentaire\n4. **Reconnaissez** les faits vrais, corrigez les faux\n5. **Publiez** des mises à jour régulières\n\n## Ce qu''il ne faut JAMAIS faire\n1. Mentir ou minimiser\n2. Pratiquer le "no comment"\n3. Se précipiter sur des explications incomplètes\n4. Oublier d''informer les employés en interne\n5. Attaquer les journalistes ou lanceurs d''alerte'),

  -- Module 7 : Communication digitale
  (v_mod7, v_course_id, 'Construire votre personal branding professionnel en Afrique', 'document', 1, false,
   E'# Personal Branding Professionnel en Afrique\n\n## Les 3 piliers\n\n### Pilier 1 : La clarté de votre positionnement\n**Votre phrase clé :** "Je suis [titre] qui aide [cible] à [résultat] grâce à [compétence]."\n\nExemple : "Je suis consultant en marketing digital qui aide les PME africaines à doubler leur clientèle en ligne."\n\n### Pilier 2 : Votre présence LinkedIn\n\n**Optimisation du titre :**\n❌ "Responsable Marketing chez XYZ"\n✅ "Expert Marketing Digital | J''aide les PME africaines à croître en ligne | +15M XOF de CA généré"\n\n**Publication régulière (2-3 fois/semaine) :**\n- Expériences professionnelles avec leçon apprise\n- Points de vue sur l''actualité de votre secteur\n- Conseils pratiques pour votre audience\n\n### Pilier 3 : Vos prises de parole publiques\n- Conférences et panels\n- Articles et tribunes\n- Podcasts\n- Webinaires\n\n## Construire votre réseau en Afrique\n\n**La règle du 10-5-1 :**\n- 10 personnes de votre secteur à suivre chaque semaine\n- 5 professionnels à rencontrer chaque mois\n- 1 mentor ou relation stratégique à cultiver chaque trimestre\n\n**Associations recommandées (Côte d''Ivoire) :**\n- CIE (Chambre de Commerce)\n- Club des Dirigeants\n- Lions Club, Rotary\n- Alumni de votre université');

END $$;


-- ============================================================
-- FORMATION 7 : Ressources Humaines
-- ============================================================
DO $$ DECLARE
  v_course_id uuid;
  v_mod5 uuid; v_mod6 uuid; v_mod7 uuid;
  v_max_pos int;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'ressources-humaines-recruter-former-fideliser';
  SELECT COALESCE(MAX(position), 0) INTO v_max_pos FROM modules WHERE course_id = v_course_id;

  INSERT INTO modules (course_id, title, position) VALUES
    (v_course_id, 'Droit du Travail en Zone OHADA et UEMOA', v_max_pos + 1),
    (v_course_id, 'Rémunération, Avantages Sociaux et Motivation', v_max_pos + 2),
    (v_course_id, 'Digitalisation RH et SIRH pour PME Africaines', v_max_pos + 3);

  SELECT id INTO v_mod5 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos LIMIT 1;
  SELECT id INTO v_mod6 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 1 LIMIT 1;
  SELECT id INTO v_mod7 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 2 LIMIT 1;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES

  (v_mod5, v_course_id, 'Le contrat de travail en droit OHADA : types et clauses essentielles', 'document', 1, false,
   E'# Le Contrat de Travail en Droit OHADA\n\n## Les types de contrats\n\n### 1. Contrat à Durée Indéterminée (CDI)\nLe contrat de référence, le plus protecteur pour le salarié.\n\n**Période d''essai (Côte d''Ivoire) :**\n- Cadres : 3 mois renouvelable une fois\n- Agents de maîtrise : 2 mois\n- Employés et ouvriers : 1 mois\n\n### 2. Contrat à Durée Déterminée (CDD)\nRéservé aux cas précis :\n- Remplacement d''un salarié absent\n- Accroissement temporaire d''activité\n- Travaux saisonniers\n\n**⚠️ Attention :** Utiliser un CDD pour un emploi permanent → requalification en CDI par les tribunaux.\n\n### 3. Contrat de prestation de services\nPour les freelances/consultants. Pas de protection du Code du Travail.\n\n## Les clauses essentielles\n\n### Mentions obligatoires\n- Identité des parties\n- Poste / qualification\n- Rémunération\n- Durée du travail\n- Période d''essai\n\n### Clauses optionnelles importantes\n- **Confidentialité :** obligatoire pour les postes stratégiques\n- **Non-concurrence :** doit prévoir une contrepartie financière, être limitée dans le temps et l''espace\n- **Mobilité :** autorise l''employeur à muter le salarié'),

  (v_mod5, v_course_id, 'Gérer les congés, absences et licenciements selon le droit africain', 'document', 2, false,
   E'# Congés, Absences et Ruptures du Contrat\n\n## Les congés payés (Côte d''Ivoire)\n- **Acquisition :** 2,5 jours ouvrables par mois\n- **Droit plein :** 30 jours ouvrables après 12 mois\n- **Majoration ancienneté :** +1 jour/an après 5 ans\n\n## Les absences\n\n| Type | Justificatif | Rémunéré ? |\n|------|-------------|------------|\n| Maladie | Certificat médical | Selon ancienneté |\n| Accident du travail | Déclaration + certificat | Oui (CNPS) |\n| Maternité | Certificat médical | Oui (CNPS) |\n| Événements familiaux | Pièces justificatives | Oui (3-5 jours) |\n\n## L''échelle des sanctions\n1. Avertissement verbal\n2. Avertissement écrit\n3. Mise à pied disciplinaire\n4. Licenciement pour faute\n\n## Procédure de licenciement\n1. **Convocation** à un entretien préalable (5 jours minimum avant)\n2. **Entretien préalable**\n3. **Délai de réflexion** (3 jours ouvrables)\n4. **Notification** par lettre recommandée\n5. **Préavis** à exécuter ou indemniser\n6. **Paiement** des indemnités + solde de tout compte\n\n## Calcul des indemnités (Côte d''Ivoire)\n\n```\n1ère à 5ème année : 20%/an × salaire mensuel moyen\n6ème à 10ème année : 25%/an\n11ème et au-delà : 30%/an\n\nExemple : 8 ans d''ancienneté, salaire 300 000 XOF\n5 premières années : 5 × 20% × 300 000 = 300 000 XOF\n6ème à 8ème : 3 × 25% × 300 000 = 225 000 XOF\nTotal : 525 000 XOF\n```'),

  (v_mod5, v_course_id, 'La CNPS et la protection sociale des salariés en Afrique', 'document', 3, false,
   E'# CNPS et Protection Sociale\n\n## Les prestations de la CNPS (Côte d''Ivoire)\n\n- **Accidents du travail :** prise en charge médicale complète + indemnités journalières\n- **Allocations familiales :** prénatale, maternité, pour chaque enfant < 14 ans\n- **Retraite :** 60 ans + 15 ans de cotisations minimum\n\n## Cotisations CNPS (Côte d''Ivoire)\n\n| Branche | Taux employeur | Taux salarié |\n|---------|---------------|-------------|\n| Retraite | 7,7% | 6,3% |\n| Allocations familiales | 5,75% | 0% |\n| Accidents du travail | 2-5% | 0% |\n| **Total** | **~16%** | **6,3%** |\n\n```\nExemple pour salaire brut de 500 000 XOF :\nCotisation employeur : 500 000 × 16% = 80 000 XOF\nCotisation salarié : 500 000 × 6,3% = 31 500 XOF\nTotal CNPS à verser : 111 500 XOF\n```\n\n## Protection sociale complémentaire\n\nPour attirer les talents :\n- **Assurance maladie complémentaire** : 15 000 à 50 000 XOF/mois/salarié\n- **Prévoyance décès-invalidité**\n- **Complémentaire retraite**'),

  -- Module 6 : Rémunération
  (v_mod6, v_course_id, 'Concevoir une politique de rémunération attractive et équitable', 'document', 1, false,
   E'# Politique de Rémunération\n\n## Les composantes de la rémunération globale\n\n### 1. Rémunération directe\n- Salaire fixe\n- Variable individuel (prime sur objectifs)\n- Variable collectif (participation aux bénéfices)\n- Primes exceptionnelles\n\n### 2. Avantages en nature\n- Véhicule de fonction ou allocation transport\n- Logement ou allocation logement\n- Téléphone / PC portable\n\n### 3. Avantages non monétaires\n- Formation et développement professionnel\n- Flexibilité des horaires\n- Télétravail\n\n## La grille salariale : 3 étapes\n\n### Étape 1 : Classification des postes\n- Niveau 1 : Exécution (opérateurs, agents)\n- Niveau 2 : Qualifiés (techniciens confirmés)\n- Niveau 3 : Maîtrise (superviseurs)\n- Niveau 4 : Cadres (responsables de département)\n- Niveau 5 : Cadres supérieurs (directeurs)\n\n### Étape 2 : Benchmarking salarial\n- Enquêtes salariales sectorielles (CGECI, cabinets RH)\n- Offres d''emploi concurrentes\n\n### Étape 3 : Définir des fourchettes\n```\nNiveau 3 (Maîtrise) : 250 000 - 350 000 - 450 000 XOF\n                       (débutant)  (confirmé) (senior)\n```\n\n## Structure de primes de performance recommandée\n\n```\nRéalisation 80-89% : prime 25 000 XOF\nRéalisation 90-99% : prime 40 000 XOF\nRéalisation 100% : prime 50 000 XOF\nRéalisation 110%+ : prime 65 000+ XOF\n```'),

  (v_mod6, v_course_id, 'Fidéliser les talents : au-delà du salaire', 'document', 2, false,
   E'# Fidéliser les Talents en Afrique\n\n## Le coût du turnover\n\nRemplacer un collaborateur coûte **3 à 6 mois de salaire** en comptant :\n- Coût du recrutement\n- Coût de la vacance du poste\n- Coût de la formation du remplaçant\n- Perte de productivité pendant la montée en compétences\n\n## Ce qui fait vraiment rester (étude PwC Afrique)\n\n1. **Manque de perspectives d''évolution** (54%)\n2. **Mauvaise relation avec le manager** (38%)\n3. **Ambiance et culture** (35%)\n4. **Salaire insuffisant** (31%)\n5. **Manque de reconnaissance** (28%)\n\n## Les 5 leviers de fidélisation\n\n### 1. Les perspectives de carrière\n- Plan de carrière individuel à 3-5 ans\n- Mobilité interne prioritaire\n\n### 2. La qualité du management\n"Les collaborateurs quittent leur manager, pas leur entreprise."\n\n### 3. La reconnaissance non financière\n- Remerciement personnel dans les 24h\n- Félicitations en public\n- Sponsoring d''une formation de leur choix\n\n### 4. Les conditions de travail (basiques africains)\n- Climatisation correcte\n- Eau potable disponible\n- Transports facilités\n- Repas du midi\n\n### 5. Le sens et la culture\n- Mission qui dépasse le profit\n- Implication dans les décisions'),

  -- Module 7 : SIRH
  (v_mod7, v_course_id, 'SIRH : choisir et mettre en place un logiciel RH pour PME', 'document', 1, false,
   E'# SIRH pour PME Africaines\n\n## Pourquoi digitaliser les RH ?\n\n**Avant le SIRH :** fiches de paie Excel avec erreurs, suivi des congés sur papier, dossiers en classeurs.\n\n**Après le SIRH :** paie calculée automatiquement, demandes de congés en ligne, dossiers numériques accessibles en 2 clics.\n\n## Logiciels adaptés aux PME africaines\n\n**Sage Paie (Afrique)**\n- Paramétré pour les codes du travail africains (CI, Sénégal, Cameroun)\n- Interface en français\n- **Coût :** 200 000 - 500 000 XOF/an\n\n**Odoo RH (open source)**\n- Module RH complet, personnalisable\n- **Coût :** gratuit + coût d''implémentation\n\n**Eurécia**\n- SIRH cloud adapté pour l''Afrique francophone\n- **Coût :** ~5 000 XOF/salarié/mois\n\n## Déployer un SIRH en 4 phases\n\n1. **Phase 1 (Mois 1-2) :** Audit, collecte des données, paramétrage\n2. **Phase 2 (Mois 3) :** Formation + déploiement pilote\n3. **Phase 3 (Mois 4-5) :** Déploiement général + double vérification\n4. **Phase 4 (Mois 6+) :** Optimisation et tableaux de bord\n\n## Le self-service salarié\n\nDonnez accès à :\n- Bulletins de salaire en ligne\n- Solde de congés en temps réel\n- Demande de congés en ligne\n- Documents RH (contrat, avenants)\n\n**Résultat :** -60% de sollicitations administratives');

END $$;


-- ============================================================
-- FORMATION 8 : E-commerce et Vente en Ligne en Afrique
-- ============================================================
DO $$ DECLARE
  v_course_id uuid;
  v_mod5 uuid; v_mod6 uuid; v_mod7 uuid;
  v_max_pos int;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'ecommerce-vente-en-ligne-afrique';
  SELECT COALESCE(MAX(position), 0) INTO v_max_pos FROM modules WHERE course_id = v_course_id;

  INSERT INTO modules (course_id, title, position) VALUES
    (v_course_id, 'Logistique et Livraison : Le Défi n°1 du E-commerce Africain', v_max_pos + 1),
    (v_course_id, 'Service Client Digital et Gestion des Avis', v_max_pos + 2),
    (v_course_id, 'Analytics E-commerce et Croissance du Chiffre d''Affaires', v_max_pos + 3);

  SELECT id INTO v_mod5 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos LIMIT 1;
  SELECT id INTO v_mod6 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 1 LIMIT 1;
  SELECT id INTO v_mod7 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 2 LIMIT 1;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES

  (v_mod5, v_course_id, 'Maîtriser la logistique de livraison en Afrique', 'document', 1, false,
   E'# Logistique E-commerce en Afrique\n\n## Les défis logistiques africains\n- Adresses postales inexistantes ou imprécises\n- Coût de livraison élevé relatif au panier moyen\n- Taux de retour élevé (paiement à la livraison dominant)\n\n## Les modèles de livraison\n\n### 1. Livraison en propre\n**Recommandé si :** > 30 commandes/jour dans votre ville.\n\n### 2. Partenaires logistiques (Côte d''Ivoire)\n- **Jumia Logistics :** livraison nationale\n- **Glovo / Yango Delivery :** express même le jour J\n- **DHL Afrique :** cross-border (exportation)\n\n### 3. Points relais\nRéseau de boutiques partenaires où les clients récupèrent leurs commandes.\n- Coût réduit de 30-50%\n- Taux d''échec quasi nul\n- Commission : 500-1000 XOF/colis\n\n## Gérer le paiement à la livraison (PAL)\n\nEn Afrique, **60-80% des achats e-commerce** sont payés à la livraison.\n\n**Comment réduire le taux de refus (15-25% en moyenne) :**\n1. **Confirmation téléphonique** avant chaque livraison\n2. **Délai de livraison court** : < 48h\n3. **Politique de retour claire** : "Satisfait ou remboursé"\n\n## Métriques logistiques\n\n| Métrique | Objectif |\n|----------|----------|\n| Taux de livraison réussie | > 85% |\n| Délai moyen | < 3 jours |\n| Taux de refus PAL | < 15% |\n| Coût logistique / CA | < 8% |'),

  (v_mod5, v_course_id, 'Vendre sur les marketplaces africaines : Jumia, Glovo et autres', 'document', 2, false,
   E'# Vendre sur les Marketplaces Africaines\n\n## L''écosystème des marketplaces\n\n### Jumia — Le leader continental\n**Présence :** CI, Sénégal, Nigeria, Kenya, Ghana, Maroc...\n**Commissions :** 5% à 25% selon catégorie\n\n**Comment vendre :**\n1. Inscription Jumia Seller\n2. Vérification des documents (registre commerce, NIF)\n3. Création des fiches produits\n4. Jumia gère le paiement et vous reverse toutes les 2 semaines\n\n### WhatsApp Business Catalog\nParfait pour les petites structures sans site web :\n- Catalogue de produits dans WhatsApp\n- Commande par WhatsApp, paiement mobile money\n\n## Stratégie multicanale recommandée\n\n**Phase 1 (Démarrage) :** WhatsApp + Instagram — coût zéro\n**Phase 2 (Croissance) :** + Jumia + Site propre\n**Phase 3 (Maturité) :** Omnicanal intégré\n\n## Optimiser vos fiches produits\n\n**Titre :**\n❌ "Chaussure femme"\n✅ "Chaussure Talon Bloc Femme — Cuir Synthétique — 7cm — Noir/Bordeaux — Taille 36-41"\n\n**Photos :** minimum 5, fond blanc pour la principale, produit porté, détails gros plan.\n\n**Description :** bénéfices avant caractéristiques, répondre aux questions fréquentes.'),

  -- Module 6 : Service client
  (v_mod6, v_course_id, 'Construire un service client e-commerce d''excellence', 'document', 1, false,
   E'# Service Client E-commerce d''Excellence\n\n## WhatsApp Business — Canal prioritaire en Afrique\n\n**Configuration indispensable :**\n- Message de bienvenue automatique\n- Réponses rapides (templates pour questions fréquentes)\n- Étiquettes : Nouveau client, En attente, Résolu, VIP\n\n**Temps de réponse visé :** < 15 minutes\n\n**Templates de réponses rapides :**\n```\n/livraison → "Votre commande sera livrée dans [X] heures. Notre livreur vous appellera avant passage."\n\n/retour → "Retours acceptés sous 7 jours. Produit non utilisé, dans son emballage. Envoyez-nous une photo + votre numéro de commande."\n```\n\n## Gérer les situations difficiles\n\n### Le client insatisfait\n```\nÉtape 1 : Reconnaître SANS se justifier\n"Je comprends votre déception et je m''en excuse sincèrement."\n\nÉtape 2 : Proposer une solution IMMÉDIATE\n"Voici ce que je vous propose : [remboursement / échange]"\n\nÉtape 3 : Agir VITE (dans les 24h)\nÉtape 4 : Suivre (recontacter 48h après)\n```\n\n### Le client agressif sur les réseaux\n- Sortir de la confrontation publique : "Pouvez-vous nous contacter en DM ?"\n- Ne jamais supprimer un commentaire négatif\n\n## Mesurer la satisfaction : NPS\n**Question :** "Sur une échelle de 0 à 10, recommanderiez-vous notre boutique à un ami ?"\n\n```\nNPS = % Promoteurs (9-10) - % Détracteurs (0-6)\nNPS > 50 : Excellent\n```'),

  -- Module 7 : Analytics
  (v_mod7, v_course_id, 'Analytics e-commerce : optimiser votre taux de conversion', 'document', 1, false,
   E'# Analytics E-commerce et Optimisation des Conversions\n\n## Les métriques fondamentales\n\n### 1. Taux de conversion (CR)\n```\nCR = (Commandes / Visiteurs) × 100\nBenchmark Afrique : 1-3%\n```\n\n### 2. Valeur Moyenne de Commande (AOV)\n```\nAOV = CA total / Nombre de commandes\n```\n**Stratégies pour augmenter :** upsell, cross-sell, bundle, livraison gratuite à partir d''un seuil\n\n### 3. Customer Lifetime Value (CLV)\n```\nCLV = AOV × Fréquence d''achat × Durée de rétention\n```\n\n### 4. Coût d''Acquisition Client (CAC)\n```\nCAC = Dépenses marketing / Nouveaux clients\nRègle : CAC < CLV/3\n```\n\n## Optimiser le tunnel de conversion\n\n```\nVisiteur → Page produit → Panier → Checkout → Commande\n  1000        600          300       150         15\n```\n\n## Récupération des paniers abandonnés (automatisation)\n- **H+1 :** WhatsApp "Vous avez oublié quelque chose dans votre panier"\n- **H+24 :** Email avec photo du produit\n- **H+48 :** Offre spéciale (-5% ou livraison gratuite)\n\n## Outils analytics recommandés\n- **Google Analytics 4 :** comportement visiteurs\n- **Meta Pixel :** tracking conversions Facebook/Instagram\n- **Hotjar :** heatmaps, enregistrements de sessions\n\n## Tests A/B\n- Bouton vert vs bouton orange\n- "Acheter maintenant" vs "Ajouter au panier"\n- Prix rond vs prix psychologique (14 900 vs 15 000 XOF)\n\n**Durée minimale :** 2 semaines, 500 visiteurs par version.');

END $$;


-- ============================================================
-- FORMATION 9 : Intelligence Artificielle & Outils IA
-- ============================================================
DO $$ DECLARE
  v_course_id uuid;
  v_mod5 uuid; v_mod6 uuid; v_mod7 uuid;
  v_max_pos int;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'intelligence-artificielle-outils-ia-professionnels';
  SELECT COALESCE(MAX(position), 0) INTO v_max_pos FROM modules WHERE course_id = v_course_id;

  INSERT INTO modules (course_id, title, position) VALUES
    (v_course_id, 'IA et Productivité Avancée : Automatiser son Travail avec l''IA', v_max_pos + 1),
    (v_course_id, 'IA pour Entrepreneurs Africains : Applications Concrètes', v_max_pos + 2),
    (v_course_id, 'Éthique de l''IA, Biais et Futur du Travail en Afrique', v_max_pos + 3);

  SELECT id INTO v_mod5 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos LIMIT 1;
  SELECT id INTO v_mod6 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 1 LIMIT 1;
  SELECT id INTO v_mod7 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos + 2 LIMIT 1;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES

  (v_mod5, v_course_id, 'Maîtriser le prompt engineering pour des résultats professionnels', 'document', 1, false,
   E'# Prompt Engineering Avancé\n\n## Pourquoi les prompts font toute la différence\n\n**Règle fondamentale :** L''IA est comme un consultant brillant qui n''a aucun contexte sur votre situation. Plus vous lui en donnez, meilleur sera le résultat.\n\n## La structure TRACI du prompt parfait\n\n### T — Tâche\n❌ "Aide-moi avec mon marketing"\n✅ "Rédige 3 accroches publicitaires pour Facebook Ads"\n\n### R — Rôle\n"Tu es un expert en marketing digital spécialisé dans les PME africaines avec 15 ans d''expérience..."\n\n### A — Audience\n"...pour des commerçants ivoiriens de 35-50 ans, peu familiers du digital..."\n\n### C — Contexte\n"...Je vends des condiments artisanaux bio à Abidjan. Prix : 3500 XOF..."\n\n### I — Instructions de format\n"...Maximum 125 caractères par accroche. Inclus un emoji. Ton chaleureux."\n\n## Techniques avancées\n\n### Chain of thought\n```\nAvant de répondre, réfléchis étape par étape :\n1. Analyse la situation\n2. Identifie les contraintes\n3. Génère plusieurs options\n4. Choisis la meilleure avec justification\n```\n\n### L''itération\n1. Premier prompt → résultat de base\n2. "C''est bien, mais rends-le plus [adjectif]"\n3. "Refais la 3ème option en version plus courte"\n4. "Combine les meilleures parties du 1 et du 3"'),

  (v_mod5, v_course_id, 'Automatiser ses tâches avec Make, Zapier et les API IA', 'document', 2, false,
   E'# Automatisation avec Make et Zapier\n\n## Principe\n**Si [événement A] se produit dans l''application X, alors [action B] dans l''application Y.**\n\n## Make vs Zapier\n\n| Critère | Make | Zapier |\n|---------|------|--------|\n| Prix | 9$/mois | 20$/mois |\n| Complexité | Plus technique | Plus simple |\n| Apps disponibles | 1000+ | 5000+ |\n| **Recommandé pour** | Besoins complexes | Débutants |\n\n## Automatisations essentielles pour PME africaines\n\n### 1. Automatisation des leads\n```\nFormulaire Google soumis\n→ Ajouter dans HubSpot CRM\n→ Envoyer WhatsApp de bienvenue\n→ Créer tâche "Rappel" dans 24h\n→ Notifier le commercial\n```\n\n### 2. Automatisation des commandes\n```\nNouvelle commande WooCommerce\n→ Email + WhatsApp de confirmation client\n→ Réduire le stock dans Google Sheets\n→ Créer bon de préparation\n→ Si stock < 5 → alerter le responsable\n```\n\n## Intégrer l''IA dans vos automatisations\n\n```\nEmail client reçu dans Gmail\n→ Analyser avec GPT-4 :\n  "S''agit-il d''un support, une commande ou une plainte ?"\n→ Si "plainte" → alerter le responsable SAV\n→ Si "commande" → créer dans le CRM\n→ Si "support" → assigner à l''équipe\n```\n\n## Créer votre premier scénario Make\n\n1. Créer un compte sur make.com (gratuit)\n2. Choisir l''application déclencheur (ex : Google Forms)\n3. Ajouter un module action (ex : Gmail)\n4. Tester avec un vrai exemple\n5. Activer le scénario\n\n**Temps de configuration :** 30-60 minutes pour un scénario simple'),

  (v_mod5, v_course_id, 'Créer du contenu professionnel avec les outils IA', 'document', 3, false,
   E'# Créer du Contenu Professionnel avec l''IA\n\n## Les outils IA de création\n\n### Texte et Rédaction\n- **ChatGPT** : articles, emails, rapports, code, formules Excel\n- **Claude** : analyse approfondie, rédaction nuancée, documents longs\n- **Gemini** : intégré à Gmail/Google Docs, recherche web en temps réel\n\n### Image et Design\n- **Canva IA** : visuels marketing, retouche photo, suppression d''arrière-plan — disponible en Afrique, version gratuite\n- **Adobe Firefly** : images professionnelles\n\n### Vidéo\n- **Synthesia** : vidéos avec avatar IA — idéal pour formations en ligne\n- **CapCut IA** : sous-titres automatiques, très populaire en Afrique (gratuit)\n\n## Workflow : 1 mois de contenu en 1 journée\n\n**Étape 1 (1h) : Brainstorming avec IA**\n```\nPrompt : "Je suis [expert en X]. Génère 20 idées de contenu LinkedIn pour [mon audience]. Mix : 40% conseils pratiques, 30% stories, 20% actualité, 10% questions."\n```\n\n**Étape 2 (2h) :** Rédiger les 8-10 meilleurs posts avec l''IA + révision humaine\n\n**Étape 3 (1h) :** Créer les visuels avec Canva IA\n\n**Étape 4 (30min) :** Programmer avec Buffer / Later\n\n## Garder votre voix humaine\n\nCe qui vous rend unique vs l''IA :\n- **Vos expériences personnelles** (anecdotes vraies)\n- **Votre contexte local** (exemples africains)\n- **Votre opinion** (l''IA hésite à prendre position)\n- **Votre réseau** (mentionnez des personnes réelles)\n\n**Règle d''or :** L''IA génère le premier jet, vous finissez.'),

  -- Module 6 : IA pour entrepreneurs
  (v_mod6, v_course_id, 'IA pour la gestion commerciale et la relation client', 'document', 1, false,
   E'# IA pour la Gestion Commerciale\n\n## Chatbots IA : votre commercial/support 24h/24\n\n### Créer un chatbot IA pour votre entreprise\n\n**ManyChat (pour WhatsApp/Instagram/Messenger)**\n- Automatise les conversations WhatsApp Business\n- Envoi de catalogues, prise de commandes\n- **Coût :** 15$/mois\n\n**Tidio (pour site web)**\n- GPT-4 intégré, répond aux questions sur vos produits\n- **Coût :** ~29$/mois\n\n### Ce que votre chatbot doit faire\n1. Accueillir et qualifier les prospects\n2. Répondre aux FAQ (prix, horaires, délais)\n3. Prendre des rendez-vous (intégration Calendly)\n4. Escalader vers un humain si besoin\n\n## Prompts IA pour l''analyse commerciale\n\n**Analyser vos ventes :**\n```\nVoici mes données des 6 derniers mois : [tableau].\nAnalyse :\n1. Les 3 tendances principales\n2. Les produits sous-performants\n3. Les patterns saisonniers\n4. 3 recommandations pour le prochain trimestre\n```\n\n**Préparer votre pitch :**\n```\nJe dois pitcher [service X] à [type de client] qui a comme problèmes [Y et Z]. Durée : 5 minutes.\nRédige un pitch en 3 parties : accroche, problème + solution, appel à l''action.\n```\n\n**Relancer des prospects :**\n```\nJ''ai rencontré [type de prospect] lors de [événement] il y a [durée]. Rédige un email de relance chaleureux qui rouvre la conversation sans être intrusif.\n```'),

  (v_mod6, v_course_id, 'IA pour l''agriculture, la santé et l''éducation en Afrique', 'document', 2, false,
   E'# Applications IA dans les Secteurs Clés Africains\n\n## Agriculture\n\n**Plantix (application mobile)**\n- Photo d''une plante malade → diagnostic IA + traitement recommandé\n- Gratuit, disponible en français\n\n**Hello Tractor**\n- "L''Uber du tracteur" en Afrique\n- Connecte tracteurs et agriculteurs via IA\n\n**Apollo Agriculture (Kenya)**\n- Crédit agricole basé sur IA (analyse satellite + météo)\n- Prêts sans garantie traditionnelle\n\n## Santé\n\n**Ada Health**\n- Symptômes → diagnostic probabiliste IA\n- Disponible en français et swahili\n\n**Zipline**\n- Médicaments et sang livrés par drones optimisés par IA\n- Présent : Rwanda, Ghana, Kenya, Nigeria\n- 8 millions de livraisons en Afrique\n\n## Éducation\n\n**Khanmigo (Khan Academy IA)**\n- Tuteur IA personnalisé\n- Gratuit pour les élèves et enseignants\n\n**Prompt pour enseignant :**\n```\nJe suis professeur de [matière] en classe de [niveau] au [pays].\nGénère-moi :\n1. Une explication adaptée à des élèves de [âge] ans\n2. 3 exemples tirés du quotidien africain\n3. 5 questions de compréhension\n4. Une activité pratique de 20 minutes en groupe\n```'),

  -- Module 7 : Éthique IA
  (v_mod7, v_course_id, 'Les biais de l''IA et leurs implications pour l''Afrique', 'document', 1, false,
   E'# Biais de l''IA et Implications Africaines\n\n## Les biais qui affectent particulièrement l''Afrique\n\n### 1. Le biais de représentation\nLa plupart des IA ont été entraînées sur des données occidentales.\n\n**Conséquences :**\n- Systèmes de reconnaissance faciale moins précis sur les peaux sombres (erreur 34% vs 0,8% — étude MIT 2018)\n- Traducteurs IA moins performants pour les langues africaines\n- Recommandations médicales basées sur des données non africaines\n\n### 2. Le biais linguistique\nPerformances réduites en langues africaines (wolof, dioula, yoruba, swahili).\n\n**Solutions en développement :**\n- **Lelapa AI** (Afrique du Sud) : IA pour les langues africaines\n- **Initiative D4Africa** : datasets en langues africaines\n\n### 3. Le biais de crédit\nAlgorithmes de scoring formés sur données occidentales qui désavantagent les entrepreneurs africains.\n\n## Comment vous protéger\n\n**En tant qu''utilisateur :**\n1. Ne jamais accepter aveuglément une décision algorithmique\n2. Demander toujours une explication\n3. Signaler les erreurs et discriminations\n\n**En tant qu''entrepreneur qui déploie de l''IA :**\n1. Vérifier que vos données sont représentatives de votre clientèle\n2. Tester les résultats sur différents segments démographiques\n3. Inclure des experts locaux dans la conception\n\n## Réglementation africaine de l''IA\n- **Union Africaine :** Politique africaine sur l''IA adoptée en 2024\n- **Kenya :** Politique nationale IA 2022-2027\n- **Côte d''Ivoire :** Cadre de gouvernance en développement'),

  (v_mod7, v_course_id, 'Le futur du travail en Afrique à l''ère de l''IA', 'document', 2, false,
   E'# Futur du Travail en Afrique à l''Ère de l''IA\n\n## L''impact de l''IA sur l''emploi\n\nLe Forum Économique Mondial : l''IA déplacera **85 millions d''emplois** mais en créera **97 millions** → **bilan net +12 millions**.\n\n## Quels emplois sont menacés en Afrique ?\n\n**Risque élevé :**\n- Saisie de données, archivage\n- Tâches comptables répétitives\n- Centre d''appel de base\n- Caissiers, guichetiers\n\n**Risque faible (l''IA augmente sans remplacer) :**\n- Métiers de relation humaine (soin, éducation, conseil)\n- Métiers créatifs\n- Managers et leaders\n- Entrepreneurs\n\n## L''opportunité africaine\n\nL''Afrique a 60% de la population mondiale de moins de 25 ans. Cette génération peut :\n- S''approprier l''IA nativement\n- Développer des solutions IA pour les problèmes africains\n- Exporter des services IA vers le monde (freelancing)\n\n## Compétences que l''IA ne peut pas reproduire\n\n- **Intelligence relationnelle** : empathie, confiance, gestion des conflits\n- **Jugement contextuel** : décisions éthiques, nuances culturelles\n- **Créativité stratégique** : innovation de rupture, vision long terme\n- **Expertise spécialisée** : l''IA fait les 80% basiques, vous faites les 20% critiques\n\n## Votre plan d''action 12 mois\n\n1. **Mois 1-2 :** Maîtriser 3 outils IA fondamentaux\n2. **Mois 3-4 :** Automatiser une tâche répétitive\n3. **Mois 5-6 :** Intégrer l''IA dans votre création de contenu\n4. **Mois 7-9 :** Explorer l''IA dans votre secteur\n5. **Mois 10-12 :** Former vos collaborateurs\n\n> "L''IA ne remplacera pas les humains. Mais les humains qui utilisent l''IA remplaceront ceux qui ne l''utilisent pas." — Karim Sy, fondateur Jokkolabs (Sénégal)');

END $$;
