-- ============================================================
-- ENRICHISSEMENT : Formation Excel + Marketing Digital
-- ============================================================

-- FORMATION EXCEL
DO $$ DECLARE
  v_course_id uuid;
  v_mod1 uuid; v_mod2 uuid; v_mod3 uuid; v_mod4 uuid; v_mod5 uuid; v_mod6 uuid;
  v_max_pos int;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'formation-excel-muu7e33g';
  IF v_course_id IS NULL THEN RAISE NOTICE 'Formation Excel non trouvée'; RETURN; END IF;
  SELECT COALESCE(MAX(position), 0) INTO v_max_pos FROM modules WHERE course_id = v_course_id;

  INSERT INTO modules (course_id, title, position) VALUES
    (v_course_id, 'Les Bases Indispensables d''Excel', v_max_pos + 1),
    (v_course_id, 'Formules et Fonctions Essentielles', v_max_pos + 2),
    (v_course_id, 'Mise en Forme et Présentation', v_max_pos + 3),
    (v_course_id, 'Graphiques et Visualisation', v_max_pos + 4),
    (v_course_id, 'Tableaux Croisés Dynamiques', v_max_pos + 5),
    (v_course_id, 'Gestion de Données et Productivité', v_max_pos + 6);

  SELECT id INTO v_mod1 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos LIMIT 1;
  SELECT id INTO v_mod2 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos+1 LIMIT 1;
  SELECT id INTO v_mod3 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos+2 LIMIT 1;
  SELECT id INTO v_mod4 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos+3 LIMIT 1;
  SELECT id INTO v_mod5 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos+4 LIMIT 1;
  SELECT id INTO v_mod6 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos+5 LIMIT 1;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES
  (v_mod1, v_course_id, 'Interface Excel : navigation et raccourcis clavier essentiels', 'document', 1, true,
   E'# Interface Excel\n\n## Les zones de l''interface\n- **Barre de formule** : affiche le contenu de la cellule active\n- **Zone Nom** : indique la référence de la cellule (ex: A1)\n- **Ruban** : onglets Accueil, Insertion, Données...\n- **Onglets de feuilles** : en bas, pour naviguer entre feuilles\n\n## Raccourcis indispensables\n| Action | Raccourci |\n|--------|----------|\n| Sélectionner tout | Ctrl+A |\n| Copier | Ctrl+C |\n| Coller | Ctrl+V |\n| Annuler | Ctrl+Z |\n| Enregistrer | Ctrl+S |\n| Aller à A1 | Ctrl+Début |\n| Dernière cellule utilisée | Ctrl+Fin |\n| Sélectionner colonne entière | Ctrl+Espace |\n| Sélectionner ligne entière | Maj+Espace |\n| Insérer la date | Ctrl+; |\n\n## Types de données\n- **Texte** : aligné à gauche automatiquement\n- **Nombres** : alignés à droite automatiquement\n- **Dates** : stockées comme nombres, affichées avec format\n- **Formules** : commencent toujours par ='),

  (v_mod1, v_course_id, 'Saisie, modification et organisation des données', 'document', 2, false,
   E'# Saisie et Organisation des Données\n\n## Saisie efficace\n- **Entrée** : valide et descend d''une cellule\n- **Tab** : valide et se déplace à droite\n- **Echap** : annule la saisie en cours\n- **F2** : entre en mode édition dans la cellule\n\n## Remplissage automatique\nSélectionnez une cellule avec une valeur → tirez la poignée (petit carré en bas à droite) vers le bas ou la droite.\n\nExcel détecte les séries :\n- 1, 2 → 3, 4, 5...\n- Lundi → Mardi, Mercredi...\n- Jan → Fév, Mar...\n- Trimestre 1 → Trimestre 2...\n\n## Nommer une plage de cellules\n1. Sélectionnez les cellules\n2. Cliquez sur la **Zone Nom** (en haut à gauche)\n3. Tapez le nom (ex: `Ventes2024`)\n4. Entrée\n\nUtilisation : `=SOMME(Ventes2024)` au lieu de `=SOMME(B2:B13)`\n\n## Figer les volets\nPour voir les en-têtes en scrollant :\n1. Cliquez sur la cellule sous/à droite des lignes à figer (ex: B2 pour figer ligne 1 et colonne A)\n2. Affichage → Figer les volets'),

  (v_mod1, v_course_id, 'Références relatives, absolues et mixtes', 'document', 3, false,
   E'# Références de Cellules\n\n## Référence relative (A1)\nChange quand vous copiez la formule.\n```\n=A1+B1  →  copié en dessous devient  =A2+B2\n```\nUtilisation : calculs répétés sur chaque ligne.\n\n## Référence absolue ($A$1)\nNe change JAMAIS quand vous copiez.\n```\n=A1*$B$1  →  copié en dessous devient  =A2*$B$1\n```\nUtilisation : taux de TVA, prix fixes, constantes.\n\n**Astuce :** Appuyez sur **F4** pour basculer entre les types de référence.\n\n## Référence mixte ($A1 ou A$1)\n- `$A1` : la colonne A est fixe, la ligne change\n- `A$1` : la ligne 1 est fixe, la colonne change\n\n### Exemple pratique : table de multiplication\n```\n     A    B    C    D\n1       1    2    3\n2   1  =B$1*$A2\n3   2\n4   3\n```\nAvec `=B$1*$A2` copiée dans toute la table, les en-têtes restent fixes.'),

  (v_mod1, v_course_id, 'Tri, filtre et mise en tableau structuré', 'document', 4, false,
   E'# Tri, Filtre et Tableaux Structurés\n\n## Trier les données\n1. Cliquez dans votre plage de données\n2. Données → Trier\n3. Choisissez la colonne et l''ordre (A→Z ou Z→A)\n\n**Tri multi-niveaux :** Données → Trier → Ajouter un niveau\nEx: Trier par Région, puis par Vendeur, puis par Ventes décroissant.\n\n## Filtrer les données\n1. Cliquez dans vos données\n2. Données → Filtrer (ou Ctrl+Maj+L)\n3. Des flèches apparaissent sur les en-têtes\n4. Cliquez sur une flèche pour filtrer\n\n**Filtre avancé :** filtrer sur des critères complexes (contient, supérieur à, date entre...)\n\n## Mettre en Tableau Structuré (recommandé !)\n1. Cliquez dans vos données\n2. Insertion → Tableau (ou Ctrl+T)\n3. Vérifiez que "Mon tableau comporte des en-têtes" est coché\n\n**Avantages du tableau structuré :**\n- Les filtres sont automatiquement ajoutés\n- Les formules s''étendent automatiquement\n- Les références sont lisibles : `=SOMME(Tableau1[Ventes])` au lieu de `=SOMME(C2:C100)`\n- Le tableau s''agrandit automatiquement quand vous ajoutez des données'),

  (v_mod2, v_course_id, 'Fonctions mathématiques : SOMME, MOYENNE, ARRONDI', 'document', 1, false,
   E'# Fonctions Mathématiques Essentielles\n\n## SOMME et ses variantes\n```excel\n=SOMME(A1:A10)              → additionne A1 à A10\n=SOMME(A1:A10, C1:C10)     → additionne deux plages\n=SOMME.SI(A:A,"CI",B:B)    → somme si la colonne A = "CI"\n=SOMME.SI.ENS(B:B, A:A,"CI", C:C,">0")  → somme avec plusieurs critères\n```\n\n## MOYENNE et statistiques\n```excel\n=MOYENNE(A1:A10)            → moyenne\n=MIN(A1:A10)                → valeur minimale\n=MAX(A1:A10)                → valeur maximale\n=NBVAL(A1:A10)              → nombre de cellules non vides\n=NB(A1:A10)                 → nombre de cellules avec des nombres\n=NB.SI(A:A,"CI")            → nombre de cellules égales à "CI"\n```\n\n## ARRONDI\n```excel\n=ARRONDI(3.456, 2)          → 3.46 (2 décimales)\n=ARRONDI(3.456, 0)          → 3 (entier)\n=ARRONDI.INF(3.7, 0)        → 3 (arrondi vers le bas)\n=ARRONDI.SUP(3.2, 0)        → 4 (arrondi vers le haut)\n=ENT(3.9)                   → 3 (partie entière)\n```\n\n## Exercice pratique\nCalculez le CA mensuel, la moyenne, le min, le max et le total annuel de vos ventes sur 12 mois.'),

  (v_mod2, v_course_id, 'Fonctions de texte : CONCATENER, GAUCHE, DROITE, CHERCHE', 'document', 2, false,
   E'# Fonctions Texte\n\n## Combiner du texte\n```excel\n="Bonjour "&A1&" !"             → "Bonjour Jean !"\n=CONCATENER(A1," ",B1)         → "Jean Dupont"\n=CONCAT(A1:C1)                  → concatène une plage entière\n=JOINDRE.TEXTE(" ",VRAI,A1:C1) → joint avec séparateur, ignore vides\n```\n\n## Extraire du texte\n```excel\n=GAUCHE("Abidjan",3)           → "Abi"\n=DROITE("Abidjan",3)           → "jan"\n=STXT("Abidjan",3,4)           → "idja" (à partir du 3e caractère, 4 caractères)\n=NBCAR("Abidjan")              → 7 (nombre de caractères)\n```\n\n## Rechercher et nettoyer\n```excel\n=CHERCHE("@","jean@ibig.ci")   → 5 (position du @)\n=TROUVE("@","jean@ibig.ci")    → 5 (idem, sensible à la casse)\n=SUBSTITUE("Jean Dupont","Dupont","Martin") → "Jean Martin"\n=SUPPRESPACE("  texte  ")      → "texte" (supprime espaces superflus)\n=MINUSCULE("IBIG")             → "ibig"\n=MAJUSCULE("ibig")             → "IBIG"\n=NOMPROPRE("jean dupont")      → "Jean Dupont"\n```\n\n## Cas pratique : extraire le nom de domaine d''un email\n```excel\nEmail en A1 : "jean@ibig.ci"\n=STXT(A1, CHERCHE("@",A1)+1, NBCAR(A1))  → "ibig.ci"\n```'),

  (v_mod2, v_course_id, 'Fonctions logiques : SI, ET, OU, SIERREUR', 'document', 3, false,
   E'# Fonctions Logiques\n\n## La fonction SI\n```excel\n=SI(test_logique, valeur_si_vrai, valeur_si_faux)\n=SI(A1>100, "Objectif atteint", "En cours")\n```\n\n## SI imbriqués (plusieurs conditions)\n```excel\n=SI(A1>=90,"Excellent", SI(A1>=70,"Bien", SI(A1>=50,"Passable","Insuffisant")))\n```\n\n**Conseil :** Au-delà de 3 niveaux, utilisez plutôt SWITCH ou une table de correspondance.\n\n## ET / OU pour combiner des conditions\n```excel\n=SI(ET(A1>0, B1="CI"), "Éligible", "Non éligible")\n→ Vrai seulement si LES DEUX conditions sont vraies\n\n=SI(OU(A1="CI", A1="SN"), "Afrique Ouest", "Autre")\n→ Vrai si AU MOINS UNE condition est vraie\n```\n\n## SIERREUR : gérer les erreurs proprement\n```excel\n=SIERREUR(A1/B1, 0)          → renvoie 0 si division par zéro\n=SIERREUR(RECHERCHEV(...), "Non trouvé")  → message clair si RECHERCHEV échoue\n```\n\n## Exercice : système de notation\nColonne A : scores (0-100)\nFormule en B1 : créez une formule qui affiche "A" (≥90), "B" (≥75), "C" (≥60), "D" (≥50), "E" (<50)'),

  (v_mod2, v_course_id, 'RECHERCHEV, RECHERCHEH et INDEX/EQUIV', 'document', 4, false,
   E'# Fonctions de Recherche\n\n## RECHERCHEV (la plus utilisée en entreprise)\n```excel\n=RECHERCHEV(valeur_cherchée, table, numéro_colonne, FAUX)\n```\n- `valeur_cherchée` : ce qu''on cherche (ex: un code produit)\n- `table` : la plage où chercher (ex: A:D)\n- `numéro_colonne` : numéro de la colonne à renvoyer (ex: 3 pour la 3e colonne)\n- `FAUX` : correspondance exacte (toujours FAUX en pratique)\n\n**Exemple :** Trouver le prix d''un produit par son code\n```excel\nTable produits : A=Code, B=Nom, C=Prix\nFormule : =RECHERCHEV("PROD001", A:C, 3, FAUX)  → renvoie le prix\n```\n\n**Limitations de RECHERCHEV :**\n- Cherche toujours dans la 1ère colonne de la table\n- Ne peut pas chercher à gauche\n\n## INDEX + EQUIV : plus flexible\n```excel\n=INDEX(colonne_résultat, EQUIV(valeur_cherchée, colonne_recherche, 0))\n```\n\nExemple : trouver le code à partir du nom (cherche à gauche !)\n```excel\n=INDEX(A:A, EQUIV("Stylo", B:B, 0))\n```\n\n## RECHERCHEX (Excel 2021+)\n```excel\n=RECHERCHEX(valeur, plage_recherche, plage_résultat, "Non trouvé")\n```\nPlus simple et plus puissant que RECHERCHEV.'),

  (v_mod2, v_course_id, 'Formules de dates : AUJOURD''HUI, DATEDIF, DATE', 'document', 5, false,
   E'# Formules de Dates\n\n## Dates de base\n```excel\n=AUJOURD''HUI()              → date du jour\n=MAINTENANT()               → date et heure actuelles\n=ANNEE(A1)                  → extrait l''année d''une date\n=MOIS(A1)                   → extrait le mois (1-12)\n=JOUR(A1)                   → extrait le jour (1-31)\n=JOURSEM(A1, 2)             → jour de la semaine (1=Lundi avec paramètre 2)\n```\n\n## Créer une date\n```excel\n=DATE(2024, 12, 31)         → 31/12/2024\n=DATE(ANNEE(A1), MOIS(A1)+1, 1)-1  → dernier jour du mois\n```\n\n## Calculer des écarts\n```excel\n=A2-A1                      → nombre de jours entre deux dates\n=DATEDIF(A1, A2, "Y")       → nombre d''années complètes\n=DATEDIF(A1, A2, "M")       → nombre de mois complets\n=DATEDIF(A1, A2, "D")       → nombre de jours\n=NB.JOURS.OUVRES(A1,A2)     → jours ouvrés (hors week-ends)\n```\n\n## Cas pratiques\n```excel\nAncienneté d''un salarié :\n=DATEDIF(date_embauche, AUJOURD''HUI(), "Y") & " ans "\n& DATEDIF(date_embauche, AUJOURD''HUI(), "YM") & " mois"\n\nRetard de paiement :\n=SI(AUJOURD''HUI()>date_échéance, AUJOURD''HUI()-date_échéance, 0)\n```'),

  (v_mod3, v_course_id, 'Mise en forme conditionnelle : mettre en valeur les données', 'document', 1, false,
   E'# Mise en Forme Conditionnelle\n\nLa mise en forme conditionnelle colore les cellules automatiquement selon leurs valeurs.\n\n## Appliquer une règle simple\n1. Sélectionnez la plage de cellules\n2. Accueil → Mise en forme conditionnelle\n3. Choisissez une règle :\n   - Supérieur à / Inférieur à\n   - Entre deux valeurs\n   - Texte contenant\n   - Date se produisant\n\n## Nuances de couleur (Scales de couleurs)\nAccueil → Mise en forme conditionnelle → Nuances de couleurs\n→ Colore du rouge au vert selon les valeurs (idéal pour tableaux de bord)\n\n## Barres de données\nAffiche une barre proportionnelle à la valeur dans la cellule.\nAccueil → Mise en forme conditionnelle → Barres de données\n\n## Jeux d''icônes\nAffiche des icônes (feux tricolores, flèches, étoiles...) selon des seuils.\nAccueil → Mise en forme conditionnelle → Jeux d''icônes\n\n## Règle basée sur une formule (avancé)\nPermets des règles complexes :\n- Colorer une ligne entière si une colonne = "Impayé"\n- Colorer si la date est dépassée\n\n```\nFormule : =$C1="Impayé"\nApplicatione à : $A:$Z (toute la ligne)\n```'),

  (v_mod3, v_course_id, 'Formats de nombre, cellule et styles professionnels', 'document', 2, false,
   E'# Formats et Styles Professionnels\n\n## Formats de nombres\nCtrl+1 → onglet Nombre\n\n| Format | Exemple | Code |\n|--------|---------|------|\n| Nombre | 1 234 567 | `# ##0` |\n| Monétaire | 1 234 567 XOF | `# ##0 "XOF"` |\n| Pourcentage | 75,5% | `0,0%` |\n| Date | 31/12/2024 | `jj/mm/aaaa` |\n| Date longue | 31 décembre 2024 | `jj mmmm aaaa` |\n\n## Format personnalisé\nCtrl+1 → Nombre → Personnalisée\n\n```\n# ##0,00 "FCFA"     → 125 000,00 FCFA\n[>0][Vert]# ##0;[<0][Rouge]-# ##0  → vert si positif, rouge si négatif\n```\n\n## Styles de tableaux professionnels\n1. Insertion → Tableau → choisissez un style\n2. Ou : Accueil → Mettre sous forme de tableau\n\n**Conseil :** Utilisez des styles cohérents :\n- En-têtes : fond coloré, texte blanc, gras\n- Lignes alternées : gris clair / blanc\n- Total : gras, bordure supérieure double\n- Nombres : alignés à droite\n- Texte : aligné à gauche'),

  (v_mod3, v_course_id, 'Protection et partage de fichiers Excel', 'document', 3, false,
   E'# Protection et Partage\n\n## Protéger une feuille\nRévision → Protéger la feuille → définissez un mot de passe\n\nCela empêche les utilisateurs de modifier les cellules.\n**Astuce :** Avant de protéger, déverrouillez les cellules de saisie :\n1. Sélectionnez les cellules modifiables\n2. Ctrl+1 → Protection → décochez "Verrouillée"\n3. Puis protégez la feuille\n\n## Protéger certaines cellules avec mot de passe différent\nRévision → Permettre la modification des plages → Nouvelle plage → mot de passe\n\n## Masquer les formules\n1. Sélectionnez les cellules avec formules\n2. Ctrl+1 → Protection → cochez "Masquée"\n3. Protégez la feuille\n→ Les formules n''apparaissent plus dans la barre de formule\n\n## Partage et co-édition\n**En ligne (OneDrive/SharePoint) :**\n- Fichier → Enregistrer sous → OneDrive\n- Partager → Copier le lien\n- Plusieurs utilisateurs éditent simultanément\n\n**Par email :**\n- Fichier → Partager → Envoyer en tant que pièce jointe\n- Choisissez : fichier complet ou PDF\n\n## Préparer un fichier pour autrui\n- Supprimez les feuilles temporaires\n- Désactivez les calculs automatiques inutiles\n- Ajoutez une feuille "Mode d''emploi"\n- Vérifiez : Fichier → Vérifier → Inspecter le document'),

  (v_mod4, v_course_id, 'Créer des graphiques percutants pour vos rapports', 'document', 1, false,
   E'# Graphiques Professionnels dans Excel\n\n## Choisir le bon type de graphique\n| Objectif | Type recommandé |\n|----------|----------------|\n| Comparer des valeurs | Histogramme en colonnes |\n| Évolution dans le temps | Courbe |\n| Part de marché | Secteurs (camembert) |\n| Comparer plusieurs séries | Graphique combiné |\n| Corrélation entre variables | Nuage de points |\n| Performance vs objectif | Jauge ou thermomètre |\n\n## Créer un graphique\n1. Sélectionnez vos données (avec les en-têtes)\n2. Insertion → choisissez le type\n3. Double-cliquez pour personnaliser\n\n## Personnalisation essentielle\n- **Titre** : double-cliquez pour modifier, soyez précis ("CA par région - 2024")\n- **Étiquettes de données** : clic droit → Ajouter des étiquettes\n- **Couleurs** : clic droit sur une barre → Mettre en forme → choisissez les couleurs de votre charte\n- **Légende** : déplacez-la ou supprimez-la si les étiquettes sont suffisantes\n- **Axes** : Clic droit → Mettre en forme l''axe → ajustez min/max\n\n## Bonnes pratiques\n- Moins c''est plus : évitez les 3D, les dégradés, les ombres\n- Maximum 5-6 catégories par graphique\n- Triez les données (du plus grand au plus petit) pour les histogrammes\n- Commencez l''axe Y à 0 pour les comparaisons'),

  (v_mod4, v_course_id, 'Graphiques dynamiques liés aux tableaux croisés', 'document', 2, false,
   E'# Graphiques Dynamiques (Graphiques Croisés Dynamiques)\n\n## Créer un graphique croisé dynamique\n1. Cliquez dans un Tableau Croisé Dynamique existant\n2. Outils TCD → Analyser → Graphique croisé dynamique\n3. Choisissez le type\n\nLe graphique se met à jour automatiquement quand vous filtrez le TCD !\n\n## Segments (Slicers) : filtres visuels interactifs\n1. Cliquez dans le TCD\n2. Insertion → Segment\n3. Choisissez les champs de filtre\n4. Connectez à plusieurs TCD : clic droit sur le segment → Connexions de rapport\n\n**Résultat :** En cliquant sur un bouton du segment, tous les graphiques et TCD liés se mettent à jour.\n\n## Chronologie : filtre par dates interactif\n1. Cliquez dans le TCD\n2. Insertion → Chronologie\n3. Sélectionnez le champ date\n\nVous pouvez glisser pour filtrer par mois, trimestre ou année.\n\n## Astuce : graphique "Sparkline" dans les cellules\n1. Sélectionnez une cellule à côté de vos données\n2. Insertion → Graphiques sparkline → Courbe/Histogramme/Gains et pertes\n3. Sélectionnez la plage de données\n\n→ Un mini-graphique apparaît dans la cellule, idéal pour les tableaux de bord !'),

  (v_mod5, v_course_id, 'Tableaux Croisés Dynamiques : analyser en quelques clics', 'document', 1, false,
   E'# Tableaux Croisés Dynamiques (TCD)\n\n## Pourquoi utiliser un TCD ?\nUn TCD permet d''analyser de grandes quantités de données en les regroupant, filtrant et calculant en quelques clics — sans une seule formule.\n\n## Créer un TCD\n1. Cliquez dans vos données (tableau structuré recommandé)\n2. Insertion → Tableau croisé dynamique\n3. Choisissez "Nouvelle feuille de calcul"\n4. OK\n\n## La zone de champs (panneau à droite)\n- **Filtres** : filtre global (ex: Année)\n- **Colonnes** : ce qui apparaît en colonnes (ex: Trimestre)\n- **Lignes** : ce qui apparaît en lignes (ex: Région, Produit)\n- **Valeurs** : ce qu''on calcule (ex: Somme des Ventes)\n\n## Glissez-déposez pour explorer\n- Glissez "Région" dans Lignes\n- Glissez "CA" dans Valeurs → Somme du CA par région\n- Ajoutez "Trimestre" dans Colonnes → CA par région et trimestre\n- Glissez "Année" dans Filtres → filtrez sur 2024\n\n## Paramètres de calcul\nClic droit sur une valeur → Paramètres des champs de valeurs :\n- Somme, Moyenne, Nombre, Max, Min\n- Afficher les valeurs : % du total, différence, rang...\n\n## Actualiser\nQuand vos données source changent :\nClic droit dans le TCD → Actualiser'),

  (v_mod5, v_course_id, 'TCD avancés : champs calculés et groupements', 'document', 2, false,
   E'# TCD Avancés\n\n## Grouper les données\n### Grouper des dates automatiquement\nClic droit sur une date dans le TCD → Grouper → choisissez : Années, Trimestres, Mois\nExcel crée automatiquement les niveaux hiérarchiques.\n\n### Grouper des nombres par tranches\nClic droit sur un nombre → Grouper → définissez les tranches\nEx: Clients par tranche de CA : 0-500K, 500K-1M, 1M+\n\n## Champs calculés : créer des métriques personnalisées\n1. Cliquez dans le TCD\n2. Analyser → Champs, éléments et jeux → Champ calculé\n3. Donnez un nom (ex: "Marge")\n4. Formule : = Revenus - Coûts\n5. OK\n\nLe nouveau champ apparaît comme n''importe quelle autre valeur.\n\n## Tableaux de bord avec plusieurs TCD connectés\n1. Créez plusieurs TCD sur la même feuille (source identique)\n2. Ajoutez des Segments\n3. Clic droit sur le segment → Connexions de rapport\n4. Cochez tous les TCD à connecter\n\n→ Un clic sur le segment filtre tous les TCD et graphiques simultanément.\n\n## Disposition du TCD\n- **Compacte** (défaut) : tout dans une colonne\n- **Plan** : chaque champ dans sa propre colonne\n- **Tabulaire** : comme un tableau classique, idéal pour copier-coller'),

  (v_mod6, v_course_id, 'Validation de données : contrôler les saisies', 'document', 1, false,
   E'# Validation de Données\n\nLa validation empêche les saisies incorrectes dans vos formulaires et tableaux.\n\n## Créer une liste déroulante\n1. Sélectionnez la cellule ou plage\n2. Données → Validation des données\n3. Autoriser : **Liste**\n4. Source : tapez les valeurs séparées par ";" ou sélectionnez une plage\n5. OK\n\nRésultat : une flèche apparaît, l''utilisateur choisit dans la liste.\n\n## Autres types de validation\n- **Nombre entier** : entre deux valeurs (ex: 1 à 100)\n- **Décimal** : valeurs décimales avec limites\n- **Date** : entre deux dates\n- **Longueur du texte** : max 50 caractères par exemple\n- **Personnalisée** : basée sur une formule\n\n## Message de saisie et alerte d''erreur\nDans la fenêtre Validation :\n- Onglet **Message de saisie** : texte affiché quand l''utilisateur clique sur la cellule\n- Onglet **Alerte d''erreur** : message en cas de saisie invalide\n  - Arrêt : empêche la saisie\n  - Avertissement : avertit mais laisse saisir\n  - Information : informe seulement\n\n## Listes en cascade (département → ville)\nUtilisez INDIRECT :\n```excel\nSi A1 = "Côte d''Ivoire"\nEn B1 : =INDIRECT(A1)  \n→ Affiche la liste nommée "Côte d''Ivoire"\n```\nCréez des plages nommées pour chaque pays avec les villes correspondantes.'),

  (v_mod6, v_course_id, 'Raccourcis et astuces de productivité pour aller plus vite', 'document', 2, false,
   E'# Productivité et Raccourcis Avancés\n\n## Raccourcis de navigation\n| Action | Raccourci |\n|--------|-----------|\n| Aller à une cellule | Ctrl+G ou F5 |\n| Sélectionner jusqu''à la dernière cellule remplie | Ctrl+Maj+Fin |\n| Sélectionner une colonne entière de données | Ctrl+Maj+↓ puis ↓ |\n| Atteindre la première cellule du tableau | Ctrl+Début |\n\n## Raccourcis de mise en forme\n| Action | Raccourci |\n|--------|-----------|\n| Gras | Ctrl+G |\n| Italique | Ctrl+I |\n| Souligné | Ctrl+U |\n| Bordures | Ctrl+Maj+& |\n| Format monétaire | Ctrl+Maj+$ |\n| Format pourcentage | Ctrl+Maj+% |\n\n## Astuces de productivité\n\n**Ctrl+D** : copie la cellule du dessus vers le bas (fill down)\n**Ctrl+R** : copie la cellule de gauche vers la droite (fill right)\n**Alt+Entrée** : saut de ligne dans une cellule\n**Ctrl+;** : insère la date du jour\n**Ctrl+:**: insère l''heure actuelle\n\n## Flash Fill (Remplissage instantané)\nExcel 2013+ détecte les patterns de saisie :\n1. Colonne A : "Jean DUPONT"\n2. Colonne B : tapez "Jean" en B1\n3. En B2, commencez à taper → Excel propose de remplir automatiquement\n4. Appuyez sur Ctrl+E pour accepter\n\n**Utile pour :** extraire prénom, reformater des dates, nettoyer des données importées.');

END $$;

-- ============================================================
-- MARKETING DIGITAL POUR PME AFRICAINES
-- ============================================================
DO $$ DECLARE
  v_course_id uuid;
  v_mod1 uuid; v_mod2 uuid; v_mod3 uuid; v_mod4 uuid;
  v_max_pos int;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'marketing-digital-pme-africaines';
  IF v_course_id IS NULL THEN RAISE NOTICE 'Marketing Digital non trouvé'; RETURN; END IF;
  SELECT COALESCE(MAX(position), 0) INTO v_max_pos FROM modules WHERE course_id = v_course_id;

  INSERT INTO modules (course_id, title, position) VALUES
    (v_course_id, 'Stratégie Digitale pour PME Africaines', v_max_pos + 1),
    (v_course_id, 'Facebook et Instagram Ads : Publicité Payante', v_max_pos + 2),
    (v_course_id, 'Email Marketing et Automatisation', v_max_pos + 3),
    (v_course_id, 'Mesurer et Optimiser : Analytics et ROI', v_max_pos + 4);

  SELECT id INTO v_mod1 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos LIMIT 1;
  SELECT id INTO v_mod2 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos+1 LIMIT 1;
  SELECT id INTO v_mod3 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos+2 LIMIT 1;
  SELECT id INTO v_mod4 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos+3 LIMIT 1;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES
  (v_mod1, v_course_id, 'Définir sa cible et son persona client en Afrique', 'document', 1, false,
   E'# Définir sa Cible Marketing\n\n## Pourquoi connaître son client ?\nEn Afrique, les marchés sont très segmentés : langue, ethnie, niveau de revenu, urbain/rural, bancarisé/non bancarisé. Un message "tout public" ne convertit pas.\n\n## Le Persona : votre client idéal fictif\nCréez une fiche pour chaque segment :\n\n### Exemple — PME de vente de matériel informatique à Abidjan\n**Persona "Directeur PME" :**\n- **Prénom fictif :** Kouassi\n- **Âge :** 42 ans, marié, 3 enfants\n- **Localisation :** Cocody, Abidjan\n- **Revenus :** 800 000 - 1 500 000 FCFA/mois\n- **Utilisations numériques :** WhatsApp, Facebook, LinkedIn, appels\n- **Problèmes :** ses employés perdent du temps avec du matériel vétuste\n- **Motivations :** productivité, image professionnelle, fiabilité\n- **Objections :** "Trop cher", "Le SAV n''est pas fiable"\n- **Canaux à atteindre :** LinkedIn, appel commercial, recommandation\n\n## Questions pour définir votre persona\n1. Quel est son problème principal que votre produit résout ?\n2. Qu''est-ce qui l''empêche de dormir la nuit ?\n3. Quels réseaux sociaux utilise-t-il le plus ?\n4. Comment prend-il ses décisions d''achat ?\n5. Qui influence ses achats ?\n6. Quel budget peut-il allouer ?\n\n## Outil pratique : Google Forms\nCréez un sondage de 5 questions envoyé à vos clients actuels. Leurs réponses sont votre meilleure source de données persona.'),

  (v_mod1, v_course_id, 'Positionnement et message marketing différenciant', 'document', 2, false,
   E'# Positionnement et Message Marketing\n\n## Le positionnement : pourquoi vous plutôt qu''un concurrent ?\n\nLe positionnement répond à cette question du client : "Pourquoi je vous choisirais vous ?\n\n### La formule du positionnement\n```\nPour [cible précise],\n[Votre marque] est la seule [catégorie]\nqui [bénéfice principal unique]\nparce que [preuve crédible].\n```\n\nExemple :\n*Pour les PME de Côte d''Ivoire,\nIBIG E-LEARN est la seule plateforme de formation\nqui propose des cours conçus pour le contexte africain (OHADA, UEMOA, Mobile Money)\npar des formateurs experts de la région.*\n\n## Les 3 stratégies de positionnement\n1. **Moins cher** : guerre des prix, difficile à maintenir\n2. **Meilleur** : qualité supérieure, justifiée et perçue\n3. **Différent** : segment de niche, non comparable\n\nChoisissez la 3e quand vous le pouvez.\n\n## Le message marketing en 4 niveaux\n**Niveau 1 - Le tagline :** 5-8 mots mémorables\n*"La formation qui comprend l''Afrique"*\n\n**Niveau 2 - La proposition de valeur :** 1-2 phrases\n*"Des formations professionnelles adaptées au contexte économique africain, accessibles depuis votre téléphone, payables en Mobile Money."*\n\n**Niveau 3 - Le pitch de 30 secondes :** pour un appel ou une présentation\n\n**Niveau 4 - La présentation complète :** pour un rendez-vous commercial\n\n## Test de clarté\nMontrez votre tagline à un inconnu pendant 5 secondes. S''il ne comprend pas ce que vous faites, recommencez.'),

  (v_mod1, v_course_id, 'Créer un calendrier éditorial réseaux sociaux', 'document', 3, false,
   E'# Calendrier Éditorial Réseaux Sociaux\n\n## Pourquoi planifier ?\nPublier au hasard = résultats au hasard. Un calendrier :\n- Garantit la régularité (algorithmes favorisent la constance)\n- Évite le syndrome de la page blanche\n- Permet d''alterner les types de contenu\n- Facilite la délégation\n\n## Les types de contenu à alterner (règle 80/20)\n**80% contenu de valeur (pas de vente directe) :**\n- Conseils pratiques du domaine\n- Témoignages clients\n- Coulisses de l''entreprise\n- Questions à l''audience\n- Infographies éducatives\n- Actualités du secteur commentées\n\n**20% contenu commercial :**\n- Promotions et offres\n- Présentation de produits/services\n- Appel à l''action direct\n\n## Fréquence recommandée par réseau\n| Réseau | Fréquence idéale | Heures de pic (Afrique) |\n|--------|-----------------|------------------------|\n| Facebook | 1x/jour | 12h-14h et 19h-21h |\n| Instagram | 1x/jour | 12h et 20h |\n| LinkedIn | 3-4x/semaine | 8h-9h et 17h-18h |\n| TikTok | 1-2x/jour | 18h-22h |\n| WhatsApp Business | Variable | 7h-9h et 17h-20h |\n\n## Modèle de calendrier hebdomadaire\n| Jour | Type de contenu | Format |\n|------|----------------|--------|\n| Lundi | Conseil pratique | Carrousel |\n| Mardi | Témoignage client | Photo + texte |\n| Mercredi | Derrière les coulisses | Vidéo courte |\n| Jeudi | Question/Sondage | Texte |\n| Vendredi | Contenu commercial | Photo produit |\n| Samedi | Contenu inspirant | Citation + image |\n\n## Outils de planification gratuits\n- **Meta Business Suite** : planifier Facebook + Instagram\n- **Buffer** (gratuit jusqu''à 3 comptes)\n- **Later** (spécialisé Instagram)\n- **Hootsuite** (version gratuite limitée)'),

  (v_mod2, v_course_id, 'Publicité Facebook et Instagram : créer sa première campagne', 'document', 1, false,
   E'# Publicité Facebook & Instagram\n\n## Pourquoi Facebook Ads en Afrique ?\nFacebook reste le réseau #1 en Afrique de l''Ouest avec 50M+ utilisateurs actifs.\n- Ciblage précis : ville, âge, intérêts, comportements\n- Paiement en FCFA possible avec cartes locales\n- ROI mesurable en temps réel\n- Accessible dès 2 000 FCFA/jour\n\n## Structure d''une campagne Facebook\n```\nCampagne (Objectif)\n  └── Ensemble de publicités (Budget + Ciblage + Placements)\n        └── Publicités (Visuels + Textes)\n```\n\n## Objectifs de campagne\n- **Notoriété :** faire connaître votre marque\n- **Trafic :** amener des visiteurs sur votre site/WhatsApp\n- **Engagement :** likes, commentaires, partages\n- **Leads :** collecter des contacts\n- **Ventes :** achats directs (nécessite le Pixel)\n\n## Créer un ciblage efficace\n**Localisation :** ville(s) précises, rayon autour d''une adresse\n**Âge et genre :** adaptez à votre persona\n**Intérêts :** Facebook détecte les centres d''intérêt des utilisateurs\n- Business, Entrepreneuriat, Finance...\n- Marques concurrentes\n- Médias économiques locaux\n\n**Taille d''audience recommandée :** 50 000 - 500 000 personnes\n\n## Les formats publicitaires qui fonctionnent\n- **Vidéo courte (15-30s) :** meilleur engagement, coût au résultat le plus bas\n- **Carrousel :** plusieurs images/vidéos défilantes\n- **Image unique :** simple et efficace\n- **Collection :** catalogue produits immersif (mobile)'),

  (v_mod2, v_course_id, 'Ciblage avancé : audiences similaires et retargeting', 'document', 2, false,
   E'# Ciblage Avancé Facebook\n\n## Les Audiences Personnalisées\nCiblez des personnes qui vous connaissent déjà :\n\n**Depuis vos données :**\n- Liste de contacts (emails ou numéros de téléphone)\n- Visiteurs du site web (nécessite le Pixel Facebook)\n- Clients existants\n\n**Depuis vos activités Facebook/Instagram :**\n- Personnes ayant vu vos vidéos (>3 secondes, 25%, 50%...)\n- Personnes ayant interagi avec votre page\n- Personnes ayant visité votre profil Instagram\n\n## Les Audiences Similaires (Lookalike)\nFacebook trouve des personnes ressemblant à vos meilleurs clients.\n1. Créez une audience personnalisée de vos clients\n2. Créez une audience similaire basée dessus\n3. Choisissez la taille (1% = très similaire, 10% = plus large)\n\n**Conseil :** Une Lookalike basée sur vos 100 meilleurs clients est plus puissante qu''une basée sur tous vos contacts.\n\n## Le Retargeting : reprendre contact\nCiblez les personnes qui ont visité votre site sans acheter :\n1. Installez le Pixel Facebook sur votre site\n2. Créez une audience "Visiteurs du site - 30 derniers jours"\n3. Excluez les acheteurs\n4. Montrez une pub de relance avec une offre spéciale\n\n**Taux de conversion moyen :** 3-5x supérieur au ciblage froid\n\n## Budget et enchères\n- **CBO (Campaign Budget Optimization)** : Facebook répartit le budget automatiquement entre vos ensembles\n- **Budget journalier minimum :** 2 000-5 000 FCFA pour commencer\n- **Durée minimale de test :** 7 jours avant de juger'),

  (v_mod2, v_course_id, 'Créer des visuels et textes publicitaires qui convertissent', 'document', 3, false,
   E'# Visuels et Textes Publicitaires\n\n## Les secrets d''un visuel qui stoppe le scroll\nVous avez **1,7 seconde** pour capter l''attention.\n\n**Ce qui fonctionne en Afrique :**\n- Visages humains (de préférence locaux)\n- Couleurs vives et contrastées\n- Texte lisible sur mobile (taille 24px minimum)\n- Avant/Après\n- Chiffres et statistiques\n- Logos de clients reconnus\n\n**Ce qui ne fonctionne pas :**\n- Photos stock génériques avec des mains blanches\n- Texte illisible sur image\n- Trop d''information dans un visuel\n- Images flous ou trop petites\n\n## La structure d''un texte publicitaire qui convertit\n```\n🎯 ACCROCHE (1ère ligne visible) :\nQuestion ou affirmation choc qui concerne la douleur du client\n\n📖 CORPS :\n- Identifiez le problème\n- Agitez la douleur\n- Présentez la solution\n- Listez 3 bénéfices concrets\n\n✅ PREUVES SOCIALES :\n"Déjà 500 PME abidjanaises nous font confiance"\n\n🚀 APPEL À L''ACTION (CTA) :\nClair, urgent, simple\n"Cliquez sur Contacter pour un devis gratuit"\n"Réservez votre place (10 restantes)"\n```\n\n## Formules d''accroches éprouvées\n- "Vous en avez marre de [problème] ?" \n- "Comment [bénéfice] en [temps] sans [obstacle]"\n- "[Chiffre] entrepreneurs ont déjà [résultat]"\n- "ATTENTION : si vous [situation], lisez ceci"\n\n## Outils gratuits pour créer les visuels\n- **Canva** : templates prêts à l''emploi\n- **CapCut** : montage vidéo mobile\n- **Remove.bg** : supprimer les fonds\n- **Pexels/Unsplash** : photos gratuites'),

  (v_mod3, v_course_id, 'Construire une liste email et créer sa newsletter', 'document', 1, false,
   E'# Email Marketing\n\n## Pourquoi l''email en Afrique ?\n- Vous possédez votre liste (vs réseaux sociaux où l''algorithme contrôle)\n- Taux d''ouverture moyen 25-40% (vs 2-5% de portée organique Facebook)\n- ROI moyen : 42 USD pour 1 USD investi\n- Fonctionne même avec une connexion lente\n\n## Constituer sa liste d''emails légalement\n\n**Méthodes efficaces :**\n- Formulaire d''inscription sur le site (avec incentive)\n- Lead magnet : guide PDF, checklist, template gratuit\n- Inscription à la newsletter depuis les réseaux sociaux\n- Collecte lors d''événements (avec consentement)\n- Signature email avec lien d''inscription\n\n**Le lead magnet idéal :**\n- Résout UN problème précis et immédiat\n- Téléchargeable immédiatement\n- Titre clair : "Le Guide Gratuit pour [résultat] en [temps]"\n\n## Outils d''email marketing\n| Outil | Gratuit jusqu''à | Prix |\n|-------|-----------------|------|\n| Mailchimp | 500 contacts | Payant après |\n| Brevo (ex-Sendinblue) | 300 emails/jour | Abordable |\n| MailerLite | 1 000 contacts | Très abordable |\n| ConvertKit | 1 000 abonnés | Freemium |\n\n## Structure d''une newsletter efficace\n1. **Objet accrocheur** (taux d''ouverture) — max 50 caractères\n2. **Prévisualisation** (complète l''objet)\n3. **Salutation personnalisée** (Bonjour [Prénom],)\n4. **Contenu de valeur** (80%)\n5. **Offre ou CTA** (20%)\n6. **Désinscription** (obligatoire légalement)'),

  (v_mod3, v_course_id, 'WhatsApp Business : transformer vos contacts en clients', 'document', 2, false,
   E'# WhatsApp Business pour les PME Africaines\n\nWhatsApp est LE canal de communication numéro 1 en Afrique. Taux d''ouverture des messages : **98%**.\n\n## WhatsApp Business vs WhatsApp normal\n| Fonctionnalité | Normal | Business |\n|----------------|--------|----------|\n| Profil entreprise | ❌ | ✅ |\n| Catalogue produits | ❌ | ✅ |\n| Réponses automatiques | ❌ | ✅ |\n| Étiquettes contacts | ❌ | ✅ |\n| Statistiques messages | ❌ | ✅ |\n| Lien d''invitation | ❌ | ✅ |\n\n## Configurer WhatsApp Business\n1. Téléchargez WhatsApp Business (gratuit)\n2. Complétez le profil : nom, secteur, adresse, horaires, description\n3. Configurez le message d''accueil automatique\n4. Configurez le message d''absence\n5. Ajoutez vos produits/services dans le Catalogue\n\n## Les Listes de Diffusion (stratégie clé)\n- Envoyez un message à plusieurs contacts sans créer de groupe\n- Chaque contact reçoit un message personnel (pas collectif)\n- Maximum 256 contacts par liste\n- **Condition :** le contact doit avoir votre numéro enregistré\n\n**Organisation recommandée :**\n- Liste "Prospects chauds"\n- Liste "Clients actifs"\n- Liste "Clients anciens"\n- Liste "Partenaires"\n\n## Séquence de bienvenue\nQuand un nouveau prospect vous contacte :\n1. Message 1 (immédiat) : accueil + demande de besoin\n2. Message 2 (J+1) : envoi du catalogue / devis\n3. Message 3 (J+3) : relance et question ouverte\n4. Message 4 (J+7) : offre spéciale ou valeur ajoutée'),

  (v_mod4, v_course_id, 'Google Analytics et mesure des performances', 'document', 1, false,
   E'# Mesurer ses Performances Marketing\n\n## Les KPIs essentiels par canal\n\n### Réseaux sociaux\n- **Portée** : combien de personnes ont vu vos publications\n- **Engagement** : likes + commentaires + partages / portée\n- **Taux d''engagement** : >3% = bon, >6% = excellent\n- **Croissance d''abonnés** : évolution mensuelle\n\n### Publicité payante\n- **CPM** (Coût Pour Mille impressions) : coût de visibilité\n- **CPC** (Coût Par Clic) : coût pour amener un visiteur\n- **CTR** (Taux de Clic) : clics / impressions — bon si >2%\n- **CPL** (Coût Par Lead) : coût pour obtenir un contact\n- **ROAS** (Return On Ad Spend) : CA généré / budget pub\n\n### Site web\n- **Sessions** : visites\n- **Utilisateurs** : visiteurs uniques\n- **Taux de rebond** : % qui partent sans interagir (<60% = bon)\n- **Durée moyenne** : temps passé sur le site\n- **Taux de conversion** : % qui font l''action souhaitée\n\n## Google Analytics 4 (GA4)\n1. Créez un compte Google Analytics (analytics.google.com)\n2. Ajoutez le code de suivi sur votre site\n3. Attendez 24-48h pour les premières données\n\n**Rapports essentiels :**\n- Acquisition : d''où viennent vos visiteurs\n- Engagement : quelles pages consultent-ils\n- Conversion : quels objectifs sont atteints\n\n## Créer un tableau de bord mensuel\nComparez chaque mois :\n- Trafic total et par source\n- Leads générés\n- Coût par lead\n- Chiffre d''affaires attribuable au digital\n- Top 3 contenus/publications performants'),

  (v_mod4, v_course_id, 'Calculer le ROI de ses actions marketing', 'document', 2, false,
   E'# ROI du Marketing Digital\n\n## La formule du ROI\n```\nROI = (Revenus générés - Coût de l''investissement) / Coût de l''investissement × 100\n\nExemple :\nBudget pub : 100 000 FCFA\nVentes générées : 450 000 FCFA\nROI = (450 000 - 100 000) / 100 000 × 100 = 350%\n```\n\n## Attribuer les ventes au marketing\nDéfi : un client peut voir votre pub, visiter votre site, vous appeler, puis acheter. Quel canal a "converti" ?\n\n**Méthodes d''attribution :**\n- **Dernier clic** : attribué au canal vu juste avant l''achat\n- **Premier clic** : attribué au canal de la première découverte\n- **Multi-touch** : réparti entre tous les canaux du parcours\n\n**Méthode simple pour PME :**\nDemandez à chaque nouveau client : "Comment nous avez-vous connu ?" et enregistrez la réponse.\n\n## Coût d''Acquisition Client (CAC)\n```\nCAC = Total dépenses marketing et ventes / Nombre de nouveaux clients\n\nExemple :\nBudget marketing mensuel : 300 000 FCFA\nNouveaux clients ce mois : 15\nCAC = 300 000 / 15 = 20 000 FCFA\n```\n\n## Valeur Vie Client (LTV ou CLV)\n```\nLTV = Panier moyen × Fréquence d''achat annuelle × Durée de vie client\n\nExemple :\nPanier moyen : 75 000 FCFA\nAchats/an : 3\nDurée client : 4 ans\nLTV = 75 000 × 3 × 4 = 900 000 FCFA\n```\n\n**Règle d''or :** LTV doit être au moins 3x le CAC pour un business rentable.\nSi CAC = 20 000 FCFA, LTV doit être > 60 000 FCFA.');

END $$;
