-- ============================================================
-- ENRICHISSEMENT : Finance Personnelle + E-commerce
-- ============================================================

-- FINANCE PERSONNELLE & INVESTISSEMENT EN AFRIQUE
DO $$ DECLARE
  v_course_id uuid;
  v_mod1 uuid; v_mod2 uuid; v_mod3 uuid; v_mod4 uuid;
  v_max_pos int;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'finance-personnelle-investissement-afrique';
  IF v_course_id IS NULL THEN RAISE NOTICE 'Finance Personnelle non trouvé'; RETURN; END IF;
  SELECT COALESCE(MAX(position), 0) INTO v_max_pos FROM modules WHERE course_id = v_course_id;

  INSERT INTO modules (course_id, title, position) VALUES
    (v_course_id, 'Construire son Budget et Épargner en Afrique', v_max_pos + 1),
    (v_course_id, 'Investir : Immobilier, Bourse et Entrepreneuriat', v_max_pos + 2),
    (v_course_id, 'Crédits, Dettes et Mobile Money', v_max_pos + 3),
    (v_course_id, 'Préparer sa Retraite et Protéger sa Famille', v_max_pos + 4);

  SELECT id INTO v_mod1 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos LIMIT 1;
  SELECT id INTO v_mod2 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos+1 LIMIT 1;
  SELECT id INTO v_mod3 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos+2 LIMIT 1;
  SELECT id INTO v_mod4 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos+3 LIMIT 1;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES
  (v_mod1, v_course_id, 'Faire son bilan financier personnel : actif, passif, net worth', 'document', 1, false,
   E'# Bilan Financier Personnel\n\n## Pourquoi faire son bilan ?\nComme une entreprise, votre situation financière personnelle peut se mesurer. Sans mesure, pas d''amélioration possible.\n\n## L''Actif : ce que vous POSSÉDEZ\n### Actifs liquides (convertibles en cash rapidement)\n- Solde compte courant\n- Épargne disponible (carnet, mobile money)\n- Investissements cotés (actions)\n\n### Actifs semi-liquides (convertibles en quelques semaines)\n- Épargne bloquée\n- Assurance-vie\n- Parts de coopérative\n\n### Actifs immobilisés (long à convertir)\n- Valeur du bien immobilier (si vous possédez)\n- Valeur du véhicule\n- Bijoux et objets de valeur\n- Parts d''entreprise\n\n## Le Passif : ce que vous DEVEZ\n- Crédit immobilier restant\n- Crédit véhicule restant\n- Dettes familiales importantes\n- Découverts\n- Dettes carte de crédit\n\n## Le Patrimoine Net (Net Worth)\n```\nPatrimoine Net = Total Actifs - Total Passifs\n```\n\n**Exemple :**\n- Maison en construction : 15 000 000 FCFA\n- Épargne : 2 500 000 FCFA\n- Voiture : 3 000 000 FCFA\n- **Total Actifs : 20 500 000 FCFA**\n\n- Crédit construction : 8 000 000 FCFA\n- Prêt voiture : 1 200 000 FCFA\n- **Total Passifs : 9 200 000 FCFA**\n\n**Patrimoine Net = 11 300 000 FCFA**\n\n## Suivre l''évolution\nRefaites ce bilan chaque année. Si votre patrimoine net augmente, vous êtes sur la bonne voie.'),

  (v_mod1, v_course_id, 'La méthode du budget 50/30/20 adaptée à l''Afrique', 'document', 2, false,
   E'# Budgéter avec la règle 50/30/20\n\n## La règle classique\n- **50%** du revenu net → Besoins essentiels\n- **30%** → Envies et loisirs\n- **20%** → Épargne et investissement\n\n## Adaptation au contexte africain\nEn Afrique, les obligations familiales et sociales sont réelles. Voici une version adaptée :\n\n- **45%** → Besoins essentiels (loyer, nourriture, transport, santé)\n- **15%** → Obligations familiales et sociales (famille élargie, cérémonies)\n- **20%** → Envies personnelles\n- **20%** → Épargne et investissement (NON NÉGOCIABLE)\n\n## Exemple pour un revenu de 500 000 FCFA/mois\n| Catégorie | % | Montant |\n|-----------|---|--------|\n| Loyer | 20% | 100 000 |\n| Alimentation | 15% | 75 000 |\n| Transport | 8% | 40 000 |\n| Santé | 2% | 10 000 |\n| **Sous-total Besoins** | **45%** | **225 000** |\n| Famille/Social | 15% | 75 000 |\n| Loisirs/Personnel | 20% | 100 000 |\n| **Épargne/Investissement** | **20%** | **100 000** |\n\n## Le piège des "petites dépenses"\n\n5 000 FCFA de taxi en plus par jour = **150 000 FCFA/mois**\n1 verre après le travail 3x/semaine = **90 000 FCFA/mois**\n\n## L''automatisation de l''épargne\nTransférez votre épargne le **jour du salaire**, avant de dépenser. Pas à la fin du mois avec "ce qu''il reste" (il ne reste jamais rien).\n\nAvec Mobile Money : programmez un virement automatique vers votre compte d''épargne dès réception du salaire.'),

  (v_mod1, v_course_id, 'Constituer un fonds d''urgence : combien, où et comment ?', 'document', 3, false,
   E'# Le Fonds d''Urgence\n\n## Qu''est-ce qu''un fonds d''urgence ?\nUne réserve de cash disponible immédiatement pour faire face aux imprévus sans s''endetter.\n\n**Urgences typiques en Afrique :**\n- Maladie d''un proche (frais médicaux)\n- Panne véhicule\n- Réparation urgente du logement\n- Perte d''emploi temporaire\n- Dépenses sociales imprévues (décès, mariage)\n\n## Combien épargner ?\n**Minimum recommandé :** 3 mois de dépenses essentielles\n**Idéal :** 6 mois de dépenses totales\n\nExemple : dépenses mensuelles = 300 000 FCFA\n- Minimum : 900 000 FCFA\n- Idéal : 1 800 000 FCFA\n\n## Où placer le fonds d''urgence ?\nCritères : **accessible rapidement** + **sécurisé** + **rendement raisonnable**\n\n**Options en Afrique :**\n1. **Compte d''épargne bancaire** : sûr, accessible, faible rendement (2-4%)\n2. **Mobile Money (Orange Money, MTN MoMo, Wave)** : très accessible, taux nul à faible\n3. **Tontine personnelle** : attention, pas toujours disponible immédiatement\n4. **Bon de Trésor** : rendement 5-7%, mais blocage 3-12 mois\n\n**À ÉVITER pour le fonds d''urgence :** immobilier, bourse, crypto, tout actif non liquide.\n\n## Plan de constitution en 6 mois\n| Mois | Action | Cumul objectif |\n|------|--------|----------------|\n| 1 | 50 000 FCFA | 50 000 |\n| 2 | 50 000 FCFA | 100 000 |\n| 3 | 100 000 FCFA | 200 000 |\n| 4 | 150 000 FCFA | 350 000 |\n| 5 | 150 000 FCFA | 500 000 |\n| 6 | 200 000 FCFA | 700 000 |\n\nOnce constitué : ne le touchez QUE pour de vraies urgences. Reconstituez-le dès que vous y avez puisé.'),

  (v_mod2, v_course_id, 'Investir dans l''immobilier en Afrique : guide pratique', 'document', 1, false,
   E'# Investissement Immobilier en Afrique\n\nL''immobilier est l''investissement préféré des Africains — pour de bonnes raisons.\n\n## Pourquoi l''immobilier en Afrique ?\n- Urbanisation rapide : la demande de logement croît de 3-5%/an\n- Inflation protégée : les loyers augmentent avec l''inflation\n- Actif tangible : contrairement aux actions, on peut voir et toucher\n- Effet de levier : s''acheter avec un crédit et rembourser avec les loyers\n- Patrimoine transmissible à la famille\n\n## Les types d''investissement immobilier\n\n### 1. Achat d''un terrain constructible\nStratégie : acheter en périphérie, attendre la valorisation\n- Investissement initial faible (2M-10M FCFA selon localisation)\n- Rendement : 10-30%/an en zone en développement\n- Risque : sécurisation du titre foncier, problèmes de litiges\n\n### 2. Construction locative\n- Achat terrain + construction appartements/chambres\n- Rendement locatif : 8-15%/an\n- Gestion nécessaire (locataires, entretien)\n\n### 3. Achat de logement pour revente\n- Acheter en VEFA (Vente en État Futur d''Achèvement) chez un promoteur\n- Revendre après livraison avec plus-value\n\n## Calculer la rentabilité\n```\nRentabilité brute = (Loyer annuel / Prix d''achat) × 100\n\nExemple :\nAppartement acheté : 25 000 000 FCFA\nLoyer mensuel : 200 000 FCFA → 2 400 000 FCFA/an\nRentabilité brute = 2 400 000 / 25 000 000 × 100 = 9,6%/an\n```\n\n## Points de vigilance\n- **Titre foncier** : vérifiez systématiquement (notaire ou service du cadastre)\n- **Promoteur** : vérifiez les réalisations passées avant de payer\n- **Zone** : accès routes, eau, électricité, proximité services\n- **Financement** : comparez crédit habitat BCEAO vs apport personnel'),

  (v_mod2, v_course_id, 'La Bourse en Afrique : BRVM, NGX et investissement actions', 'document', 2, false,
   E'# Investir en Bourse en Afrique\n\n## Les bourses africaines\n\n### BRVM (Bourse Régionale des Valeurs Mobilières)\nSiège à Abidjan, couvre 8 pays UEMOA :\n- Bénin, Burkina Faso, Côte d''Ivoire, Guinée-Bissau, Mali, Niger, Sénégal, Togo\n- Plus de 45 entreprises cotées\n- Horaires : 9h-15h (lundi-vendredi)\n\n**Actions emblématiques BRVM :**\n- SONATEL (télécoms Sénégal)\n- ECOBANK (bancaire)\n- SOLIBRA (brasserie CI)\n- TOTAL CI (énergie)\n- ORANGE CI (télécoms CI)\n\n### NGX (Nigeria Exchange Group)\n- Bourse du Nigeria, la plus grande d''Afrique de l''Ouest\n- 150+ entreprises cotées en naira\n\n## Comment investir à la BRVM ?\n1. Ouvrir un compte chez un Société de Gestion et d''Intermédiation (SGI)\n2. Déposer des fonds (minimum variable selon SGI)\n3. Passer des ordres d''achat/vente via votre SGI\n\n**SGI connues :** BICI Bourse, SIB Bourse, Hudson & Cie, SOGEBOURSE\n\n## Les principes de base de l''investissement boursier\n\n**Diversifiez :** Ne mettez pas tout dans une seule action\n**Investissez régulièrement :** DCA (Dollar Cost Averaging) — même montant chaque mois\n**Long terme :** La bourse est volatile à court terme, rentable à long terme\n**Dividendes :** Certaines actions versent des dividendes annuels (4-8% de rendement)\n\n## Risques à connaître\n- Liquidité faible : certains titres BRVM se négocient peu\n- Information limitée : peu d''analyses indépendantes disponibles\n- Risque de change pour les investissements hors zone FCFA'),

  (v_mod2, v_course_id, 'Les OPCVM et fonds d''investissement accessibles en Afrique', 'document', 3, false,
   E'# OPCVM et Fonds d''Investissement\n\n## Qu''est-ce qu''un OPCVM ?\nOrganisme de Placement Collectif en Valeurs Mobilières : un fonds géré par des professionnels qui collecte l''épargne de plusieurs investisseurs et investit dans des titres diversifiés.\n\n**Avantages :**\n- Diversification automatique (pas d''expertise requise)\n- Montant d''entrée faible (parfois dès 10 000 FCFA)\n- Gestion professionnelle\n- Liquidité (rachats possibles)\n\n## Types de fonds disponibles en zone UEMOA\n\n### Fonds Monétaires\n- Investissent en bons de trésor et dépôts bancaires\n- Rendement : 4-6%/an\n- Risque très faible\n- Idéal pour : fonds d''urgence, épargne court terme\n\n### Fonds Obligataires\n- Investissent en obligations d''État et d''entreprises\n- Rendement : 6-9%/an\n- Risque faible à modéré\n- Idéal pour : épargne moyen terme (2-5 ans)\n\n### Fonds Actions\n- Investissent en actions BRVM\n- Rendement : 8-15%/an (variable)\n- Risque plus élevé\n- Idéal pour : investissement long terme (5+ ans)\n\n## Exemples de fonds accessibles\n- **OMICAFI** (Côte d''Ivoire) : fonds monétaire Coris Banque\n- **SJBF** : Société de Gestion de fonds zone UEMOA\n- **Africa Rendement** : fonds obligataire\n\n## Comment choisir ?\n1. Définissez votre horizon d''investissement\n2. Évaluez votre tolérance au risque\n3. Comparez les frais de gestion (< 1,5%/an = acceptable)\n4. Vérifiez l''agrément CREPMF (régulateur UEMOA)'),

  (v_mod3, v_course_id, 'Comprendre et utiliser intelligemment le crédit', 'document', 1, false,
   E'# Crédit : Bon ou Mauvais Outil ?\n\n## La différence fondamentale\n\n### Bon crédit (crée de la richesse)\n- Crédit pour acheter un bien productif\n- L''actif financé génère plus que le coût du crédit\n\nExemple : Crédit à 8%/an pour acheter un appartement loué à 12%/an de rentabilité = GAIN net 4%/an\n\n### Mauvais crédit (détruit la richesse)\n- Crédit pour consommation (télé, voyage, fête)\n- Crédits à la consommation à 18-30%/an pour des achats qui perdent de la valeur\n\n## Le coût réel d''un crédit\n```\nEmprunt : 2 000 000 FCFA\nTaux : 15%/an sur 24 mois\n\nMensualité : ~97 000 FCFA\nTotal remboursé : 97 000 × 24 = 2 328 000 FCFA\nCoût du crédit : 328 000 FCFA\n```\n\n**Calculez toujours le coût total, pas juste la mensualité !**\n\n## Les types de crédit en Afrique\n| Type | Taux moyen | Durée | Usage |\n|------|-----------|-------|-------|\n| Crédit habitat | 8-12% | 10-20 ans | Immobilier |\n| Crédit auto | 10-15% | 3-5 ans | Véhicule |\n| Crédit conso | 15-24% | 1-3 ans | Dépenses pers. |\n| Microfinance | 18-36% | 3-18 mois | Petits besoins |\n| Mobile money prêt | 10-30% | 1-6 mois | Urgences |\n\n## Règles pour emprunter intelligemment\n1. **La mensualité ne doit pas dépasser 30-35% de vos revenus nets**\n2. **N''empruntez que pour des actifs productifs ou des urgences**\n3. **Comparez TOUJOURS au moins 3 offres de crédit**\n4. **Remboursez par anticipation si possible** (réduction des intérêts)\n5. **Évitez les crédits revolving** (pièges à dettes)'),

  (v_mod3, v_course_id, 'Mobile Money : épargne, transfert et crédit numérique', 'document', 2, false,
   E'# Mobile Money et Finance Numérique en Afrique\n\n## L''écosystème Mobile Money\nL''Afrique est le leader mondial du Mobile Money avec 60%+ des transactions mondiales.\n\n**Principaux opérateurs :**\n| Pays | Opérateurs |\n|------|----------|\n| Côte d''Ivoire | Orange Money, MTN MoMo, Moov Money, Wave |\n| Sénégal | Orange Money, Free Money, Wave |\n| Cameroun | MTN MoMo, Orange Money |\n| Burkina Faso | Orange Money, Moov Money, Coris Money |\n\n## Services disponibles\n\n### Transferts et paiements\n- Transferts entre particuliers (souvent gratuits ou 1%)\n- Paiement de factures (électricité, eau, abonnements)\n- Paiement de salaires (masse salariale)\n- Paiement marchands (QR code)\n\n### Épargne mobile\n- **Compte épargne intégré** : Orange Money Épargne, MTN Sabi Sabi...\n- Taux : 2-6%/an selon opérateur\n- Avantage : discipline forcée, accessible depuis le téléphone\n\n### Crédit numérique\n- **Orange Xpress Prêt**, **MTN Qwik Loan**, **Wave Crédit**\n- Montants : 5 000 à 500 000 FCFA selon historique\n- Taux : 5-15% pour la durée (1-3 mois) = équivalent 30-60%/an !\n- **Utilisation recommandée :** urgences seulement\n\n## Stratégie d''épargne via Mobile Money\n1. Recevez votre salaire en Mobile Money\n2. Transférez immédiatement 20% vers le compte épargne\n3. Ne dépensez que ce qui reste\n4. Activez les notifications pour suivre chaque transaction\n\n## Sécurité\n- Ne partagez JAMAIS votre code PIN\n- Vérifiez le numéro du bénéficiaire avant de confirmer\n- Activez l''authentification en 2 étapes si disponible\n- Notez votre numéro de transaction après chaque opération importante'),

  (v_mod4, v_course_id, 'Préparer sa retraite en Afrique : CNPS et épargne privée', 'document', 1, false,
   E'# Préparer sa Retraite\n\n## La réalité de la retraite en Afrique\n- **CNPS** : pension moyenne en Côte d''Ivoire < 80 000 FCFA/mois\n- **Espérance de vie** : 60-65 ans en moyenne → retraite à 60 ans = peu d''années de retraite\n- **Famille** : traditionnellement, les enfants soutiennent les parents — mais cette tradition s''érode\n\n**Conclusion : vous devez compter sur VOUS-MÊME pour votre retraite.**\n\n## La magie des intérêts composés\n```\nInvestissez 50 000 FCFA/mois à 8%/an\n\nAprès 10 ans : 9 200 000 FCFA\nAprès 20 ans : 29 700 000 FCFA\nAprès 30 ans : 75 000 000 FCFA\n\nVous avez investi : 18 000 000 FCFA\nLes intérêts ont généré : 57 000 000 FCFA\n```\n\n**Plus vous commencez tôt, moins vous devez investir.**\n\n## Options d''épargne retraite en Afrique\n\n### 1. Assurance-Vie avec participation aux bénéfices\n- Contrat avec une compagnie d''assurance (SUNU, SAHAM, NSIA...)\n- Rendement : 4-7%/an\n- Avantage fiscal possible\n- Capital transmissible aux bénéficiaires désignés\n\n### 2. OPCVM long terme\n- Fonds actions ou mixtes\n- Horizon 15-30 ans\n- Rendement espéré : 8-12%/an\n\n### 3. Immobilier locatif\n- Les loyers remplacent le salaire à la retraite\n- Objectif : 2-3 appartements payés avant la retraite\n\n## Plan de retraite en 4 étapes\n1. **Définir vos besoins** : combien vous faudra-t-il par mois ?\n2. **Calculer le capital nécessaire** : besoins × 12 × 20 ans\n3. **Définir l''épargne mensuelle** : pour atteindre ce capital\n4. **Choisir les placements** : selon horizon et risque toléré'),

  (v_mod4, v_course_id, 'Assurances et protection financière de la famille', 'document', 2, false,
   E'# Protéger sa Famille avec les Assurances\n\n## Pourquoi s''assurer ?\nSans assurance, un seul événement (maladie, accident, décès) peut détruire des années d''épargne et plonger la famille dans la précarité.\n\n## Les assurances essentielles\n\n### 1. Assurance Vie\n**Objectif :** Protéger la famille si vous décédez prématurément\n\nEn cas de décès :\n- Votre famille reçoit le capital assuré (ex: 10 000 000 FCFA)\n- Remplace vos revenus pour permettre à la famille de vivre\n\n**Combien s''assurer ?** Minimum 3-5 ans de revenus annuels\n\n### 2. Assurance Maladie Complémentaire (AMC)\n**Objectif :** Couvrir les frais médicaux non pris en charge par la CNPS/IPM\n- Consultations, hospitalisations, médicaments\n- Frais dentaires et optiques\n**Coût moyen :** 15 000-40 000 FCFA/mois selon couverture\n\n### 3. Assurance Invalidité\n**Objectif :** Revenu de remplacement si vous devenez invalide\n- Accident ou maladie grave empêchant de travailler\n- La CNPS couvre partiellement les accidents du travail\n\n### 4. Assurance Scolaire\n**Objectif :** Garantir les études des enfants même en cas de décès\n- Capital versé pour financer les études\n- Souvent intégrée à l''assurance vie\n\n## Comment choisir un assureur ?\n1. Vérifiez l''agrément CIMA (régulateur assurances zone franc)\n2. Comparez le ratio sinistres/primes (solvabilité)\n3. Lisez les exclusions avant de signer\n4. Vérifiez la facilité de déclaration et de remboursement sinistres\n5. Préférez les assureurs avec des agences physiques dans votre ville');

END $$;


-- E-COMMERCE ET VENTE EN LIGNE EN AFRIQUE
DO $$ DECLARE
  v_course_id uuid;
  v_mod1 uuid; v_mod2 uuid; v_mod3 uuid; v_mod4 uuid;
  v_max_pos int;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'ecommerce-vente-en-ligne-afrique';
  IF v_course_id IS NULL THEN RAISE NOTICE 'E-commerce non trouvé'; RETURN; END IF;
  SELECT COALESCE(MAX(position), 0) INTO v_max_pos FROM modules WHERE course_id = v_course_id;

  INSERT INTO modules (course_id, title, position) VALUES
    (v_course_id, 'Créer sa Boutique en Ligne', v_max_pos + 1),
    (v_course_id, 'Sourcing, Stock et Logistique en Afrique', v_max_pos + 2),
    (v_course_id, 'Paiement en Ligne et Mobile Money', v_max_pos + 3),
    (v_course_id, 'Vendre sur les Marketplaces Africaines', v_max_pos + 4);

  SELECT id INTO v_mod1 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos LIMIT 1;
  SELECT id INTO v_mod2 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos+1 LIMIT 1;
  SELECT id INTO v_mod3 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos+2 LIMIT 1;
  SELECT id INTO v_mod4 FROM modules WHERE course_id = v_course_id ORDER BY position OFFSET v_max_pos+3 LIMIT 1;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES
  (v_mod1, v_course_id, 'Choisir sa plateforme e-commerce : Shopify, WooCommerce ou solution locale', 'document', 1, false,
   E'# Choisir sa Plateforme E-commerce\n\n## Comparatif des solutions\n\n### Shopify\n**Pour qui :** Vendeurs qui veulent démarrer vite, budget disponible\n- ✅ Très facile à prendre en main\n- ✅ Hébergement inclus, sécurisé\n- ✅ 100+ templates professionnels\n- ✅ App Store avec milliers d''extensions\n- ❌ 29-79 USD/mois (environ 17 000-46 000 FCFA)\n- ❌ Commission sur ventes si paiement Shopify non activé\n- ❌ Peu d''intégrations Mobile Money africain nativement\n\n### WooCommerce (WordPress)\n**Pour qui :** Ceux qui veulent contrôle total, budget limité\n- ✅ Open source et gratuit\n- ✅ Personnalisation totale\n- ✅ Plugins Mobile Money disponibles\n- ✅ Communauté francophone active\n- ❌ Nécessite hébergement (5 000-15 000 FCFA/mois)\n- ❌ Maintenance technique requise\n- ❌ Plus long à configurer\n\n### Solutions africaines\n**Jumia Seller Center, Glovo Store (CI) :**\n- Marketplace avec trafic existant\n- Pas de boutique propre\n- Commission 15-25% par vente\n\n**MyBusiness.ci, TopAfric.com :**\n- Solutions locales adaptées\n- Support en FCFA\n- Intégrations Mobile Money\n\n## Recommandation selon profil\n| Profil | Solution recommandée |\n|--------|--------------------|\n| Débutant, budget serré | WooCommerce |\n| Croissance rapide voulue | Shopify |\n| Produits locaux + marketplace | Jumia + boutique propre |\n| Développeur disponible | Solution sur mesure |'),

  (v_mod1, v_course_id, 'Créer des fiches produits qui vendent', 'document', 2, false,
   E'# Fiches Produits Optimisées\n\n## La fiche produit : votre vendeur 24h/24\nEn ligne, personne ne peut toucher, sentir ou essayer votre produit. Votre fiche doit compenser ça.\n\n## Les éléments essentiels\n\n### 1. Photos de qualité\n- **Minimum 4-6 photos par produit**\n- Vue principale sur fond blanc (professionnel)\n- Vues multiples (face, côté, dos, détails)\n- Photo en situation d''utilisation (lifestyle)\n- Photo avec indication de taille si pertinent\n\n**Matériel minimum :** Smartphone récent + lumière naturelle + fond blanc (drap ou carton)\n\n### 2. Titre optimisé\nStructure : [Marque] + [Type de produit] + [Caractéristiques principales]\n\n*Exemple MAUVAIS :* "Robe"\n*Exemple BON :* "Robe Wax Africaine Femme - Modèle Abidjan - Tailles S à XXL - 100% Coton"\n\n### 3. Description convaincante\nStructure :\n- **Première phrase** : bénéfice principal\n- **Description** : caractéristiques techniques\n- **Pour qui** : situation d''utilisation\n- **Garanties** : retour, SAV, livraison\n\n### 4. Prix clair\n- Prix barré si promotion\n- Prix en FCFA (et USD si clientèle diaspora)\n- Frais de livraison affichés clairement (pas de surprise)\n\n### 5. Avis clients\n- Collectez et affichez les témoignages\n- Photos clients encore mieux\n- Répondez à TOUS les avis (positifs et négatifs)\n\n## Optimisation SEO des fiches\nIncluez dans le titre et la description les mots que vos clients tapent dans Google :\n- "acheter robe wax Abidjan"\n- "tissu africain livraison Côte d''Ivoire"'),

  (v_mod1, v_course_id, 'Livraison et expérience client : les clés de la fidélisation', 'document', 3, false,
   E'# Livraison et Expérience Client\n\n## La livraison : souvent le facteur décisif\n72% des abandons de panier en Afrique sont liés aux frais ou délais de livraison.\n\n## Options de livraison en Afrique\n\n### Livraison express (J+1)\n**Prestataires :**\n- Glovo, Jumia Delivery, Yango (grandes villes)\n- Coursiers moto indépendants\n- Votre propre livreur\n\n**Coût :** 1 000-3 000 FCFA en ville\n**Avantage :** Livraison le jour même ou J+1\n**Recommandé pour :** produits <5 kg dans la même ville\n\n### Livraison standard (3-7 jours)\n**Prestataires :**\n- La Poste locale (réseau national)\n- DHL, FedEx, UPS (international)\n- Gozem Delivery\n\n**Coût :** 2 000-8 000 FCFA selon distance\n\n### Retrait en boutique / points relais\n- Gratuit pour le client\n- Pratique pour ceux sans adresse précise\n- Créez un réseau de points relais (boutiques partenaires)\n\n## Politique de retour claire\n**Affichez clairement :**\n- Délai de retour (7, 14 ou 30 jours)\n- Conditions (produit non utilisé, emballage original)\n- Procédure (qui contacter, comment renvoyer)\n- Remboursement ou échange\n\n**Une bonne politique de retour augmente les ventes :** les clients achètent plus facilement quand ils savent qu''ils peuvent retourner.\n\n## L''emballage : marketing gratuit\n- Emballage soigné = image premium\n- Ajoutez un mot de remerciement manuscrit\n- Glissez un petit cadeau surprise (1 000-2 000 FCFA)\n- Incluez votre carte de visite et les réseaux sociaux\n\n**Résultat :** photos et témoignages spontanés des clients sur les réseaux sociaux (contenu UGC gratuit)'),

  (v_mod2, v_course_id, 'Trouver ses fournisseurs : Chine, local et dropshipping', 'document', 1, false,
   E'# Sourcing et Fournisseurs\n\n## Option 1 : Produits locaux africains\n**Avantages :**\n- Différenciation (produits introuvables ailleurs)\n- Délais courts, pas de douane\n- Impact social positif (artisans locaux)\n- Marges meilleures (pas de transport international)\n\n**Sources :**\n- Marchés artisanaux (Grand Marché, Treichville...)\n- Coopératives de femmes artisanes\n- Tisserands, potiers, bijoutiers locaux\n- Agriculture locale (produits transformés)\n\n## Option 2 : Importation depuis la Chine\n**Plateformes :**\n- **Alibaba.com** : grossistes et fabricants\n- **AliExpress** : petites quantités (test produits)\n- **1688.com** : prix fabricant (interface en chinois, utilisez Google Translate)\n- **DHGate** : B2B petites commandes\n\n**Processus :**\n1. Recherchez le produit + comparez 5-10 fournisseurs\n2. Demandez des échantillons (payer le transport)\n3. Négociez le prix pour une commande de test\n4. Vérifiez la qualité à réception\n5. Passez la commande principale\n\n**Frais à prévoir :**\n- Transport maritime : 4-8 semaines, moins cher\n- Transport aérien : 1-2 semaines, 3-5x plus cher\n- Droits de douane : 15-35% de la valeur déclarée selon pays et produit\n\n## Option 3 : Dropshipping\nVous vendez sans stock. Le fournisseur expédie directement au client.\n\n**Avantages :** pas de capital immobilisé en stock\n**Inconvénients :** délais longs (20-45 jours depuis Chine), qualité non contrôlée, service client difficile\n\n**Recommandation :** Testez d''abord en dropshipping, puis importez les produits qui marchent.'),

  (v_mod2, v_course_id, 'Gérer son stock et éviter les ruptures et surstocks', 'document', 2, false,
   E'# Gestion des Stocks\n\n## Les coûts cachés du mauvais stock\n\n**Rupture de stock :**\n- Vente perdue\n- Client déçu qui part chez le concurrent\n- Mauvaise réputation sur les réseaux\n\n**Surstock :**\n- Capital immobilisé inutilement\n- Coût de stockage\n- Risque de péremption ou démodement\n\n## Calcul du stock minimum (point de commande)\n```\nStock minimum = Délai fournisseur (jours) × Ventes journalières moyennes\n\nExemple :\nVous vendez 3 robes/jour en moyenne\nVotre fournisseur livre en 14 jours\nStock minimum = 14 × 3 = 42 robes\n\nCommandez dès que votre stock descend sous 42 robes.\n```\n\n## Stock de sécurité\nPour les imprévus (retard fournisseur, pic de ventes) :\n```\nStock sécurité = Délai fournisseur × (Ventes max - Ventes moyennes)\n= 14 × (6 - 3) = 42 robes supplémentaires\n```\n\n## Suivi du stock\n**Pour démarrer :** tableau Excel simple\n- Colonne : produit, stock initial, entrées, sorties, stock actuel\n- Mettez à jour à chaque vente et réception\n\n**Pour croître :**\n- Logiciel de gestion commerciale : Odoo (open source), Sage...\n- WooCommerce gère le stock automatiquement si configuré\n\n## Valorisation du stock\n**Méthode FIFO (First In First Out) :**\nLes premiers articles entrés sont les premiers vendus.\nRecommandé pour les produits périssables ou sujets aux modes.\n\n**Inventaire mensuel :**\nComptez physiquement votre stock une fois par mois et comparez avec votre système. Les écarts = vols ou erreurs de saisie.'),

  (v_mod3, v_course_id, 'Intégrer le Mobile Money sur sa boutique en ligne', 'document', 1, false,
   E'# Paiement en Ligne et Mobile Money\n\n## La réalité du paiement en Afrique\n- Moins de 20% de la population est bancarisée en Afrique de l''Ouest\n- **80%+ utilisent Mobile Money**\n- Proposer uniquement carte bancaire = exclure 80% de vos clients potentiels\n\n## Solutions de paiement Mobile Money pour e-commerce\n\n### GeniusPay\n- Accepte : Orange Money, MTN MoMo, Wave, Moov Money, carte Visa/Mastercard\n- Couverture : Côte d''Ivoire, Sénégal, Burkina Faso, Mali...\n- Commission : 2-3% par transaction\n- Intégration : API REST, plugins WooCommerce/PrestaShop\n- Dashboard : suivi des transactions en temps réel\n\n### CinetPay\n- 14 pays africains\n- Orange Money, MTN, Wave, Moov + cartes\n- Commission : ~3%\n- Plugin WordPress disponible\n\n### Ligdicash\n- Spécialisé zone UEMOA\n- Mobile Money toutes banques UEMOA\n\n## Comment intégrer GeniusPay sur WooCommerce\n1. Créez votre compte marchand sur GeniusPay\n2. Fournissez les documents (RCCM, pièce identité)\n3. Récupérez vos clés API (publique et privée)\n4. Installez le plugin WooCommerce GeniusPay\n5. Configurez avec vos clés API\n6. Testez avec un paiement test\n7. Activez en production\n\n## Paiement à la livraison (PAL)\n**Très populaire en Afrique :** le client paye en cash quand il reçoit le colis.\n- Avantage : lève les freins à l''achat\n- Inconvénient : taux de retour plus élevé, gestion cash\n- Recommandation : proposez les 2 options'),

  (v_mod3, v_course_id, 'Sécurité, fraudes et protection des transactions en ligne', 'document', 2, false,
   E'# Sécurité et Fraudes e-commerce\n\n## Les fraudes courantes en Afrique\n\n### Côté marchand (vous subissez)\n- **Faux paiement :** screenshot de paiement falsifié\n- **Chargeback frauduleux :** achat par carte puis contestation bancaire\n- **Adresse fausse :** livraison impossible, marchandise perdue\n- **Retour frauduleux :** retourne un autre produit ou produit abîmé\n\n### Protection\n- **Ne livrez qu''après confirmation réelle** du paiement (vérifiez dans votre tableau de bord, pas sur screenshot)\n- Conservez toutes les preuves (commande, conversation, numéro de suivi)\n- Pour les grosses commandes : demandez une pièce d''identité\n- Activez les notifications SMS/email pour chaque transaction\n\n## Côté client (vos clients vous font confiance)\n**Rassurez vos clients avec :**\n- Badge SSL (cadenas vert dans l''URL — HTTPS obligatoire)\n- Mentions légales complètes (nom société, adresse, RCCM)\n- Politique de retour claire\n- Numéro de téléphone WhatsApp visible\n- Avis clients vérifiés\n- Page "À propos" avec photos de l''équipe\n\n## HTTPS : obligatoire pour l''e-commerce\n1. Obtenez un certificat SSL (gratuit avec Let''s Encrypt ou inclus dans votre hébergement)\n2. Configurez les redirections HTTP → HTTPS\n3. Vérifiez que toutes les pages sont en HTTPS\n\n**Sans HTTPS :** Google marque votre site "Non sécurisé", les clients fuient et votre référencement chute.'),

  (v_mod4, v_course_id, 'Vendre sur Jumia, Amazon et les marketplaces africaines', 'document', 1, false,
   E'# Vendre sur les Marketplaces\n\n## Pourquoi les marketplaces ?\n- **Trafic existant :** millions de visiteurs/mois sans effort de votre part\n- **Confiance** : les clients font confiance aux grandes plateformes\n- **Infrastructure** : paiement, livraison, SAV gérés\n- **Visibilité internationale** : Amazon pour la diaspora\n\n## Jumia (Afrique de l''Ouest)\n**La plus grande marketplace d''Afrique de l''Ouest**\n\n**Inscription vendeur :**\n1. jumia.ci/seller-center\n2. Documents : RCCM, pièce identité, relevé bancaire\n3. Formation en ligne obligatoire\n4. Première livraison dans l''entrepôt Jumia\n\n**Commissions :** 8-25% selon catégorie\n**Livraison :** Jumia gère (Fulfilled by Jumia)\n\n**Conseils Jumia :**\n- Participez aux Jumia Flash Sales (Black Friday, anniversaire)\n- Investissez dans les photos professionnelles\n- Maintenez un taux de remplissage commande > 95%\n- Répondez aux avis négatifs rapidement\n\n## Amazon (Diaspora africaine)\n**Pour vendre aux Africains de la diaspora (France, USA, UK...)**\n\n- Inscrivez-vous sur Seller Central Amazon\n- Vendez en Euros/Dollars\n- Expédiez depuis votre pays (prix élevé) ou utilisez Amazon FBA (cher)\n- Nécessite compte bancaire international (Payoneer, Wise)\n\n## Etsy (Artisanat africain)\n**Idéal pour :**\n- Bijoux, tissu, art africain\n- Produits faits main uniques\n- Prix premium accepté par les acheteurs\n- Communauté internationale sensible au "fait en Afrique"\n\n## Stratégie multicanal recommandée\n```\nBoutique propre (WooCommerce/Shopify)\n  + Jumia (volume, visibilité locale)\n  + Amazon/Etsy (international)\n  + WhatsApp Business (fidélisation)\n  = Maximum de canaux de vente\n```'),

  (v_mod4, v_course_id, 'Service client e-commerce : transformer les plaintes en fidélité', 'document', 2, false,
   E'# Service Client e-commerce\n\n## Pourquoi le service client est un avantage concurrentiel\nEn Afrique, la confiance se construit par le contact humain. Un excellent service client :\n- Compense les lacunes du produit\n- Génère du bouche-à-oreille\n- Fidélise et augmente la valeur vie client\n- Différencie des concurrents qui ignorent leurs clients\n\n## Les canaux de contact à mettre en place\n| Canal | Priorité | Délai de réponse |\n|-------|----------|------------------|\n| WhatsApp Business | ⭐⭐⭐ Essentiel | < 1h |\n| Commentaires réseaux sociaux | ⭐⭐⭐ Essentiel | < 2h |\n| Email | ⭐⭐ Important | < 24h |\n| Avis Google My Business | ⭐⭐ Important | < 48h |\n| Chat sur le site | ⭐ Si possible | Temps réel |\n\n## Gérer les réclamations : le protocole HEARD\n**H**ear : Écoutez le client sans interrompre\n**E**mpathize : "Je comprends votre frustration..."\n**A**pologize : Excusez-vous même si vous n''avez pas tort\n**R**esolve : Proposez une solution concrète et rapide\n**D**iagnose : Identifiez la cause pour éviter la récurrence\n\n## Scripts de réponse WhatsApp\n\n**Commande non reçue :**\n"Bonjour [Prénom], merci de nous avoir contacté. Je suis vraiment désolé pour ce retard. Je vérifie immédiatement l''état de votre livraison et reviens vers vous dans 30 minutes avec une solution concrète. 🙏"\n\n**Produit endommagé :**\n"Bonjour [Prénom], je suis sincèrement désolé de voir cela. Envoyez-moi une photo et je vous envoie immédiatement un remplacement sans frais supplémentaires. Votre satisfaction est ma priorité absolue."\n\n## Transformer un client mécontent en ambassadeur\nRéglez le problème en dépassant les attentes :\n- Remboursement OU remplacement + coupon de réduction\n- Livraison gratuite sur la prochaine commande\n- Cadeau surprise avec le remplacement\n\nUn client dont le problème a été bien résolu est souvent plus fidèle qu''un client n''ayant jamais eu de problème.');

END $$;
