-- ============================================================
-- B. Enrichir Communication Professionnelle (~19 → 25 leçons)
--    et Entrepreneuriat (~18 → 25 leçons)
-- ============================================================

-- ============================================================
-- COMMUNICATION PROFESSIONNELLE
-- ============================================================
DO $$ DECLARE
  v_course_id uuid; v_module_id uuid;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE title ILIKE '%Communication%Professionnelle%' LIMIT 1;
  IF v_course_id IS NULL THEN RAISE NOTICE 'Communication non trouvée'; RETURN; END IF;

  -- Module : Écriture professionnelle
  INSERT INTO modules (course_id, title, position)
  VALUES (v_course_id, 'Écriture professionnelle efficace', 60)
  RETURNING id INTO v_module_id;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES
  (v_module_id, v_course_id, 'Structurer un email professionnel percutant', 'document', 1, false,
    E'# Structurer un Email Professionnel Percutant\n\n## La structure PACS\nUn email professionnel efficace suit 4 éléments :\n\n**P — Prise de contact** (1 ligne)\nPersonnalisée si possible. "Bonjour M. Koné," vaut mieux que "Bonjour,"\n\n**A — Accroche / contexte** (1-2 lignes)\nRappel de la raison de contact ou contexte commun.\n\n**C — Corps** (2-5 lignes max)\nL''information principale. Une seule idée par email.\n\n**S — Suite / Call-to-Action**\nQue doit faire le destinataire ? Soyez précis : "Pouvez-vous me confirmer avant vendredi 17h ?"\n\n## Les 10 erreurs à éviter\n\n1. **Objet vague** : "Question" → "Demande de devis prestation comptable — TECH CI SARL"\n2. **Trop long** : si l''email dépasse 150 mots, faites un appel\n3. **Pièce jointe sans annonce** : toujours mentionner "Veuillez trouver ci-joint..."\n4. **Majuscules** : perçues comme agressives en langage numérique\n5. **Pas de salutation finale** : "Cordialement," est le minimum\n6. **Répondre à tous** par défaut : vérifiez qui doit réellement recevoir\n7. **Emoji dans un email formel** : réservez-les aux échanges informels\n8. **Pas de signature** : nom, poste, téléphone, entreprise obligatoires\n9. **Envoyer sans relecture** : 30 secondes qui évitent des erreurs gênantes\n10. **Objet : RE: RE: RE: RE:**  — créez un nouveau fil si le sujet change\n\n## Modèles adaptés au contexte africain\n\n### Email de demande de rendez-vous\n```\nObjet : Demande de rendez-vous — Partenariat distribution Orange CI\n\nBonjour M. Adou,\n\nSuite à notre rencontre lors du SARA 2024, je souhaitais vous proposer \nun échange de 30 minutes sur les opportunités de distribution de nos \nproduits via votre réseau.\n\nSerais-je disponible pour vous rencontrer la semaine prochaine, \nde préférence mardi ou jeudi matin ?\n\nCordialement,\nFatou Diallo | Directrice Commerciale | FINTECH CI\n+225 07 XX XX XX XX\n```\n\n### Email de relance (sans insistance)\n```\nObjet : Suite à mon email du 15 octobre — Partenariat distribution\n\nBonjour M. Adou,\n\nJe me permets de relancer mon email du 15 octobre concernant \nnotre potentiel partenariat, au cas où il vous aurait échappé.\n\nN''hésitez pas si vous avez besoin d''informations complémentaires.\n\nCordialement,\nFatou Diallo\n```'),

  (v_module_id, v_course_id, 'Rédiger des rapports et comptes-rendus clairs', 'document', 2, false,
    E'# Rédiger des Rapports et Comptes-Rendus Clairs\n\n## La différence entre rapport et compte-rendu\n\n**Compte-rendu** : fidèle reflet de ce qui s''est dit/décidé en réunion.\n- Qui était présent\n- Ce qui a été discuté\n- Les décisions prises\n- Les actions à suivre (responsable + délai)\n\n**Rapport** : analyse + recommandations sur un sujet donné.\n- Contexte et objectif\n- Analyse des faits\n- Conclusions\n- Recommandations\n\n## Structure d''un compte-rendu de réunion\n\n```\nCOMPTE-RENDU DE RÉUNION\nDate : 5 octobre 2024\nLieu : Salle de conférence IBIG, Abidjan\nObjet : Revue mensuelle des ventes — Octobre 2024\n\nParticipants : [liste]\nAbsents excusés : [liste]\n\nOrdre du jour\n1. Bilan ventes septembre\n2. Objectifs octobre\n3. Point marketing\n\n--- DISCUSSIONS ---\n\n1. BILAN VENTES SEPTEMBRE\nCA réalisé : 4 250 000 FCFA vs objectif 5 000 000 FCFA (-15%)\nCauses identifiées : délais livraison fournisseur, 3 clients grands comptes en attente\n\nDÉCISIONS PRISES\n- Relancer les 3 clients grands comptes avant le 10/10\n  Responsable : Ama Kofi | Délai : 10/10/2024\n\n- Renégocier délais fournisseur\n  Responsable : Direction achats | Délai : 15/10/2024\n\nPROCHAINE RÉUNION : 5 novembre 2024 à 9h00\n```\n\n## Les 5 règles d''un bon rapport\n1. **Une idée par paragraphe** — jamais deux\n2. **Chiffres précis** : "CA en hausse" → "CA en hausse de 12% à 8,4M FCFA"\n3. **Conclusions avant les détails** : résumé exécutif en première page\n4. **Voix active** : "Nous recommandons" plutôt que "Il est recommandé"\n5. **Annexes pour les détails** : les tableaux lourds vont en annexe'),

  (v_module_id, v_course_id, 'Communication non-verbale et image professionnelle', 'document', 3, false,
    E'# Communication Non-Verbale et Image Professionnelle\n\n## Les 3 canaux de communication\nSelon les recherches en communication :\n- **7%** du message passe par les mots\n- **38%** passe par le ton et l''intonation\n- **55%** passe par le langage corporel\n\nCe que vous ne dites pas communique plus que ce que vous dites.\n\n## Les 6 éléments du langage corporel\n\n### 1. La posture\n**À faire :** dos droit, épaules ouvertes, pieds bien posés au sol\n**À éviter :** bras croisés (signe de fermeture), corps penché en arrière (désintérêt)\n\n### 2. Le contact visuel\n- Maintenir 60-70% du temps en conversation 1-to-1\n- Répartir le regard sur l''audience lors d''une présentation\n- Éviter de regarder ses notes en permanence\n\n### 3. Les gestes\n- Gestes ouverts = accessibilité et confiance\n- Mains visibles = transparence\n- Pointer du doigt = perçu comme agressif — préférez la main ouverte\n\n### 4. Les expressions faciales\n- Le sourire sincère engage la conversation\n- Froncement de sourcils = concentration (pas hostilité)\n- Hocher la tête = écoute active\n\n### 5. La voix\n- **Débit** : ni trop rapide (stress), ni trop lent (ennui)\n- **Volume** : adapté à l''espace\n- **Silence** : outil puissant — une pause de 2 secondes attire l''attention\n- **Intonation** : montante = question, descendante = affirmation\n\n### 6. La distance sociale\n- Zone intime (0-45cm) : famille, amis proches\n- Zone personnelle (45cm-1,2m) : collègues proches\n- Zone sociale (1,2-3,6m) : réunions professionnelles\n- Zone publique (>3,6m) : conférences, présentations\n\n## L''image professionnelle en Afrique\nLe dress code varie selon les cultures et entreprises. En Afrique de l''Ouest :\n- **Secteur bancaire/juridique** : costume-cravate ou tailleur\n- **PME tertiaire** : tenue business casual (chemise, pantalon de ville)\n- **Tenue africaine formelle (Wax, Kente, Boubou)** : parfaitement adaptée en contexte professionnel\n- **Règle universelle** : propre, soigné, adapté à l''occasion');

  -- Module : Gestion des situations difficiles
  INSERT INTO modules (course_id, title, position)
  VALUES (v_course_id, 'Gérer les situations de communication difficiles', 70)
  RETURNING id INTO v_module_id;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES
  (v_module_id, v_course_id, 'Donner et recevoir du feedback constructif', 'document', 1, false,
    E'# Donner et Recevoir du Feedback Constructif\n\n## Pourquoi le feedback est difficile ?\nCritiquer fait peur de blesser. Être critiqué active nos mécanismes de défense. Pourtant, le feedback bien formulé est le carburant de la progression professionnelle.\n\n## La méthode SBI pour donner un feedback\n\n**S — Situation** : décrivez le contexte précis\n**B — Behavior (Comportement)** : décrivez le comportement observable, pas la personnalité\n**I — Impact** : exprimez l''impact concret\n\n**Exemple :**\n❌ "Tu es toujours en retard et tu t''en fous."\n✅ "**Lors de la réunion client du lundi 3 octobre** (S), **tu es arrivé 20 minutes après le début** (B), **ce qui a mis notre client mal à l''aise et a raccourci le temps de présentation** (I)."\n\n## La méthode sandwich pour un feedback difficile\n1. **Point positif** — ce qui fonctionne bien\n2. **Point d''amélioration** — formulé en comportement observable\n3. **Encouragement** — confiance dans la capacité à progresser\n\n## Recevoir du feedback sans se défendre\n5 réflexes pour bien recevoir un feedback :\n1. **Écouter sans interrompre** — laissez la personne terminer\n2. **Poser des questions de clarification** : "Pouvez-vous me donner un exemple ?"\n3. **Remercier** : "Merci pour ce retour, je vais y réfléchir"\n4. **Prendre le temps** : vous n''êtes pas obligé de répondre immédiatement\n5. **Ne pas vous justifier** : même si vous n''êtes pas d''accord, noter et analyser d''abord\n\n## Feedback en contexte hiérarchique africain\nDans beaucoup d''entreprises africaines, critiquer un supérieur directement est tabou. Alternatives :\n- Le rapport écrit (moins frontal)\n- La réunion de bilan (cadre formel)\n- Le feedback anonyme via enquête interne\n- Le canal RH pour les points sensibles'),

  (v_module_id, v_course_id, 'Gérer les conflits interpersonnels au travail', 'document', 2, false,
    E'# Gérer les Conflits Interpersonnels au Travail\n\n## Les 5 styles de gestion de conflits\n\n| Style | Description | Quand l''utiliser |\n|-------|-------------|------------------|\n| **Évitement** | Reporter ou ignorer | Sujet mineur, mauvais timing |\n| **Accommodement** | Céder à l''autre | Relation > résultat |\n| **Compétition** | Imposer sa position | Urgence, enjeu éthique |\n| **Compromis** | Chacun cède un peu | Solutions équilibrées rapides |\n| **Collaboration** | Chercher une solution gagnant-gagnant | Enjeu important pour les deux parties |\n\nLe style **Collaboration** est le plus durable mais le plus exigeant.\n\n## Le processus de résolution en 5 étapes\n\n**1. Écoute séparée**\nRencontrez chaque partie séparément. Posez la question : "Quel est votre besoin fondamental dans cette situation ?"\n\n**2. Reformulation**\n"Si je comprends bien, ce qui vous pose problème c''est..."\n\n**3. Rencontre commune**\nPrésentez les besoins de chacun sans jugement. Cherchez les points communs.\n\n**4. Co-construction de solutions**\n"Qu''est-ce qui pourrait convenir aux deux parties ?"\n\n**5. Accord formalisé**\nMettez par écrit la solution retenue et les engagements de chacun.\n\n## Signaux d''alarme à gérer rapidement\n- Refus de se parler\n- Comportements passifs-agressifs (sabotage, retard délibéré)\n- Coalition contre un collègue\n- Impact sur les performances de l''équipe\n\nCes situations nécessitent une intervention RH rapide.');

  RAISE NOTICE 'Communication enrichie avec succès';
END $$;


-- ============================================================
-- ENTREPRENEURIAT
-- ============================================================
DO $$ DECLARE
  v_course_id uuid; v_module_id uuid;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE title ILIKE '%Entrepren%' LIMIT 1;
  IF v_course_id IS NULL THEN RAISE NOTICE 'Entrepreneuriat non trouvé'; RETURN; END IF;

  -- Module : Financer et structurer son entreprise
  INSERT INTO modules (course_id, title, position)
  VALUES (v_course_id, 'Financer et structurer son entreprise', 60)
  RETURNING id INTO v_module_id;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES
  (v_module_id, v_course_id, 'Choisir la forme juridique adaptée à votre projet', 'document', 1, false,
    E'# Choisir la Forme Juridique Adaptée à Votre Projet\n\n## Les principales formes juridiques en Afrique de l''Ouest (OHADA)\n\n### 1. Entreprise individuelle (EI)\n- **Capital** : aucun minimum\n- **Responsabilité** : illimitée sur le patrimoine personnel\n- **Idéal pour** : artisans, commerçants débutants, auto-entrepreneurs\n- **Inconvénient** : confusion patrimoine perso/professionnel\n\n### 2. SARL (Société à Responsabilité Limitée)\n- **Capital minimum** : 1 000 000 FCFA (OHADA)\n- **Associés** : 1 à 50 personnes\n- **Responsabilité** : limitée aux apports\n- **Idéal pour** : PME bien établies, projet à plusieurs associés\n- **Avantage** : protection du patrimoine personnel\n\n### 3. SAS (Société par Actions Simplifiée)\n- Capital minimum : 1 FCFA (très souple)\n- Gouvernance très flexible\n- **Idéal pour** : startups, levée de fonds, projets innovants\n- Moins connue des banques africaines\n\n### 4. SA (Société Anonyme)\n- Capital minimum : 10 000 000 FCFA\n- Conseil d''administration obligatoire\n- **Idéal pour** : grandes entreprises, introduction en bourse\n\n## Tableau comparatif simplifié\n\n| Critère | EI | SARL | SAS |\n|---------|-----|------|-----|\n| Capital minimum | 0 | 1M FCFA | 1 FCFA |\n| Protection perso | Non | Oui | Oui |\n| Nb associés | 1 | 1-50 | Illimité |\n| Complexité | Faible | Moyenne | Moyenne |\n| Levée fonds | Non | Difficile | Oui |\n\n## Comment choisir ?\n- **Solo, petit projet** → Entreprise individuelle\n- **2-5 associés, PME classique** → SARL\n- **Startup tech, levée de fonds prévue** → SAS\n- **Grands projets, investisseurs** → SA\n\n## Coûts de création estimés en Côte d''Ivoire (2024)\n- Frais de notaire : 150 000 - 300 000 FCFA\n- Inscription registre commerce : 50 000 - 100 000 FCFA\n- Délai moyen (CEPICI) : 48h à 5 jours ouvrés\n\n**Conseil** : Consultez un notaire ou un cabinet juridique avant de vous décider. Le coût de la consultation (50 000-100 000 FCFA) est largement rentabilisé.'),

  (v_module_id, v_course_id, 'Trouver des financements pour votre entreprise africaine', 'document', 2, false,
    E'# Trouver des Financements pour Votre Entreprise Africaine\n\n## Les sources de financement selon la maturité\n\n### Phase 0 : Amorçage (0 - 6 mois)\n**Fonds propres et "Love Money"**\n- Votre épargne personnelle\n- Famille et amis proches\n- Tontines et associations d''épargne\n- Avantage : pas de remboursement, pas de dilution\n\n### Phase 1 : Démarrage (6 mois - 2 ans)\n**Microfinance et banques locales**\n- OIKOCREDIT, Advans, ACEP : prêts PME 500K - 5M FCFA\n- Crédit rural avec garantie (équipements, stock)\n- FAIJ (Fonds d''Appui aux Jeunes) — Côte d''Ivoire\n- FDFP (Fond de Développement de la Formation Professionnelle)\n\n### Phase 2 : Croissance (2 - 5 ans)\n**Investisseurs et subventions**\n- Fonds d''investissement (Partech Africa, Orange Ventures, Uncork Capital)\n- BOAD (Banque Ouest-Africaine de Développement)\n- ADB (African Development Bank) — via projets\n- Concours entrepreneuriaux : Orange Social Venture Prize, Total Energies Startupper\n\n### Phase 3 : Expansion\n**Marchés financiers**\n- BRVM (Bourse Régionale des Valeurs Mobilières) — Abidjan\n- Obligations corporate\n- Private Equity\n\n## Préparer votre dossier de financement\n\nChaque bailleur veut voir :\n1. **Business plan** (5-10 pages max) avec prévisions sur 3 ans\n2. **Bilans comptables** si entreprise existante (2-3 ans)\n3. **Identité et casier judiciaire**\n4. **Garanties disponibles** (caution personnelle, bien immobilier, équipements)\n5. **Plan d''utilisation des fonds** (comment sera dépensé chaque FCFA)\n\n## Erreurs qui font rejeter un dossier\n- Business plan trop optimiste sans justification\n- Absence de fonds propres (les banques veulent voir que vous risquez aussi)\n- Pas de garantie pour les prêts classiques\n- Dossier incomplet ou incohérent'),

  (v_module_id, v_course_id, 'Construire votre réseau entrepreneurial en Afrique', 'document', 3, false,
    E'# Construire Votre Réseau Entrepreneurial en Afrique\n\n## Pourquoi le réseau est vital en Afrique ?\nEn Afrique de l''Ouest, la culture des affaires repose fortement sur la confiance interpersonnelle et les recommandations. Un marché public, un contrat commercial, une association stratégique — beaucoup se concrétisent grâce au réseau plutôt qu''aux appels d''offres.\n\n## Les 5 cercles de réseau entrepreneurial\n\n**Cercle 1 : Les mentors**\nTrouvez 2-3 entrepreneurs expérimentés prêts à vous conseiller. Cherchez-les dans les associations professionnelles (CGECI, CPME, Chambre de Commerce).\n\n**Cercle 2 : Les pairs**\nEntrepreneurs à votre niveau. Échangez des bonnes pratiques, partagez des défis communs. Rejoignez ou créez un "mastermind" de 5-8 personnes.\n\n**Cercle 3 : Les clients potentiels**\nLe réseau n''est pas que professionnel. Chaque contact est un client potentiel ou une recommandation.\n\n**Cercle 4 : Les prestataires et partenaires**\nComptable, avocat, graphiste, imprimeur... Constituez votre carnet d''adresses de prestataires de confiance.\n\n**Cercle 5 : Les prescripteurs**\nPersonnes influentes qui peuvent vous recommander : journalistes, responsables d''associations, leaders d''opinion.\n\n## Où trouver votre réseau ?\n- **Chambres de Commerce** (CCIAM Abidjan, CCIA Dakar...)\n- **Hubs entrepreneuriaux** : Akendewa, Africa Tech Lab, ViVaTech Africa\n- **LinkedIn** : profil professionnel complet, publier 1-2x/semaine\n- **Événements sectoriels** : SARA, SIAO, Africa CEO Forum, GITEX Africa\n- **Associations sectorielles** : selon votre domaine\n- **Alumni d''écoles de commerce** : INSCAE, CESAG, HECI...\n\n## La règle du "Give First"\nDonnez avant de demander. Partagez vos contacts, recommandez des prestataires, offrez votre expertise. La générosité construit une réputation qui attire naturellement les opportunités.');

  -- Module : Scaler et pérenniser son entreprise
  INSERT INTO modules (course_id, title, position)
  VALUES (v_course_id, 'Faire croître et pérenniser votre entreprise', 70)
  RETURNING id INTO v_module_id;

  INSERT INTO lessons (module_id, course_id, title, type, position, is_free_preview, content) VALUES
  (v_module_id, v_course_id, 'Passer de l''artisan à l''entrepreneur : systèmes et délégation', 'document', 1, false,
    E'# Passer de l''Artisan à l''Entrepreneur\n\n## Le piège de l''artisan entrepreneur\nBeaucoup de fondateurs créent une entreprise mais continuent à travailler DANS l''entreprise plutôt que SUR l''entreprise. Résultat : si vous vous arrêtez, l''activité s''arrête.\n\n**Artisan** : exécute le travail lui-même, indispensable à chaque opération\n**Entrepreneur** : crée des systèmes qui permettent à l''entreprise de fonctionner sans lui\n\n## Créer vos premiers systèmes\n\n### 1. Procédures opérationnelles standard (SOP)\nDocumentez chaque processus répété :\n- Comment répondre à une demande client\n- Comment établir une facture\n- Comment gérer une réclamation\n- Comment onboarder un nouvel employé\n\nFormat simple : déclencheur → étapes numérotées → résultat attendu\n\n### 2. Les outils de gestion incontournables\n- **Trello / Asana** : gestion des tâches et projets\n- **WhatsApp Business** : communication client (gratuit, omniprésent en Afrique)\n- **Wave / Orange Money** : encaissements\n- **Excel ou Google Sheets** : suivi financier\n- **Google Drive** : stockage et partage de documents\n\n### 3. Déléguer avec efficacité\n\nLa matrice de délégation :\n| Compétence de votre équipe | Faible | Haute |\n|---------------------------|--------|-------|\n| **Enjeu élevé** | Former + Superviser | Déléguer + Faire confiance |\n| **Enjeu faible** | Déléguer + Vérifier | Déléguer totalement |\n\n**Règle des 70%** : Si quelqu''un peut faire la tâche à 70% aussi bien que vous, déléguez. Le 30% restant s''améliore avec la pratique.\n\n## Les 4 rôles de l''entrepreneur mature\n1. **Visionnaire** : où va l''entreprise dans 3-5 ans ?\n2. **Manager** : les équipes ont-elles ce qu''il faut pour réussir ?\n3. **Communicant** : les parties prenantes sont-elles informées et engagées ?\n4. **Gardien de la culture** : les valeurs de l''entreprise sont-elles vécues ?'),

  (v_module_id, v_course_id, 'Mesurer la performance de votre entreprise : les KPIs essentiels', 'document', 2, false,
    E'# Mesurer la Performance : Les KPIs Essentiels pour PME\n\n## Pourquoi mesurer ?\n"Ce qui ne se mesure pas ne s''améliore pas." Sans indicateurs, vous pilotez à l''aveugle.\n\n## Les 4 catégories de KPIs pour une PME\n\n### 1. KPIs Financiers\n| Indicateur | Formule | Cible recommandée |\n|-----------|---------|-------------------|\n| Chiffre d''affaires | Somme des ventes | +15-20%/an |\n| Marge brute | (CA - Coût des ventes) / CA | >40% (services) |\n| Trésorerie nette | Entrées - Sorties | Toujours positive |\n| Délai paiement clients | Créances / CA × 365 | <45 jours |\n\n### 2. KPIs Commerciaux\n| Indicateur | Formule | |\n|-----------|---------|--|\n| Taux conversion | Clients / Prospects × 100 | >15-20% |\n| Panier moyen | CA / Nb de transactions | Augmenter de 10%/an |\n| Taux fidélisation | Clients récurrents / Total clients | >60% |\n| Coût acquisition client (CAC) | Budget marketing / Nb nouveaux clients | < LTV/3 |\n\n### 3. KPIs Opérationnels\n- Délai de livraison moyen\n- Taux de réclamations clients\n- Productivité par employé (CA / Nb employés)\n\n### 4. KPIs RH\n- Turnover annuel (cible : <20%)\n- Taux d''absentéisme (cible : <5%)\n- NPS employés (enquête satisfaction interne)\n\n## Tableau de bord simple (hebdomadaire)\nCréez un Google Sheet avec 5-7 indicateurs max :\n- CA semaine vs. objectif\n- Nouvelles commandes\n- Trésorerie\n- 1 indicateur opérationnel clé\n- 1 indicateur RH\n\nRévision : 15 minutes chaque lundi matin. Décision si écart >10% vs. objectif.');

  RAISE NOTICE 'Entrepreneuriat enrichi avec succès';
END $$;
